### ISSUE TITLE
MXML support

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/vscode-nextgenas#10]
- [x] Syntax coloring
- [ ] Completion
- [x] Goto Definition
- [x] Rename
- [x] Document Symbol
- [x] Workspace Symbol
- [x] Hover
- [x] Find All References
- [x] ActionScript inside `<fx:Script>`

**Comment by Harbs** [comment]
I'm not sure if you have this item in your list, but currently "Command + /" adds an XML comment to ActionScript inside an <fx:Script> tag instead of an ActionScript comment.

**Comment by joshtynjala** [comment]
I'll look into it! That part of VSCode may not be robust enough to know about two languages in one file, though.
