### ISSUE TITLE
FlexJS 0.8.0 basic app error with Alert.show

### ISSUE THREAD

**Issue by gdeverlant** [BowlerHatLLC/vscode-nextgenas#102]
Main.mxml
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:js="library://ns.apache.org/flexjs/basic">
	<js:initialView>
		<js:View>
			<js:Label text="Hello World"/>
			<js:TextButton text="Click Me !" click="onButtonClicked(event)" />
		</js:View>
	</js:initialView>
	<js:valuesImpl>
		<js:SimpleCSSValuesImpl />
	</js:valuesImpl>

	<fx:Script>
		<![CDATA[
			import org.apache.flex.events.MouseEvent;
			import org.apache.flex.html.Alert;

			
			private function onButtonClicked(e:MouseEvent):void{
				Alert.show("Yehhhhaaaaa !", this);
			}
		]]>
	</fx:Script>

</js:Application>
```

![image](https://user-images.githubusercontent.com/26530975/27087725-152885b2-5056-11e7-818a-c83605ad1e70.png)

![image](https://user-images.githubusercontent.com/26530975/27087757-29fe3cc0-5056-11e7-90f9-99590c8d86dd.png)

**Comment by joshtynjala** [comment]
Can you delete your bin directory and try again?

In the future, if you have issues with FlexJS, it would be better to post to the Flex users mailing list. This is the Github project for the NextGen ActionScript extension for Visual Studio Code. It certainly supports FlexJS, but it's a separate project.

**Comment by gdeverlant** [comment]
Correct!

But the Alert box is not displayed correctly

![image](https://user-images.githubusercontent.com/26530975/27091037-39c3a3da-505f-11e7-969e-6b48dfa396b4.png)

**Comment by joshtynjala** [comment]
Perhaps there's a bug in FlexJS! It is beta-quality, so I'm sure you will run into a number of bugs along the way.

**Comment by joshtynjala** [comment]
FYI: There is already an existing bug report for the Alert issue you discovered.

[FLEX-35305: org.apache.flex.html.Alert: header background bleeds outside border on right side](https://issues.apache.org/jira/browse/FLEX-35305)
