### ISSUE TITLE
Errors being written to Output in 0.5.0

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-nextgenas#108]
I noticed some errors being written to output while editing an MXML file:

The following error happened when I added initComplete="init()" to the component before I created the init() function
[Error - 11:16:39 AM] Request textDocument/signatureHelp failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 

And this is the entry in the log:
https://paste.apache.org/KLAG

The second error happened while moving my mouse between the same file and the Output pane:

[Error - 11:19:19 AM] Request textDocument/hover failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
With this log entry:
https://paste.apache.org/OEO1

**Comment by joshtynjala** [comment]
Thanks! I can reproduce this issue.
