### ISSUE TITLE
Extra lines in output

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-nextgenas#109]
This is a minor annoyance, but if it's an easy fix it would be nice.

When compiling from VS Code, I'm getting 184 line returns after the compiler output. This makes the results of the output scroll up off the screen. I need to page up a few times to see the results. This was true when using task.json as well as in the terminal output using 0.5.0.

I'm not sure exactly when this started, but it doesn't feel like this was the case some months back.

Is anyone else seeing this? Any idea what's outputting all those extra line returns?

**Comment by Harbs** [comment]
Just to clarify: When using ant to compile in Terminal or the integrated terminal in VS Code, I'm not getting these extra line returns.

**Comment by Harbs** [comment]
I just tried using asconfigc directly from the command line and I'm getting the line returns with no VS Code involvement, so it looks like an asconfigc issue.

**Comment by joshtynjala** [comment]
This issue is fixed in today's v0.5.2 update to asconfigc.
