### ISSUE TITLE
Definitions can't be found after 0.8.0 upgrade

### ISSUE THREAD

**Issue by tlhinman** [BowlerHatLLC/vscode-nextgenas#110]
I started receiving an error that Apache FlexJS 0.8.0 or newer was required. I used NPM to install this and changed my VSCode settings and environment variables accordingly. That got rid of the error, but now, every time I hover over a variable, I get

```
Request textDocument/hover failed.
Message: Internal error, please look at the server's logs.
Code: -32603
```

Selecting "Go to definition" has a similar effect, with "hover" replaced by "definition" above.

This problem persists whether I install FlexJS globally (putting it in /usr/local/) or otherwise (putting it in /Users/me/). Thanks for any assistance you can provide.

**Comment by joshtynjala** [comment]
I assume that you're using the new version 0.5.0 of the extension? If not, please upgrade!

Starting with 0.5.0, you don't need to set `nextgenas.sdk.editor` in VSCode's settings anymore. If you have that set, clear it and see if it makes a difference.

**Comment by tlhinman** [comment]
Yes, I have 0.5.0. That setting is now out of my settings file. (It still appears in the list of searchable default settings, but since I can't change that, I assume it doesn't matter.) No effect, I'm afraid. nextgenas.sdk.framework is being automatically populated in the workspace settings, but I'm guessing that's also expected.

I tried the installation via the installer (DMG) but still no dice.

**Comment by joshtynjala** [comment]
nextgenas.sdk.framework will indeed get populated if you click the SDK item in the status bar and use the SDK picker.

I'm not sure what you're referring to when you mention a DMG file...

**Comment by joshtynjala** [comment]
If you open the Output panel, you should see an option to view Output specifically from the extension (that's the log the error is referring to). If you see something there, can you copy and paste it here?

**Comment by tlhinman** [comment]
Sorry; by DMG I just meant a Mac disk image, i.e. an executable with a GUI rather than a simple NPM command-line installation.

I'm afraid I can't find any other output via that panel. I generated a few errors, which show up in the "ActionScript and MXML Language Server" category in the dropdown on the right. I change that to "Extensions" and there's nothing there. Then, when I generate a few more errors, it automatically switches the dropdown back to AS/MXML to display the new ones.

**Comment by joshtynjala** [comment]
FlexJS doesn't come in a DMG... So I'm a little confused. Do you mean the Flex SDK Installer app? I guess that might come as a DMG.

I was mistaken about the logs. If you open the VSCode command palette, you can search for the developer tools and get some more errors from the console in there!

**Comment by tlhinman** [comment]
Oh, yeah, sorry. I meant [this thing](https://github.com/BowlerHatLLC/vscode-nextgenas/issues/100#issuecomment-308123574).

OK, got something pretty verbose from the console. Attached.
[ngaslog.txt](https://github.com/BowlerHatLLC/vscode-nextgenas/files/1168380/ngaslog.txt)

**Comment by joshtynjala** [comment]
Thanks! That should be helpful. Looks like there's a null pointer exception that I can try to reproduce.

Can you also share your asconfig.json? That might give me some more clues.

**Comment by tlhinman** [comment]
Not much to it. In its entirety:

`
{
    "config": "flex",
    "compilerOptions": {
        "source-path": [
            "as3"
        ]
    }
}
`

**Comment by joshtynjala** [comment]
Haha! I was just writing this comment when yours appeared. It looks like this error can happen when the "files" field is missing in asconfig.json. You'll want to modify your asconfig.json file to look something like this:

```
{ "config": "flex", "compilerOptions": { "source-path": [ "as3" ] }, "files": ["path/to/MainClass.as"] }
```

I'll make sure to update the extension show a proper error when this field is missing.

**Comment by tlhinman** [comment]
Thanks! I thought I had that field in there when this problem started, but maybe I'm misremembering and I had source-path or something. In any case, looks like this is rectified. Many thanks again!
