### ISSUE TITLE
Error in MXML

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-nextgenas#113]
The following MXML causes an error in VS Code but successfully compiles:

	<fx:Style>
		.mdl-slider {
			width: calc(100% - 10px);
			margin: 0px;
		}
	</fx:Style>

It generates the following error in the problems palette:

file: 'file:///Users/harbs/Documents/git/PrintUI/printui-flexjs/PortedPrintUI/src/com/printui/view/components/PaletteSlider.mxml'
severity: 'Error'
message: 'Internal error in ABC generator subsystem, when generating code for: /Users/harbs/Documents/git/PrintUI/printui-flexjs/PortedPrintUI/src/com/printui/view/components/PaletteSlider.mxml: java.lang.NullPointerException
'
at: '1,1'
source: ''

Removing the line with calc() makes the error go away.

I'm using the nightly SDK in the likely case that this matters. (I think this css is something that was recently fixed.)

**Comment by Harbs** [comment]
Placing the css in the complied css also has issues with the compiled js.

**Comment by Harbs** [comment]
I think calc is still not quite working, so this is probably a bug in the compiler and not the extension.

**Comment by joshtynjala** [comment]
I assume that nextgenas.sdk.editor is set to the same SDK as the one you are using to compile?
