### ISSUE TITLE
asconfigc doesn't work when trying to build on Mac OSX

### ISSUE THREAD

**Issue by yvant** [BowlerHatLLC/vscode-nextgenas#118]
Hello, 

I followed the steps to try to compile a simple AS3 script.
I installed asconfigc on the terminal with npm install -g asconfigc and it seemed to install properly.
I have the flex sdk installed too. But when I try Run Build Task..., then I get a code 1 error specifying that asconfigc can not be executed.
In the terminal, when I input asconfigc, I get the following error:
-bash: asconfigc: command not found

What can I do?

Thank you!

**Comment by joshtynjala** [comment]
Something seems to be wrong with your installation of Node or npm. You could try reinstalling Node. Make sure it's at least Node 6, which is the latest LTS release.

If bash/Terminal can't find asconfigc when you install with `npm install -g asconfigc`, then the directory where npm installs its executables must be missing from the PATH environment variable, for some reason. I don't know what would cause it to be removed (or never added in the first place). This issue will affect anything that you try to install globally with npm in the future, though, so it's not specific to asconfigc.

**Comment by joshtynjala** [comment]
Were you able to get it figured out?

**Comment by yvant** [comment]
Yep, I just reinstalled npm, actually I didn't run it in root mode. I am not a mac expert, I am just figuring out how it works. Thanks!

**Comment by joshtynjala** [comment]
Great!
