### ISSUE TITLE
Including swc file

### ISSUE THREAD

**Issue by yvant** [BowlerHatLLC/vscode-nextgenas#119]
Hi, 

I managed to compile and debug a simple pure AS3 project, but now I need to include some swc libraries. How can I do that with Visual Studio Code?

Thanks!

**Comment by neminovno** [comment]
What did you use to include SWC? Maybe https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/asconfig.json#library-path ?

**Comment by yvant** [comment]
Yes, and actually I was able to make it work!

Now I have another issue: the package name of my Main.as doesn't fit. Actually I'm using a FlashDevelop project, and I'm trying to make it work with Visual Code Studio.

My folders go like this:
ProjectFolder/src/net/host/gameName/Main.as
package for Main.as is net/host/gameName

I put asconfig.json in ProjectFolder
the file property in asfing.json is
"files":
	[
		"src/net/host/gameName/Main.as"
	]
Doing so, the project won't compile. Put if I change the package of Main.as from net/host/gameName to "", it does compile.

How can I do to keep src/net/host/gameName as the package?

**Comment by joshtynjala** [comment]
The main class can't be in a package. I believe this is a limitation of the "Falcon" compiler that the extension uses for code intelligence.

**Comment by yvant** [comment]
Ok, thanks for the information!
