### ISSUE TITLE
Not stopping at breakpoints in main class constructor

### ISSUE THREAD

**Issue by JohnSword** [BowlerHatLLC/vscode-nextgenas#12]
Ok, so I managed to get the compiling working on my mac, it now produces the bin folder and the output js files. The debugger executes the compile task then fires the chrome browser and the script runs but it doesn't stop at the breakpoints. I'm trying to debug using the local file option as per instructions.

**Comment by joshtynjala** [comment]
Are you adding the breakpoint in the constructor of the main class? Last time I tried that, it didn't work for some reason. I suspect that the debugger hasn't fully connected yet. Try adding a breakpoint in an event listener somewhere, and you should see a difference.

Also, when using Chrome, make sure to exit the browser entirely and let VSCode launch it. The debugger won't work unless special command line options are passed in, so if it's already running, it won't work.

**Comment by JohnSword** [comment]
humm, I set a on click event and the breakpoint worked but I cant get it to stop on page load.
I tried with: window.addEventListener("load", onLoad, true)
The onLoad function is called but again the breakpoint fails. Do you have an idea how one could set a breakpoint in the constructor to break on page load?

**Comment by joshtynjala** [comment]
I'm not sure. Like I said, it seems like VSCode's debugger might not be fully connected until after page load or something.

If you open Chrome's developer tools directly, and use its built-in debugger, a breakpoint in the constructor will work correctly, so it seems to be a VSCode issue.

**Comment by JohnSword** [comment]
thanks Josh, I got it working by setting an interval, like so:
interval = setInterval(onLoad,1000);

for debugging this is enough.

**Comment by joshtynjala** [comment]
I found that if you add a `debugger` statement to your HTML page before you instantiate the main class constructor, the VSCode debugger will pause there as if there were a breakpoint. If you continue the debugging session, your breakpoints will work.

I added a more detailed description about this to the documentation:

https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Common-issues#debugger-will-not-stop-at-breakpoints-on-startup
