### ISSUE TITLE
Can't access recent methods (eg: Bitmap.drawWithQuality)

### ISSUE THREAD

**Issue by yvant** [BowlerHatLLC/vscode-nextgenas#120]
I have some issues with recent methods in my code, making me unable to compile.
I added the required version of the swf but it doesn't seem to work:
{
	"compilerOptions": {
		"swf-version":37,
...

My Flex sdk is 4.6.0...

Am I missing something?

Thanks!

**Comment by joshtynjala** [comment]
That's a bug in the extension. Thanks for pointing it out! I've only tested with SDKs that automatically use the correct swf-version value. It's been years since I merged Flex 4.6 with an AIR SDK and had to set swf-version manually.

As a workaround for now, you should be able to set swf-version in the additionalOptions field of your asconfig.json file.

**Comment by yvant** [comment]
So I tried to use additionalOptions, but it didn't work, I still can't compile because of the drawWithQuality method. Here's my asconfig.json:
{
	"compilerOptions": {
		"output": "bin/game.swf",
		"library-path": [
			"lib/as3-signals-v0.8.swc",
			"lib/as3corelib.swc",
			"lib/greensock.swc",
			"swc/game-Sounds.swc",
			"swc/game-Graph.swc"
		],
		"define": [
			{
				"name": "CONFIG::AIR",
				"value": false
			},
			{
				"name": "CONFIG::CHEAT",
				"value": true
			}
		]
	},
	"additionalOptions": "-swf-version=37",
	"files":
	[
		"src/Main.as"
	]
}

**Comment by joshtynjala** [comment]
Where in the SDK did you put the updated playerglobal.swc? You may need to specify -target-player too.

**Comment by joshtynjala** [comment]
Okay, I determined that it was indeed `target-player` option that is necessary. Using `target-player` tells the compiler to use the appropriate *playerglobal.swc* file, like *frameworks/libs/player/26.0/playerglobal.swc*. If it uses the default *playerglobal.swc* file for version 11.1 instead, the SWC won't even have newer APIs, like drawWithQuality().

Similar to `swf-version`, it's necessary to add `target-player` to additionalOptions in the current version of the extension.

```
"additionalOptions": "-swf-version=37 -target-player=26.0"
```

In the next version of vscode-nextgenas, you won't need these in additionalOptions.
