### ISSUE TITLE
Error: Missing builtin type Object (1,1)

### ISSUE THREAD

**Issue by bigosmallm** [BowlerHatLLC/vscode-nextgenas#122]
I am using VS Studio Code 1.15.1
![image](https://user-images.githubusercontent.com/1650037/30047741-9609cc88-91c7-11e7-9c40-44213c12af0b.png)

I used `yo flexjs` to set up a brand new project.  
I set up FlexJS 0.8 as the SDK.  The SDK was installed via `npm install flexjs -g`

I am seeing this error:
![image](https://user-images.githubusercontent.com/1650037/30047723-7c77af4c-91c7-11e7-90b0-c6b0b6256967.png)

Here is the console log:
![image](https://user-images.githubusercontent.com/1650037/30047810-e894df1a-91c7-11e7-9bb6-ddb9addd2fc0.png)

**Comment by joshtynjala** [comment]
For some reason, the compiler doesn't seem to be able to find playerglobal.swc (or maybe js.swc). Maybe you should try reinstalling the SDK.

**Comment by joshtynjala** [comment]
Can you share your asconfig.json file?

**Comment by bigosmallm** [comment]
Here it is:
{
  "compilerOptions": {
    "targets": [
      "JSFlex"
    ]
  },
  "files": [
    "src/First.mxml"
  ]
}

And it turns out that the error occurs only with the npm installed version of FlexJS 0.8.0.
The issue goes away with the Installer installed versio of FlexJS 0.8.0

**Comment by joshtynjala** [comment]
I just tried uninstalling and reinstalling the npm version of FlexJS, and it's working fine for me. I tried on both macOS and Windows.

**Comment by bigosmallm** [comment]
Huh, that is weird.  Let me dig deeper to see what is causing the issue on my side.

**Comment by joshtynjala** [comment]
Closing. Feel free to re-open if you find anything!
