### ISSUE TITLE
Recommended for AIR development? 

### ISSUE THREAD

**Issue by PippoApps** [BowlerHatLLC/vscode-nextgenas#124]
Hi,
it is not clear to me after eading documentation if this is aimed mostly at FlexJS or also developing coupled with Animate CC for AIR/SWF export. Would you recommend NextGenAS/VisualStudio for AIR development?
cheers

**Comment by joshtynjala** [comment]
Yes, absolutely! It's worth adding that I use VSCode every single day to develop [Feathers UI](https://feathersui.com/), the popular UI component library for Starling Framework.

You can see here that I have documentation written specifically for AIR development:

https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Adobe-AIR
https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Debug-an-Adobe-AIR-mobile-application-with-Visual-Studio-Code

**Comment by PippoApps** [comment]
Fantastic Josh, thank you!

**Comment by joshtynjala** [comment]
I tried to update some of the documentation to make it more clear that AIR and Flash Player are supported with the extension. Hopefully, that will answer the questions of others who might be wondering in the future!
