### ISSUE TITLE
Wiki: missing example `asconfig.json` for AIR library project (swc)

### ISSUE THREAD

**Issue by soimy** [BowlerHatLLC/vscode-nextgenas#125]
First of all, thank you @joshtynjala for this great extension. I finally become a happy as3 coder in macOS.
I think the wiki is missing a little piece of example `asconfig.json` for AIR library (swc) setup. It took me  a while... ( almost a week ) to figure out a functional one:
```json
{
    "config": "air",
    "type": "lib",
    "compilerOptions": {
        "output": "bin/some-library.swc",
        "source-path": [ "src" ],
        "library-path": [ "lib" ],
        "include-sources": [ "src" ]
    }
}
```
note that the `include-sources` or `include-class` is a must for `swc` just like `files` for `swf`. Without it, always "critical and error detection disabled"

**Comment by joshtynjala** [comment]
Yes, an example for creating a SWC project is a good idea!

**Comment by joshtynjala** [comment]
https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Create-a-new-ActionScript-library-project-in-Visual-Studio-Code
