### ISSUE TITLE
Wrong behavior while Debuging (Step over/in/out)

### ISSUE THREAD

**Issue by soimy** [BowlerHatLLC/vscode-nextgenas#126]
Only tested on AIR SWF project (AIR SDK 26.0.0.118) on Nextgen-Actionscript 0.5.1
Step over action is very unpredictable. Some it will act like continue, sometimes act as step in. Not sure if the problem lies in adobe adl or nextgenas extension.

I've packed a minimal project to reproduce the bug.
[as3test.zip](https://github.com/BowlerHatLLC/vscode-nextgenas/files/1286851/as3test.zip)

**Comment by joshtynjala** [comment]
This was fixed in commit 5bbc4da6aeb650b2bec9e7ca26c007a43a8e83ef, and it will be included in the next version! 😄
