### ISSUE TITLE
swf debugger : stepover(f10) error

### ISSUE THREAD

**Issue by tertis** [BowlerHatLLC/vscode-nextgenas#127]
- error messsage
unknown request command: setExceptionBreakpoints

**Comment by joshtynjala** [comment]
Strange, I don't know what exception breakpoints have to do with step over.

Regardless, this issue may be fixed in commit 5bbc4da6aeb650b2bec9e7ca26c007a43a8e83ef, which will be included in the upcoming v0.6.

**Comment by tertis** [comment]
I tried to build and test. 
this feature working well. thank you your answer.

**Comment by joshtynjala** [comment]
Great!
