### ISSUE TITLE
FlexJS: asconfig.json example on VS code extension homepage.

### ISSUE THREAD

**Issue by rrefsland** [BowlerHatLLC/vscode-nextgenas#129]
Great extension...  

Wondering....could the example shown on the VS Code extension homepage get updated to below?  The example errors out, but below works fine.  

```
{
	"config": "flex",
	
	"compilerOptions": {
		"js-output-type": "flexjs"
    },
    "files":
    [
		"src/main/flex/DataGridExample.mxml"
    ]
}
```

![image](https://user-images.githubusercontent.com/15321147/30524132-79c0b474-9bb3-11e7-8926-994ad1284268.png)

**Comment by joshtynjala** [comment]
Hmm... That seems to be a bug in the extension. The config field is supposed to be optional.

By the way, you should definitely use targets and not js-output-type.

**Comment by joshtynjala** [comment]
I thought about this some more, and I think you may actually be using an old version of asconfigc. Even if you just installed asconfigc for the first time, that can happen if you have an outdated version of Node.js installed. Currently, asconfigc requires Node.js 6, but some older versions of asconfigc didn't have a minimum version requirement, so they can still be installed with older versions of Node.js.

Make sure that you're running Node.js 6 or newer, and then try reinstalling asconfigc. Thanks!

**Comment by joshtynjala** [comment]
Closing. I'm going to assume that you got it fixed by updating to Node.js 6.
