### ISSUE TITLE
Terminal will be reused by tasks, press any key to close it.

### ISSUE THREAD

**Issue by Simon-wu** [BowlerHatLLC/vscode-nextgenas#131]
I use vscode bulid a air project   debug code
`> Executing task: C:\Users\CH\AppData\Roaming\npm\asconfigc.cmd --debug=true --flexHome D:/Program Files/Adobe/Adobe Flash Builder 4.7 (64 Bit)/eclipse/plugins/com.adobe.flash.compiler_4.7.0.349722/AIRSDK <

正在加载配置: D:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\frameworks\airmobile-config.xml

在 1.288 秒内向 F:\TestProject\Knock\bin-debug\Knock.swf 写入了 1911 个字节

Terminal will be reused by tasks, press any key to close it.`

**Comment by joshtynjala** [comment]
I don't see any errors in your terminal output. What seems to be the problem?
