### ISSUE TITLE
Cannot determine executable for debug adapter 'null' with Java 9

### ISSUE THREAD

**Issue by stijnvanderlaan** [BowlerHatLLC/vscode-nextgenas#136]
I'm getting this error when I try to run this debug:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "swf",
      "request": "launch",
      "name": "Launch Site",
      "program": "bin/index.html"
    }
  ]
}
```

**Comment by joshtynjala** [comment]
It appears that Visual Studio Code is having trouble finding Java on your machine. Either you don't have Java installed, or the extension cannot find it, for some reason. You may need to customize the [`nextgenas.java` setting](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Extension-settings#nextgenasjava).

**Comment by stijnvanderlaan** [comment]
I did, I tried:
/usr/bin/java
/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java
/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java

Every time, after I restart Visual Studio Code, I get the error again. I also tried to reinstall jre.

**Comment by joshtynjala** [comment]
Hmmm... I haven't tested with Java 1.9 yet. Can you try installing Java 1.8 to see if that works better for you? You can have both versions installed side-by-side if you need Java 1.9 for other things.

**Comment by stijnvanderlaan** [comment]
Tnx, installing 1.8 works.

**Comment by joshtynjala** [comment]
Okay, thank you! I'll try to get that fixed in the next update.
