### ISSUE TITLE
Wishlist: make it possible to open localhost when debugging

### ISSUE THREAD

**Issue by stijnvanderlaan** [BowlerHatLLC/vscode-nextgenas#137]
It would be great if I could debug a swf from a local server like so:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "swf",
      "request": "launch",
      "name": "Launch Site",
      "program": "http://localhost:8080/index.html"
    }
  ]
}
```
When I do this now, I get the `Error launching SWF debug session.`

**Comment by joshtynjala** [comment]
You might try specifying the runtimeExecutable option in launch.json to point to your browser. Depending on your platform, the debugger may not be able to find your browser automatically.

https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Debug-a-SWF-embedded-in-HTML-with-Visual-Studio-Code#launch-in-a-specific-web-browser

**Comment by stijnvanderlaan** [comment]
This results in the same error (`Error launching SWF debug session`):
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "swf",
      "request": "launch",
      "name": "Launch Site",
      "program": "http://localhost:8080/index.html",
      "runtimeExecutable": "/Applications/Google Chrome.app"
    }
  ]
}
```
However this does work (with or without the runtimeExecutable):
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "swf",
      "request": "launch",
      "name": "Launch Site",
      "program": "index.html",
      "runtimeExecutable": "/Applications/Google Chrome.app"
    }
  ]
}
```

**Comment by joshtynjala** [comment]
Strange! I'll investigate.
