### ISSUE TITLE
Simple project, Failed to load project configuration options

### ISSUE THREAD

**Issue by SoepStengel** [BowlerHatLLC/vscode-nextgenas#142]
I have started a simple test project with two mxml files. My asconfig.json looks like this:

{
    "compilerOptions": {
        "targets": [
            "JSFlex"
        ]
    },
    "files": [
        "src/ProvincieRaceJs.mxml",
        "src/MainView.mxml"
    ]
}

When I open the project in Visual Studio Code with the latest nextgenas extension installed, I get a problem that says: Failed to load project confguration options. Error checking disabled, except for simple syntax problems. It points to the file ProvincieRaceJs.mxml witch looks like this:

<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:js="library://ns.apache.org/flexjs/express"
    xmlns:local="*">
    <js:initialView>
        <local:MainView/>
    </js:initialView>
</js:Application>

MainView.mxml is like this:

<?xml version="1.0" encoding="utf-8"?>
<js:View xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:js="library://ns.apache.org/flexjs/express">
    <js:TextButton text="Talk to Me!"/>
    <fx:Script>
        <![CDATA[
            
        ]]>
    </fx:Script>
</js:View>

My local settings.json for the extension:

{
    "nextgenas.sdk.framework": "c:\\Programmeren\\Flex\\sdks\\FlexJs0.8.0"
}

I cannot for the world figure out what is going wrong. The project compiles just fine when using the mxmlc compiler: mxmlc -targets=JSFlex src/ProvincieRaceJs.mxml

**Comment by joshtynjala** [comment]
Your application class should always be the final item in "files".

In fact, you don't actual need to list MainView.mxml in "files" at all because ProvincieRaceJs.mxml references it. The only time you might want to include more than one item in the array is if you're including extra classes that aren't referenced directly. Maybe things you only access using refection APIs.

**Comment by SoepStengel** [comment]
Ok, I removed the MainView.mxml from files, still same error. I restarted Visual Studio Code, but the same problem remains.

**Comment by SoepStengel** [comment]
Ok, sorry, I now found my mistake, the asconfig.json was in the .vscode folder. I moved it to the root and all is ok now. Sorry to bother you.

**Comment by joshtynjala** [comment]
I'm glad you figured it out! I've accidentally put things in the .vscode folder too. I think they don't indent the items far enough, and it can be hard to see that a file is in the wrong place!

> "c:\Programmeren\Flex\sdks\FlexJs0.8.0"

This may be correct in your real file, but make sure to escape each \ character:

    "c:\\Programmeren\\Flex\\sdks\\FlexJs0.8.0"
