### ISSUE TITLE
Add support for Apache Royale

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/vscode-nextgenas#144]

**Comment by carlosrovira** [comment]
+1

**Comment by pentapache** [comment]
VSCode looks like a terrific IDE for Apache Royale. Any help to get it going would be greatly appreciated.

**Comment by Harbs** [comment]
FYI, I pulled in the change and tried running it locally. I'm still getting "nextgenas.sdk.editor in settings does not point to a valid SDK. Requires Apache FlexJS 0.8.0 or newer".

As best as I can figure, the java process called in CheckFlexJSVersion is returning a status of 1 when checking my Royale SDK. Here's the args being passed in in case it helps:

````
[
  "-cp",
  "/FlexSDK/FlexJSNightly/lib/compiler.jar:/FlexSDK/FlexJSNightly/js/lib/jsc.jar:/Users/harbs/Documents/github/BowlerHatLCC/vscode-nextgenas/distribution/target/vscode-nextgenas/vscode-nextgenas/bin/check-flexjs-version.jar",
  "com.nextgenactionscript.vscode.CheckFlexJSVersion"
]
````
I'm not sure if my comment is helpful, but in case I have something to offer, I'd be happy to try any suggestions.

**Comment by joshtynjala** [comment]
The changes I have made related to Royale are purely superficial still. That's why this is not yet closed.

I have not yet migrated the language server to run code intelligence with the Royale compiler. You definitely can't use Royale with netgenas.sdk.editor until I do.

In theory, Royale should work as nextgenas.sdk.framework (if you comment out fxg-base-class in flex-config.xml because that option didn't exist in FlexJS 0.8), but when I did a quick test, I got a weird error. I still need to investigate that one.

**Comment by carlosrovira** [comment]
Hi Josh,

my experience is that trying to configure an Apache Royale SDK (0.9.0-SNAPSHOT), VSCode reports (in the right-lower corner) that the SDK used is "Apache Flex 0.9.0-SNAPSHOT". Then trying to run code intelligence does not do anything.

I think that if VSCode could recognize Royale the same way it does for FlexJS, I suppose always wil be running again

Thanks Josh

**Comment by joshtynjala** [comment]
> my experience is that trying to configure an Apache Royale SDK (0.9.0-SNAPSHOT), VSCode reports (in the right-lower corner) that the SDK used is "Apache Flex 0.9.0-SNAPSHOT"

My recent commit from a couple of days ago, c4aad31, will make it display Royale instead.

**Comment by Harbs** [comment]
I figured you were aware, but on the chance that not, I figured I'd mention what I found.

I doubt there's anything I can do to help you with this, but if there is, please let me know.

FYI, my local build of asconfigc has been working fine for me.

Thanks!

**Comment by carlosrovira** [comment]
Hi Josh,
wasn't aware of that, thanks Josh, could you release that as 0.7.2?
thanks!

**Comment by joshtynjala** [comment]
Since code intelligence isn't working for Royale yet, I'd prefer to wait before releasing anything related to Royale.

**Comment by joshtynjala** [comment]
I created a branch named **royale** where I've switched over to the Royale compiler for code intelligence. **I am not finished yet!** I know for sure that there are bugs because not all tests are currently passing.

If you want to live on the bleeding edge, you could build the **royale** branch yourself with Maven:

``` bash
mvn clean package
```

Then, you can install the extension manually from the following location:

 *distribution/target/vscode-nextgenas/vscode-nextgenas/vscode-nextgenas-0.8.0-SNAPSHOT.vsix*

**Comment by Harbs** [comment]
FWIW I tried the royale branch and it's not working for me yet. I guess I'll wait until more things are fixed... 😉

**Comment by joshtynjala** [comment]
All of my tests are passing on Windows, macOS, and Linux on the royale branch, and I've successfully created some sample projects. Everything should be good to go, as far as I can tell. Please let me know the details of error messages if you run into any further issues trying out the royale branch.

When are you guys planning to release the first official build of Royale? I'd prefer to wait on merging this branch back into master until there's official release of the compiler.

**Comment by Harbs** [comment]
Here's what I see when I open a project:
<img width="730" alt="keyboardeventconverter_as_ _royale-asjs" src="https://user-images.githubusercontent.com/395968/32565370-8b860be8-c4bf-11e7-92c0-fabf1b922d4a.png">
Here's what the extension reports with an ActionScript file open:
<img width="254" alt="keyboardeventconverter_as_ _royale-asjs" src="https://user-images.githubusercontent.com/395968/32565383-940d8d90-c4bf-11e7-9a4e-99050c769f3a.png">
I am using a patched FlexJS nightly with the Royale bits.

When I tried debugging the extension, the problem was in the function which checks the SDK for validity. The details are above https://github.com/BowlerHatLLC/vscode-nextgenas/issues/144#issuecomment-342421834.

What does CheckFlexJSVersion check? If you have a list of things it checks, I can try and figure out where things are going off...

**Comment by joshtynjala** [comment]
It appears that you're not using the royale branch.

> Here's what I see when I open a project:

If you were using the royale branch, you'd see "Requires Apache Royale 0.9.0 or newer." The error message that you see doesn't exist at all in the extension in the royale branch.

>  Here's what the extension reports with an ActionScript file open:

On the royale branch (or even the latest master branch), this should say "Royale 0.9.0"

>  I am using a patched FlexJS nightly with the Royale bits.

I tested with a pure build of Royale produced by `ant binary-release`, but as long you replaced all the compiler JAR files, your patched SDK may work.

> What does CheckFlexJSVersion check? If you have a list of things it checks, I can try and figure out where things are going off...

It's now CheckRoyaleVersion. It checks the version number of the compiler JAR file to be sure that it's 0.9.0 or newer.

**Comment by Harbs** [comment]
I am on the royale branch. I have this in extension.ts:
`const INVALID_SDK_ERROR = "nextgenas.sdk.editor in settings does not point to a valid SDK. Requires Apache Royale 0.9.0 or newer.";`

Maybe I need to clean something when I build the extension?

**Comment by Harbs** [comment]
I am on the royale branch. I have this in extension.ts:
`const INVALID_SDK_ERROR = "nextgenas.sdk.editor in settings does not point to a valid SDK. Requires Apache Royale 0.9.0 or newer.";`

Maybe I need to clean something when I build the extension?

**Comment by Harbs** [comment]
I am on the royale branch. I have this in extension.ts:
`const INVALID_SDK_ERROR = "nextgenas.sdk.editor in settings does not point to a valid SDK. Requires Apache Royale 0.9.0 or newer.";`

Maybe I need to clean something when I build the extension?

**Comment by Harbs** [comment]
I am on the royale branch. I have this in extension.ts:
`const INVALID_SDK_ERROR = "nextgenas.sdk.editor in settings does not point to a valid SDK. Requires Apache Royale 0.9.0 or newer.";`

Maybe I need to clean something when I build the extension?

**Comment by Harbs** [comment]
(Sorry about the multiple comments. My browser had a hiccup...) ;)

**Comment by Harbs** [comment]
I figured it out.

In ~/.vscode/extensions I had both `bowlerhatllc.vscode-nextgenas-0.8.0-SNAPSHOT` and `bowlerhatllc.vscode-nextgenas-0.7.1` The release version was steppin on the newer snapshot.

Removing the release version made it work. Looks good!!! ❤️

**Comment by Harbs** [comment]
FYI I just got the following error in VS Code. The file has complex CSS selectors and jquery (FWIW).

The project compiles correctly, but VS Code reports this error in the Problems tab.

````
file: 'file:///Users/harbs/Documents/git/PrintUI/printui-flexjs/PortedPrintUI/src/com/printui/view/components/palette/TabContainer.mxml'
severity: 'Error'
message: 'Internal error in ABC generator subsystem, when generating code for: /Users/harbs/Documents/git/PrintUI/printui-flexjs/PortedPrintUI/src/com/printui/view/components/palette/TabContainer.mxml: java.lang.NullPointerException
	at org.apache.royale.abc.instructionlist.InstructionList.addAll(InstructionList.java:420)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processMXMLStyle(MXMLClassDirectiveProcessor.java:4277)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processNode(MXMLClassDirectiveProcessor.java:987)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:861)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:831)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processMainClassDefinitionNode(MXMLClassDirectiveProcessor.java:653)
	at org.apache.royale.compiler.internal.as.codegen.GlobalDirectiveProcessor.declareMXMLDocument(GlobalDirectiveProcessor.java:518)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:232)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.traverse(DirectiveProcessor.java:188)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generate(ABCGenerator.java:122)
	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleABCBytesRequest(MXMLCompilationUnit.java:199)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processABCBytesRequest(CompilationUnitBase.java:875)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$300(CompilationUnitBase.java:108)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:312)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:308)
	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
'
at: '1,1'
source: ''
````

**Comment by joshtynjala** [comment]
@Harbs The language server has no code intelligence for CSS, and it looks like this error is being thrown when the compiler is parsing your styles. I'm fairly confident that this is a Royale compiler bug.

**Comment by Harbs** [comment]
The css is using namespace `@namespace "http://www.w3.org/1999/xhtml";`
Any other namespace causes a compiler error with the css in use, but the compiler is supposed to know that this is HTML CSS and is OK. Is it possible that the VS Code extension is parsing it as non-HTML CSS?

**Comment by joshtynjala** [comment]
The VSCode extension asks the compiler to parse everything.

This may be a clue:

> Internal error in ABC generator subsystem

As far as I can tell, when the compiler is acting as the code model for an IDE, it always generates bytecode for SWFs (this was intended to make building projects in IDEs faster). It could be that the bytecode generator doesn't know what to do with that namespace. I suspect that we may have found an extra place where the compiler needs to ignore this namespace, similar to however it does that elsewhere. I assume that it probably wasn't discovered before because the command line compiler bypasses the "ABC generator subsystem".

**Comment by Harbs** [comment]
Any suggestions on how I should file an intelligent issue? 😉

**Comment by joshtynjala** [comment]
I'm going to look into disabling the bytecode generator. If the command line compiler can bypass it to generate only JS, I feel like an IDE should be able to too.

**Comment by Harbs** [comment]
Cool.

I just added asconfigc files for all the Royale projects.

For the most part it works pretty well, but code intelligence in JS blocks is a bit hit or miss. I'm not sure what to make of it, and I'm getting on-and-off weird errors that start like this:
````
Nov 09, 2017 2:34:21 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///Users/harbs/Documents/ApacheRoyale/royale-asjs/frameworks/projects/Basic/src/main/royale/org/apache/royale/core/UIBase.as",
      "languageId": "nextgenas",
      "version": 1,
      "text": "////////////////////////////////////////////////////////////////////////////////\n//\n//  Licensed to the Apache Software ...........
````
I'm consistently getting these errors in the HTML project. Just opening Div.as causes an error.

**Comment by Harbs** [comment]
FWIW, my VS Code just updated itself to 1.18. I don't know if that's related...

**Comment by joshtynjala** [comment]
@Harbs Can you share the CSS from TabContainer.mxml? I tried reproducing by using then XHTML namespace and trying some things, but I couldn't get the "Internal error in ABC generator subsystem" error. If it's a lot of CSS, maybe you can simplify it to only the subset of lines that are required to cause the error.

**Comment by Harbs** [comment]
Sure.
````
    <fx:Style>
        @namespace "http://www.w3.org/1999/xhtml";
        .my_app .TabContainer .tabs {
            display: table;
            table-layout: fixed;
            width: 100%;
            transform: translateY(5px);
            padding-left:0px;
            background-color: #4d4d4d;
            margin-top:0px;
        }
        .tabs > li {
            transition-duration: .25s;
            display: table-cell;
            list-style: none;
            text-align: center;
            /* padding: 0px 20px 25px 20px; */
            position: relative;
            overflow: hidden;
            cursor: pointer;
            color: white; 
        }
        .tabs > li:before {
            z-index: -1;
            position: absolute;
            content: "";
            width: 100%;
            height: 120%;
            top: 0;
            left: 0;
            background-color: rgba(255, 255, 255, 0.3);
            -webkit-transform: translateY(100%);
            transform: translateY(100%);
            transition-duration: .25s;
            border-radius: 5px 5px 0 0;
        }
        .tabs > li:hover:before {
            -webkit-transform: translateY(70%);
            transform: translateY(70%);
        }
        .tabs > li.active {
            color:#000000;
            /* color: #50555a; */
        }
        .tabs > li.active:before {
            transition-duration: .25s;
            background-color: #f3f3f3;
            -webkit-transform: translateY(0);
            transform: translateY(0);
        }

        .tab__content {
            /* background-color: white; */
            position: relative;
            width: 100%;
            border-radius: 5px;
            padding-left: 0px;
        }
        .tab__content > li {
            width: 100%;
            position: absolute;
            top: 0;
            left: 0;
            display: none;
            list-style: none;
        }
        .tab__content > li .content__wrapper {
            /*text-align: left;*/
            border-radius: 5px;
            width: calc(100% - 10px);
            /* padding: 45px 40px 40px 40px; */
            padding-left: 10px;
            /* background-color: white; */
        }

    </fx:Style>
````

**Comment by joshtynjala** [comment]
@Harbs Perfect, thanks! I can reproduce the error now.

**Comment by joshtynjala** [comment]
> I'm getting on-and-off weird errors that start like this:

@Harbs I was able to reproduce these errors, and I fixed the issue. Grab the latest changes from the royale branch.

**Comment by Harbs** [comment]
Thanks. I'll give it a go!

**Comment by Harbs** [comment]
It looks like both errors are fixed. Great work! 😄
