### ISSUE TITLE
Stuck on Initializing ActionScript and MXML language server

### ISSUE THREAD

**Issue by breizhmanNB** [BowlerHatLLC/vscode-nextgenas#145]
Trying to play with that extension but somehow it can initialize the connection and can't use the auto completion and other features.

I tried to run as admin, disabling firewall, install uninstall etc..

Is there anything particular on the network side to be done.

[https://imgur.com/MSqwi4X](url)

**Comment by joshtynjala** [comment]
I'm going to release an update later this week that doesn't use sockets to communicate with the language server. Once I do, I think you should give it a try, and maybe it will fix your issue.

**Comment by breizhmanNB** [comment]
Any chances JAVA version or issue with JAVA installation can be the root cause?

**Comment by joshtynjala** [comment]
Java 1.8 is the minimum version of Java that's supported. If you only have an older version of Java, the extension should figure that out and display an error without trying to initialize the language server.

Until version 0.7.0 of the extension (which I just released last week), the new Java 9 was not working correctly. That should be fixed, though.

**Comment by breizhmanNB** [comment]
Ok many thanks.

thanks for your quick answers.

thanks for making that extension. Being a flex coders i want to see the potential of flexjs.

Next step i guess is to reboot my machine (never know :) )

**Comment by joshtynjala** [comment]
I just published version 0.7.1 with some improvements to how the extension initializes. Please give it a try and let me know if it works for you!

**Comment by breizhmanNB** [comment]
Thanks for the update.
It didn't change my issue but i think it is related to my machine/network i'm on.
Because i tried it home and on other machines and it works fine.
