### ISSUE TITLE
error debug

### ISSUE THREAD

**Issue by Simon-wu** [BowlerHatLLC/vscode-nextgenas#151]
java 8 jre   code 1.17   mac 10.12.6 (16G1036)
 i used     "nextgenas.java": "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"

i have install java 6 and java8

> Executing task: asconfigc --debug=true --flexHome /Applications/Adobe Flash Builder 4.7/sdks/4.6.0 <

Exception in thread "main" java.lang.NoClassDefFoundError: Flash
Caused by: java.lang.ClassNotFoundException: Flash
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
The terminal process terminated with exit code: 1

**Comment by Simon-wu** [comment]
reinstall jdk in mac  and set  log Error: Could not find or load main class Flash  msg

**Comment by joshtynjala** [comment]
I can reproduce this issue. It appears that something is different about the Adobe Flex 4.6 SDK compared to other SDKs.

Give it a try with the latest Apache Flex SDK instead.

**Comment by Simon-wu** [comment]
in my windows pc is ok ,and i try airsdk 27  it's same problem  on mac os 10.12.6  code 1.17.2

**Comment by joshtynjala** [comment]
I determined that it is not working on macOS if the SDK has spaces in its path.

**Comment by Simon-wu** [comment]
yes  i see the bug and i change the path  to
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java
but it's no work too

**Comment by joshtynjala** [comment]
I meant that the Flex SDK path can't have spaces.

**Comment by Simon-wu** [comment]
ok i have try thank very much

**Comment by Simon-wu** [comment]
Released in npm now？

**Comment by joshtynjala** [comment]
Not yet. I will try to release an update to asconfigc today.

**Comment by Simon-wu** [comment]
Thanks

**Comment by joshtynjala** [comment]
asconfigc has been updated on npm. Please update!

``` bash
npm install -g asconfigc
```
