### ISSUE TITLE
link folder support 

### ISSUE THREAD

**Issue by leefj** [BowlerHatLLC/vscode-nextgenas#153]
can vs code create a link folder ? and "vscode-nextgenas"  will support this feature ？it really useful, my project in FB have many linked folder,code in these folder are shared in several project.

**Comment by joshtynjala** [comment]
Is a link folder different from the source-path compiler option?

**Comment by leefj** [comment]
folder in source-path  can not list at vs code "resource manager". because I want open it and edit .as file in link folder just like normal folder in vs code.

**Comment by joshtynjala** [comment]
In the current version of the extension, files in the source-path will appear in the "ActionScript Source Path" view under your workspace's files. You can open linked classes from here. Unfortunately, there's no way to add more files to the regular file explorer yet.

In an upcoming Visual Studio Code update, "multi-root workspaces" will be supported. As I understand it, this feature will allow you to add folders that are outside of the current workspace to the file explorer. They should be releasing it soon, and then I plan to update the extension to add support for multiple roots.

**Comment by leefj** [comment]
ok, thanks,wait for your updates

**Comment by leefj** [comment]
hi josh,source-path config is good , but can you give an option to set folder alias.
![11111111](https://user-images.githubusercontent.com/12420137/32637480-fa8792e2-c5f4-11e7-9203-d48da9d5eb04.png)
