### ISSUE TITLE
Can't connect to debugger

### ISSUE THREAD

**Issue by ifrancis** [BowlerHatLLC/vscode-nextgenas#157]
Hi, I'm getting 'Process terminated without establishing connection to debugger.' when trying to debug an swf. When I launch the debugger, it opens the ADL process and I can see my project in a new window but there's no real time trace output. When I close the ADL window I get 'Process terminated without establishing connection to debugger.' followed by the project trace output all at once in the debug console.  Also the error message 'Error launching SWF debug session. Process exited with code: 0' appears. It makes no difference if I use the preLaunchTask to build the project first. I'm using the Apache Flex 4.16.0 SDK / AIR 27

**Comment by joshtynjala** [comment]
Getting all the trace output at once when you close the window is one I've never seen before...

Can you try to make a new, simple project that reproduces the same behavior and attach it here? I'll let you know if I can see the same on my computer, and we can go from there.

**Comment by ifrancis** [comment]
Ok, so I had a config setup error that was causing the issue. What I was seeing was the effect of trying to use the debugger with an swf compiled with as a release build (i.e. debug=false). So, it's correct that the debugger couldn't connect, but why could I see the trace output when I closed the window? This implies the swf is still outputting the debug info somehow, I thought that this code got stripped out at compile time if debug was set to false.  This behaviour happens on a fresh project setup as per the instructions in the wiki pages.

Anyway on a separate note, in the 'Problems' panel, I'm seeing issues picked up from files that are being excluded from my file explorer - is that correct behaviour?

Anyway, great work on the extension.

**Comment by joshtynjala** [comment]
> I thought that this code got stripped out at compile time if debug was set to false.

As far as I know, trace() calls do not get stripped out at compile time unless you use the omit-trace-statements compiler option (which isn't available for all SDKs).

> Anyway on a separate note, in the 'Problems' panel, I'm seeing issues picked up from files that are being excluded from my file explorer - is that correct behaviour?

I don't think there's a way for the language server to check if you've excluded something, so yes, that's the expected behavior.
