### ISSUE TITLE
Reinstall win 10 in an other ssd  use sdk  issue

### ISSUE THREAD

**Issue by Simon-wu** [BowlerHatLLC/vscode-nextgenas#158]
> Executing task: C:\Users\Wu\AppData\Roaming\npm\asconfigc.cmd --flexHome e:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK --debug=true <

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.common.base.internal.Finalizer (file:/E:/Program%20Files/Adobe/Adobe%20Flash%20Builder%204.7%20(64%20Bit)/eclipse/plugins/com.adobe.flash.compiler_4.7.0.349722/AIRSDK/lib/guava-r08.jar) to field java.lang.Thread.inheritableThreadLocals
WARNING: Please consider reporting this to the maintainers of com.google.common.base.internal.Finalizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
??????: e:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\frameworks\flex-config.xml

e:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\frameworks\flex-config.xml:47
??: ?????e:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\frameworks\libs\player\11.1\playerglobal.swc??
e:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\frameworks\flex-config.xml (line: 47)
        </external-library-path>

**Comment by joshtynjala** [comment]
Does compilation fail? I'm not sure what I'm looking at here in your output. I don't see any mentions of errors.

**Comment by Simon-wu** [comment]
thanks！Compilation done！ what mean about "All illegal access operations will be denied in a future release",  can update at new release at future

**Comment by joshtynjala** [comment]
This warning is from AIR SDK compiler when it's running on Java 9. Adobe needs to update one of its dependencies.
