### ISSUE TITLE
VS Code on Windows 7 - NextGen ActionScript extension exited with error code 1

### ISSUE THREAD

**Issue by bigosmallm** [BowlerHatLLC/vscode-nextgenas#16]
I am trying to set up the nextgenas extension for VS Code.  I must be doing something wrong because, I am getting this error:

![image](https://cloud.githubusercontent.com/assets/1650037/19991656/8146e344-a1f4-11e6-9a97-ef8ac3ffcd05.png)

I am not sure if there are any more detailed logs I can dig in.  If there are any, please let me know where I can find them.

**Comment by joshtynjala** [comment]
This is usually caused by multiple versions of Java installed on your computer. 0.1.0 picks the first Java installation it finds, and if that's not Java 8, it fails with an error and gives up. I've fixed that for 0.2.0, and it will continue to search for more versions of Java after a failure. 0.2.0 needs more time, so I'm thinking that I need to do a 0.1.1 release because, as you can probably guess, you aren't the first to have this issue.

**Comment by bigosmallm** [comment]
Sure, that would be great.  If there is a branch for 0.1.1, I can grab it and test it before you do an actual release.  If that would be helpful for you, that is.

**Comment by joshtynjala** [comment]
I emailed you a build, Om. No point in having you set up a dev environment for a quick test. Especially since I'm considering some changes to the build soon.

**Comment by bigosmallm** [comment]
Did you send an email?  I never hit anything.

**Comment by joshtynjala** [comment]
Yeah, I sent it to your Gmail, with the subject "vscode-nextgenas 0.1.1 build"

**Comment by bigosmallm** [comment]
Okay, I saw it in the spam folder.  

I uninstalled the existing one and installed it with the .vsix file you sent me.  I am still getting the same error.  Now, in addition to that I am seeing these in the OUTPUT window:

[Error - 2:23:43 PM] Connection to server is erroring. Shutting down server.
[Error - 2:23:43 PM] Connection to server is erroring. Shutting down server.
[Error - 2:23:43 PM] Connection to server is erroring. Shutting down server.
[Error - 2:23:43 PM] Connection to server is erroring. Shutting down server.
[Error - 2:23:43 PM] Connection to server is erroring. Shutting down server.
[Error - 2:23:43 PM] Connection to server is erroring. Shutting down server.

**Comment by joshtynjala** [comment]
Can you press Ctrl+Shift+P and run the **Developer: Toggle Developer Tools** command? Can you tell me what's in the console?

**Comment by bigosmallm** [comment]
I see multiple such errors in the console:

`extensionHost.ts:255[Extension Host] TypeError: Cannot read property 'dispose' of null
    at LanguageClient.cleanUp (C:\Users\omuppirala\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.1.1\node_modules\vscode-languageclient\lib\main.js:631:30)
    at LanguageClient.stop (C:\Users\omuppirala\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.1.1\node_modules\vscode-languageclient\lib\main.js:605:14)
    at LanguageClient.handleConnectionError (C:\Users\omuppirala\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.1.1\node_modules\vscode-languageclient\lib\main.js:866:18)
    at errorHandler (C:\Users\omuppirala\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.1.1\node_modules\vscode-languageclient\lib\main.js:728:19)
    at C:\Users\omuppirala\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.1.1\node_modules\vscode-languageclient\lib\main.js:47:42
    at CallbackList.invoke (C:\Users\omuppirala\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.1.1\node_modules\vscode-jsonrpc\lib\events.js:103:39)
    at Emitter.fire (C:\Users\omuppirala\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.1.1\node_modules\vscode-jsonrpc\lib\events.js:167:36)
    at readErrorHandler (C:\Users\omuppirala\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.1.1\node_modules\vscode-jsonrpc\lib\main.js:110:22)
    at CallbackList.invoke (C:\Users\omuppirala\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.1.1\node_modules\vscode-jsonrpc\lib\events.js:103:39)
    at Emitter.fire (C:\Users\omuppirala\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.1.1\node_modules\vscode-jsonrpc\lib\events.js:167:36)`

**Comment by joshtynjala** [comment]
Are you running VSCode 1.7.1?

Did you restart VSCode after installing the extension?

**Comment by bigosmallm** [comment]
![image](https://cloud.githubusercontent.com/assets/1650037/20023459/4961b91e-a29d-11e6-91e5-cd17fc10076f.png)

**Comment by bigosmallm** [comment]
Yes, I did restart after installing the extension

**Comment by joshtynjala** [comment]
Please try the new build that I emailed to you!

**Comment by joshtynjala** [comment]
Thanks for the patience on this one, Om. Can you please try installing the new version 0.3.0 of the extension in VSCode? Let me know if the error code has changed when it crashes (it might be something other than 1 now). Also, please share any errors that appear in the developer tools. Thank you!

**Comment by bigosmallm** [comment]
Thanks for ping back!

I am just setting up my new Windows 10 PC.  This was one of the first
things I was going to test :-)
If you still want me to test on Windows 7, please let me know.

Thanks,
Om

**Comment by joshtynjala** [comment]
Hey, Om. If everything works fine on Windows 10, I'd like you to double-check on your Windows 7 machine, just to be sure. Thanks!

**Comment by bigosmallm** [comment]
Tested the new version on Windows 7.  Much better!  I dont see any errors
in the console and things seem to be working.  I need to play around with
it more to build and compile an app.

But things are looking much better already.

Thanks,
Om

**Comment by joshtynjala** [comment]
Good news!
