### ISSUE TITLE
Additional folder  to package with the Adobe AIR application failed

### ISSUE THREAD

**Issue by TerranTian** [BowlerHatLLC/vscode-nextgenas#160]
Here is what the document says, but it doesn't work with directory.
>Additional files to package with the Adobe AIR application. Each entry in this array must be an object with two fields, file and path. The file field refers to the source path of a file (or directory) to include in the application package. The path field refers to the path to the destination directory of the file inside the application package.

The error is:

> password:
File does not exist: bin/assets
usage:
  adt -checkstore SIGNING_OPTIONS

I can put these folders in application successfully using the shell below:
`adt -package\
 	-storetype pkcs12 -storepass 123456 -keystore keys/sign.p12\
 	-tsa none\
 	re.air bin/ResTool-app.xml -C bin main.swf\
	-C bin assets\
	-C bin icons`

Below is the my project screenshot:
![image](https://user-images.githubusercontent.com/2083024/34767913-4f5599b2-f634-11e7-8522-91e8f8b63c85.png)

**Comment by joshtynjala** [comment]
Yeah, it turns out that Adobe's documentation about the -e option is incorrect. It says that folders are allowed, but they're not. I have a fix working locally, and I'll update asconfigc soon!

**Comment by joshtynjala** [comment]
Please update asconfigc to v0.6.3 or newer.

``` bash
npm install -g asconfigc
```
