### ISSUE TITLE
Scaleform and Go To Flash Symbol

### ISSUE THREAD

**Issue by gw1108** [BowlerHatLLC/vscode-nextgenas#161]
I'm a new at flash and I was wondering if it's possible to use the debugger on scaleform swf files? I'm working on a C++ game that uses scaleform on PC and PS4.

Also, is it possible to go to definition of classes like flash.display.MovieClip? I can do it on FlashDevelop. Do I have to setup something?

**Comment by joshtynjala** [comment]
@gw1108 

1) Can you debug Scaleform SWF files in other IDEs, like Flash Builder or FlashDevelop? I've never used Scaleform. However, if it works in those other IDEs, then it should work in VSCode too. We'd just need to figure out how the debugger is configured in the other IDEs.

2) Goto Definition does not currently summarize the contents of compiled SWC files, so you won't be able to use it to see the methods and properties on classes like flash.display.MovieClip. It's something that can be added, though. In fact, I created issue #2 for this exact feature a while back.

**Comment by gw1108** [comment]
1. I've never got FlashDevelop to debug Scaleform SWF files. I was hoping it'd be possible, but I don't think it is.
2. Yes this feature would be great. I have an SWC file that I want VSCode to jump to but I didn't know how.

**Comment by joshtynjala** [comment]
I looked into #2 today, and I figured out a good way to implement it. I'll try to add this feature soon. Probably in v0.10.
