### ISSUE TITLE
Royale .9 debugging issue

### ISSUE THREAD

**Issue by JTtheGeek** [BowlerHatLLC/vscode-nextgenas#162]
at HoelloRoayle.js goog is undefined exception upon launching the debug player

/**
 * Generated by Apache Royale Compiler from HelloRoyale.mxml
 * HelloRoyale
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('HelloRoyale');

possibly related actionscript source path panel says "no source paths"

**Comment by joshtynjala** [comment]
> possibly related actionscript source path panel says "no source paths"

That's normal. It just means that your project does not have any extra source folders added with the source-path compiler option.

**Comment by joshtynjala** [comment]
Are you using a custom HTML template?

**Comment by JTtheGeek** [comment]
negative, attempted to just follow the intro to royale with vscode at

https://github.com/apache/royale-asjs/wiki/Visual-Studio-Code

and hit this issue

fresh install of vscode, node, asconfigc, etc, etc,

**Comment by joshtynjala** [comment]
I don't see anything that seems incorrect about those instructions. They don't really go into much detail about debugging, so maybe something in your launch.json needs a tweak.

Check out these two pages with my official instructions, and see if anything might look out of place in your project.

https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Apache-Royale
https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Debug-a-transpiled-ActionScript-project-in-Visual-Studio-Code-with-Google-Chrome

You might also try deleting the bin directory and compiling fresh to see if that makes a difference.

**Comment by JTtheGeek** [comment]
swapped my launch.json over to

{
"version": "0.2.0",
"configurations": [
{
"name": "Launch Chrome, debug build with sourcemaps",
"type": "chrome",
"request": "launch",
"file": "${workspaceRoot}/bin/js-debug/index.html",
"sourceMaps": true
}
]
}


and installed the chrome debug extension and it worked.   I think the
guides might want to mention that as that extension wasn't installed by
default

**Comment by joshtynjala** [comment]
I'm glad you figured it out! Feel free to let the Apache Royale folks know that their guide could use those details!
