### ISSUE TITLE
Necessary steps for each new opened Royale app (folder) to run it

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#163]
Is it true that for each opened Royale app, that doesn't have VSCode related files, one must create:
- asconfig.json
- launch.json
- tasks.json

with their proper contents, to have option to start debugging app with one click on _green arrow in Debug panel_ (or F5) ?

If not, what is most quick way to open Royale app folder and run it?
If yes, how can this be automated? What is preferred?

**Comment by joshtynjala** [comment]
You must always create *asconfig.json*, but you could potentially get started without the other two files.

You can build without creating *tasks.json* with Ctrl+Shift+B. Or go to the Tasks menu and select Run Build Task. You'll need to choose an option from the list, but it can all be done with arrow keys and enter, so you won't leave the keyboard.

If you press the green arrow when *launch.json* doesn't exist, it should create one for you automatically.

Unfortunately, there's no way to automatically build when you start the debugger without creating both *tasks.json* and *launch.json* with the appropriate options specified.
