### ISSUE TITLE
Failed to copySourcePathAssetToOutputDirectory if subDirectory not exists

### ISSUE THREAD

**Issue by civet** [BowlerHatLLC/vscode-nextgenas#165]
why not create directories automatically?

**Comment by joshtynjala** [comment]
Fixed in 47dbf5b already. There will be an update soon.

In the meantime, you can temporarily disable the bundled version of asconfigc in the VSCode settings by changing `nextgenas.asconfigc.useBundled` to `false`. Then, install the npm version of asconfigc, which does not have this issue.
