### ISSUE TITLE
How can I copy additional resources to bin/js-debug/resources?

### ISSUE THREAD

**Issue by piotrzarzycki21** [BowlerHatLLC/vscode-nextgenas#168]
I'm preparing configuration to run some Royale examples using VSCode. I have problem with one example and cannot find appropriate options in [asconfig](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/asconfig.json) documentation.

I have resource folder with some additional css file:
resources/additional.css - it should be copied to bin/js-debug/resources/additional.css. 

How can I do this ?

**Comment by joshtynjala** [comment]
In *asconfig.json* set [`copySourcePathAssets`](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/asconfig.json#copysourcepathassets) to `true`.

You can either move *resources* inside your *src* folder, or you can create a new parent folder for *resources* and add the parent folder to the `source-path` compiler option.

**Comment by piotrzarzycki21** [comment]
I did used copySourcePathAssets and it didn't copied this particular file. "resources" are inside src folder.
I have following structure:
src/resources/images
src/resources/additional.css

Everything in images is being copied, but file additional.css not.

**Comment by piotrzarzycki21** [comment]
I just did try to add to source-path - src/resources, but it didn't work either. The example which I'm talking about is [here](https://github.com/piotrzarzycki21/TranspiledActionScript/tree/examples/Examples/TranspiledActionScriptWebsite).

It's configured with VSCode so you should not have problem with checking. I can also prepare some smaller example.

**Comment by joshtynjala** [comment]
Be sure that you're using vscode-nextgenas v0.9.1. I released an update today that fixes an issue with copySourcePathAssets.

**Comment by piotrzarzycki21** [comment]
I lately changed my SSD and installed everything from scratch.  VSCode was installed one hour ago along with your 0.9.1 update. I have everything fresh. 

![image](https://user-images.githubusercontent.com/24554795/35999032-c05f78f2-0d1e-11e8-9008-f48a6a419f36.png)

**Comment by joshtynjala** [comment]
When you build your project, do you see the following message in your terminal at the end?

> The terminal process terminated with exit code: 2

That's what I see. It appears that the Royale compiler is exiting as if it had found errors. Strangely, it only seems to have found warnings. I guess it's a bug in the Royale compiler.

When I remove the bindings that cause the warnings, I can see additional.css in bin-debug/resources.

**Comment by piotrzarzycki21** [comment]
Yes I see it! I will remove binding warning and think how actually report that. Maybe I will create small examples and try to reproduce it. Thank you for the help!
