### ISSUE TITLE
Support js-output-optimization and remove-circulars in compilerOptions

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-nextgenas#17]
Hi Josh,

I'm really liking your extesion.

I'm not sure if I'm doing something wrong, but I tried adding the following items to compilerOptions in the asconfig.json file:
        "js-output-optimization": "skipAsCoercions",
        "remove-circulars": true,

I get "unknown compiler option" for both of those.

**Comment by joshtynjala** [comment]
I'll get these added in a future version. When I release 0.1.1, you'll be able to add them to the new additionalOptions field in asconfig.json.

**Comment by Harbs** [comment]
additionalOptions should be fine. Looking forward.

**Comment by joshtynjala** [comment]
I just released version 0.1.1 of the extension. It now supports the additionalOptions field.

**Comment by joshtynjala** [comment]
Moved to BowlerHatLLC/asconfigc#7 and BowlerHatLLC/asconfigc#8
