### ISSUE TITLE
How can I set the theme for the compiler?

### ISSUE THREAD

**Issue by vrokolos** [BowlerHatLLC/vscode-nextgenas#171]
I get hundreds of errors like this:

The style 'backgroundColor' is only supported by type 'VBox' with the theme(s) 'halo,spark'.

This error only appears on the editor. The build works fine. I saw on your sourcecode that you disable themes when on editor. Perhaps this is the cause?

https://github.com/BowlerHatLLC/vscode-nextgenas/blob/af2fad91632f54c6f0aa643f5e33f27882c462a5/language-server/src/main/java/com/nextgenactionscript/vscode/ActionScriptTextDocumentService.java#L4818

**Comment by joshtynjala** [comment]
Just to be sure that I fully understand the situation, are you using a custom theme? Or are you seeing these errors even when you use the default Flex theme?

**Comment by vrokolos** [comment]
Not sure in this exact spot since I'm only doing a form out of a huge project. I believe it's the default Flex theme.
`      <theme>
         <filename>themes/Spark/spark.css</filename>
      </theme>`

**Comment by joshtynjala** [comment]
Is that XML from a custom config file that you include with the -load-config compiler option?

**Comment by vrokolos** [comment]
It's the output xml from --dump-config from Flex Builder

**Comment by joshtynjala** [comment]
Understood. Yes, that's probably the default theme from the SDK. Thanks! I'll take a look.

**Comment by joshtynjala** [comment]
Attaching some code that reproduces this issue.

``` mxml
<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
	xmlns:s="library://ns.adobe.com/flex/spark"
	xmlns:mx="library://ns.adobe.com/flex/mx">
	<mx:VBox backgroundColor="0xff00ff"/>
</s:Application>
```
