### ISSUE TITLE
Can I replace sdk path with some variable like ${flexlib} in asconfig.json so I can share it with other people?

### ISSUE THREAD

**Issue by vrokolos** [BowlerHatLLC/vscode-nextgenas#173]
"external-library-path": [
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\player\\17.0\\playerglobal.swc",
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\framework.swc",
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\textLayout.swc",
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\spark.swc",
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\sparkskins.swc",
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\rpc.swc",
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\charts.swc",
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\spark_dmv.swc",
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\osmf.swc",
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\mx\\mx.swc",
            "C:\\FlexSDK_4.14.1\\frameworks\\libs\\advancedgrids.swc"
        ]

I need: 
`        "external-library-path": [            
                "${flexlib}\\libs\\advancedgrids.swc"
        ]`

**Comment by joshtynjala** [comment]
These libraries from the SDK should be automatically added to the external-library-path. You should not need to add them manually. Is there any particular reason why?

**Comment by vrokolos** [comment]
File size of output all those mentioned in json: 507kb.
File size of output without those mentioned in json: 2.8mb.

So I need to reference them there

**Comment by joshtynjala** [comment]
I'm afraid that I still don't understand.

**Comment by vrokolos** [comment]
By telling the compiler to externally link those libraries it won't add them to the output file when compiling.
So the resulting swf doesn't include all those since they will be linked externally at runtime.

If I don't add them to the json file the output file gets enormous since it includes all those framework swcs

**Comment by joshtynjala** [comment]
Okay, thanks. I understand now! I didn't realize that you load them at runtime.

Anyway, there is currently no way to use a token to replace the SDK path. I'll consider it for a future update, but you'll need to use the full path for now.
