### ISSUE TITLE
Error: The actionscript task detection didn't contribute a task for the following configuration:

### ISSUE THREAD

**Issue by 22Round** [BowlerHatLLC/vscode-nextgenas#174]
can't figure out what I am missing?
I have followed wiki tutorial

<img width="1399" alt="screen shot 2018-02-22 at 18 59 22" src="https://user-images.githubusercontent.com/5682469/36545523-8841918c-1802-11e8-86b7-19dac2c04db9.png">

**Comment by joshtynjala** [comment]
*asconfig.json* should be in the root folder of your project. You accidentally placed it in the *.vscode/* folder.

**Comment by 22Round** [comment]
@joshtynjala thanks, my stupid mistake

**Comment by nadako** [comment]
Hm, two years later I'm getting this as well: 
![image](https://user-images.githubusercontent.com/49749/80028846-1b161d00-84e6-11ea-9029-df96e459bfa0.png)

**Comment by joshtynjala** [comment]
@nadako I suspect that the AS3 & MXML extension has not activated yet. Try opening one your .as/.mxml files, which should trigger the extension activation, and then try to build again. If that doesn't work, try reloading the workspace.

**Comment by nadako** [comment]
I had the same idea and I did open a file, but that didn't help. I'll try to debug some more next time I'll have to touch AS3 code :)
