### ISSUE TITLE
compile error with "inline"

### ISSUE THREAD

**Issue by leefj** [BowlerHatLLC/vscode-nextgenas#175]
hi, I use "inline" ,but it report error 

![xxx](https://user-images.githubusercontent.com/12420137/36585237-03acdd08-18b8-11e8-8235-e44bb81dd567.jpg)

**Comment by leefj** [comment]
project is here 
https://github.com/leefj/fast-md5

**Comment by joshtynjala** [comment]
Maybe I'm wrong, but I thought that you needed to make functions inline by using metadata: `[Inline]`. I don't think I've ever seen an `inline` keyword used in ActionScript.

**Comment by leefj** [comment]
sorry , it is my fault. this on cracked FlexSDK 4.5; 
so I just submit the result only.
