### ISSUE TITLE
Huge performance differences WRT tasks.json

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-nextgenas#178]
I have been using a `tasks.json` file in VS Code to compile my app and it looks like this:
````
{
	"version": "0.1.0",
	"command": "asconfigc",
	"isShellCommand": true,
	"args": [
		"--sdk=/Apache/royale-asjs"
	],
	"showOutput": "always"
}
````
When I compile with `"debug": false` in my asconfig.json, I'm getting about a 36 second compile time in my app (about 10 seconds with `"debug": true`).

When I remove the `tasks.json` file and let VS Code compile using the internal version of asconfigc, I'm getting about 80 second compile times for release. This is using the exact same `asconfig.json` file. It's interesting to note that the build times when running an ant script is similar to the build times when I don't have a tasks.json file defined. This makes me wonder if running the compiler from Java somehow slows down builds.

**Comment by joshtynjala** [comment]
It's certainly possible that starting up two instances of the JVM is slower. You could set nextgenas.asconfigc.useBundled to false, and it will use the Node version instead. This will probably perform similarly to your tasks.json.

If VSCode ever adds the ability to run a "command" as a task, I'll be able to run asconfigc from the already running language server. It won't require starting any new runtimes, so it should be super fast.

**Comment by joshtynjala** [comment]
I'm also looking into using fcsh, which will keep the compiler in memory for incremental builds. Someone wrote a version for Adobe's ASC 2.0, and I may be able to modify it for Royale. That should ultimately end up being the fastest option.

**Comment by Harbs** [comment]
Your suggestion of setting `nextgenas.asconfigc.useBundled` did in fact result in similar build times. Thanks for the tip.

The other two optimizations sound enticing... 😉 

Thanks for the great work! 😄

**Comment by Harbs** [comment]
FWIW, I'm probably going to leave the tasks.json file intact because the "Output" output is *sooo* much nicer than the Terminal output. It's also more complete.

**Comment by joshtynjala** [comment]
I suspect that they may remove the older 0.1.0 format of tasks.json in the future, so you may need to move to the 2.0 format that uses the terminal eventually. However, if that's what you prefer, go for it!

When you say that it's more complete, I'm not sure what you mean. As I understood it, the output should be exactly the same. What is missing that I didn't realize?

**Comment by Harbs** [comment]
The output is truncated.

I get only 712 lines of output in the Terminal (for debug) instead of the full 5100 lines I get in Output.

**Comment by joshtynjala** [comment]
Interesting! Thanks for letting me know about it. I'm going to release v0.10 later this week. In this update, I made some changes to how the output from the compiler is handled (in a way, I'm following "best practices" a little better), so hopefully, that will fix your issue. If not, I'll make sure to look into it soon!

**Comment by Harbs** [comment]
Also, the output in "Output" is color coded and has proper file links, while the output in Terminal is plain text with no links. (Not sure if it's related to above.)

**Comment by joshtynjala** [comment]
@Harbs I just discovered that you can customize the `terminal.integrated.scrollback` setting in VSCode to keep a longer terminal history.
