### ISSUE TITLE
Two equal problems listed if there is non closed tag.

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#180]
Reproduce code:
```
<?xml version="1.0" encoding="utf-8"?>
<js:View xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:js="library://ns.apache.org/royale/basic">
    
    <js:Image>

</js:View>
```

Problems:

> 'js:Image' tag (or tag before this tag, or non-tag inside this tag) is unclosed or tag not allowed here.
> 'js:Image' tag (or tag before this tag, or non-tag inside this tag) is unclosed or tag not allowed here.
> 

![image](https://user-images.githubusercontent.com/1468887/36803107-f7f2c1be-1cb6-11e8-8cc3-123a8fdf442a.png)

**Comment by joshtynjala** [comment]
It's very likely that the compiler is actually creating two separate problems, for some reason. I simply display what the compiler gives me. If that's the case, then it's an apache/royale-compiler issue. I'll investigate to see what I can find.

**Comment by joshtynjala** [comment]
I have confirmed that [apache/royale-compiler](https://github.com/apache/royale-compiler) produces two errors.
