### ISSUE TITLE
Mouse over closing tag should show tooltip even if there is problem within the tag

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#181]
Mouse over closing tag should show tooltip even if there is problem within the tag, same as it shows tooltip when mouse over opening tag. Reproduce code is same as in https://github.com/BowlerHatLLC/vscode-nextgenas/issues/180 if you mouse over `</js:View>` there is no tooltip.

**Comment by joshtynjala** [comment]
Copying code from #180 so that I don't need to reference multiple issues:

``` mxml
<?xml version="1.0" encoding="utf-8"?>
<js:View xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:js="library://ns.apache.org/royale/basic">
    
    <js:Image>

</js:View>
```

**Comment by joshtynjala** [comment]
This is possibly a bug in the compiler, but I think I can find a workaround.

*Notes to self:*

In MXMLDataUtils.getDefinitionForMXMLTag(), if getXMLName() doesn't have a proper URI for the MXML namespace, the following code may be useful for finding the URI manually.

``` java
IMXMLData parent = tag.getParent();
if (parent != null)
{
    IMXMLTagData rootTag = parent.getRootTag();
    if (rootTag != null)
    {
        PrefixMap prefixMap = rootTag.getPrefixMap();
        if (prefixMap.containsPrefix(tag.getPrefix()))
        {

        }
    }
}
```
