### ISSUE TITLE
Feature request: Export build script

### ISSUE THREAD

**Issue by bigosmallm** [BowlerHatLLC/vscode-nextgenas#188]
The nextgenas tool makes it very simple for creating new projects, add dependencies etc.  When I am trying to share a project, I would like to make it buildable using command line tools, with only mxmlc/asjsc as dependencies.  

Is it possible to export a simple command with all the correct params and dependencies as a .sh file? That would be extremely useful.

**Comment by joshtynjala** [comment]
There is currently no way to export any kind of command. However, you can install [asconfigc](https://www.npmjs.com/package/asconfigc) to build the project from the command line using the same asconfig.json file used by VSCode.

**Comment by bigosmallm** [comment]
Ah, that's nifty.  I will give that a spin.  Thanks for the quick response!
