### ISSUE TITLE
Can't load ANEs on mobile project

### ISSUE THREAD

**Issue by embpdaniel** [BowlerHatLLC/vscode-nextgenas#189]
Hi, brand new to the extension in vscode and migrating from IntelliJ. I think I might not be understanding how to get my ANEs to be found by my debug build. What I am trying to do is run the (Launch SWF) debug task to debug my mobile application in the IOS simulator. My anes are in a "anes" folder in my project's root folder, which also contains my `.code-workspace` file. Here's what I have so far:

_launch.json_
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch SWF",
            "preLaunchTask": "build-debug",
            "profile": "mobileDevice",
	          "screensize": "iPhone6Plus",
	          "screenDPI": 401,
            "versionPlatform": "IOS",
            "extdir": "${workspaceRoot}/anes"
        },
        {
            "type": "swf",
            "request": "attach",
            "name": "Attach SWF"
        }
    ]
}
```

_tasks.json_
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "identifier": "build-debug",
            "type": "actionscript",
            "debug": true,
            "problemMatcher": [
                "$nextgenas_nomatch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

_asconfig.json_ (all paths relative to root folder)
```
{
  "config": "airmobile",
  "compilerOptions": {
      "output": "out/app.swf",
      "library-path": [
        "libs",
        "anes"
      ]
  },
  "application": "src/Sports App-app.xml",
  "files":
  [
      "src/Main.as"
  ],
  "airOptions": {

    "android": {
      "extdir": [
        "./anes"
      ],
      "output": "out/Main.apk",
      "signingOptions": {
        "storetype": "pkcs12",
        "keystore": "android_certificate.p12"
      }
    },
    "ios": {
      "extdir": [
        "./anes"
      ],
      "output": "out/Main.ipa",
      "signingOptions": {
        "storetype": "pkcs12",
        "keystore": "ios_certificate.p12",
        "providerName": "path/to/file.mobileprovision"
      }
    }
  }
}
```
With these configurations in place, I hit play on the Launch SWF debug config, and I get the following error:
```
Process terminated without establishing connection to debugger.
The content cannot be loaded because there was a problem loading an extension: Error: Requested extension com.milkmangames.extensions.GoViral could not be found.
```

I have confirmed the `com.milkmangames.extensions.GoViral.ane` file is inside the `anes` folder. Here is a screenshot of my folder structure:

![screen-shot-2018-03-20-at-10 28 38-pm](https://user-images.githubusercontent.com/5573046/37692425-d585627a-2c8e-11e8-82ed-ee4464d3efff.jpg)

Am I doing something wrong?

**Comment by joshtynjala** [comment]
In launch.json, extdir should point to "unpackaged" ANEs, as I understand it. It looks like your ANEs are files rather than unpackaged directories. See the ADL documentation for details:

https://help.adobe.com/en_US/air/build/WSfffb011ac560372f-6fa6d7e0128cca93d31-8000.html

**Comment by embpdaniel** [comment]
Thanks @joshtynjala I think that worked. I have other errors which I am wondering about, but I think the ANEs were found :)

**Comment by m-a-v** [comment]
I am also a newbie and have the same problem. Is it wrong if I just rename the files from ane to zip und unzip them? Or must they have a special naming convention. I have the ane directory listed in asconfig.json and launch.json. What else could be wrong? The project compiles without any problems in Flash Builder 4.7.

"Type was not found or was not a compile-time constant"

**Comment by joshtynjala** [comment]
I don't have experience with ANEs, but this is how they work, as I understand it.

The compile the SWF and for code intelligence, you should add your original, **unextracted** *.ane* files to the `library-path` field in the `compilerOptions` section of *asconfig.json*. The way that I understand it, they are treated like *.swc* files.

For packaging your AIR app, you should add the folder containing your original **unextracted** *.ane* files in the `extdir` field in the `airOptions` section of *asconfig.json*.

For debugging, you **must extract** the *.ane* files. As I understand it, a special naming convention is required. I think the new folder needs to have the same name as the original file (including the *.ane* file extension!). You add the parent folder of all of the unextracted ANEs to the `extdir`field of *launch.json*.

If anyone sees that I got anything wrong, please let me know.

**Comment by m-a-v** [comment]
I made a simple AS3 project (as you describe in the wiki) and then I tried to integrate a simple native call using an ANE, but it still doesn't compile: The definition could not be found. Should it generally be possible to support ANEs with the VS Code extension? Have you already tried it? I didn't find any sample in the web. Do you have one or do you have any further hints?

**Comment by joshtynjala** [comment]
It should definitely be possible because all of the configuration options are exposed for you to use. I have not tried using ANEs myself, but it sounds like embpdaniel was able to get it to work, and others have reported success too.

Your error makes it pretty clear that compiling the SWF is where you have something misconfigured. I guess this means that you need to adjust the library-path compiler option so that the compiler can find your ANEs (the original files, not the ones you unzipped... those are only for debugging, as I understand it).

**Comment by embpdaniel** [comment]
@m-a-v I emailed you some info. I haven't touched this project in a bit, but I was able to get the unzipped ANEs to be found if I recall.

To get it working I unzipped my ANEs and placed them in a `anes-debug` folder in my project. I kept the same name of the ANE, including the extension, as part of the folder name. Here's a screenshot:

<img width="382" alt="screen shot 2018-05-30 at 9 35 17 am" src="https://user-images.githubusercontent.com/5573046/40723444-f1cb922a-63ec-11e8-9e8d-54d9ba9369a7.png">

As part of my debug config I added an "extdir" value, which points to my `anes-debug` folder. Here is the entire debug config:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch SWF",
            "preLaunchTask": "build-debug",
            "profile": "mobileDevice",
	    "screensize": "iPhone6Plus",
	    "screenDPI": 401,
            "versionPlatform": "IOS",
            "extdir": "${workspaceRoot}/anes-debug"
        },
        {
            "type": "swf",
            "request": "attach",
            "name": "Attach SWF"
        }
    ]
}
```
I believe that was all I did to get it to find the ANEs. I did have some other problems with some ANEs but I think it may have been unrelated to this, and I had to abandon this for now because I could not fix those issues. Hope this helps in some way though.

**Comment by m-a-v** [comment]
Finally, I was able to compile the sample project. I also had to add the corresponding SWC file. Is this really needed?

See also the following comments:
https://stackoverflow.com/questions/25934196/why-do-i-need-a-swc-file-when-compiling-against-an-adobe-native-extension

**Comment by joshtynjala** [comment]
@m-a-v Where did you add the SWC file?

**Comment by m-a-v** [comment]
I added it to a libs folder and in asconfig.json into the compilerOptions/libary-path section.

    "compilerOptions": {
      "output": "bin/Main.swf",
      "library-path":[
        "libs",
        "ane"
      ]

**Comment by joshtynjala** [comment]
@m-a-v And the *ane* folder contains your *.ane* files? (Not the folders that you extracted to for debugging, but the original real *.ane* files)

**Comment by m-a-v** [comment]
Yes, the original .ane files are there. Is this wrong?

**Comment by joshtynjala** [comment]
The way that I understand it, the original *.ane* files should be treated like *.swc* files by the compiler. Maybe I'm wrong, though, and Adobe expects IDEs to manually extract *.ane* files to get at the *.swc* that's supposed to be in *META-INF/ANE/default*.

**Comment by taratoga** [comment]
Have red this all. Wondering why now the extdir parameter gives "Property extdir is not allowed" .
has a green wavy line under extdir.
If I compile then I have this:
> Executing task: C:\ProgramData\Oracle\Java\javapath\java.exe -jar c:\Users\Cheffes Workstation2\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.15.0\bin\asconfigc.jar --sdk d:\feathersSDK --debug=false --project d:\feathersProjekte\McMakinMockUp\asconfig.json --air android <

Konfigurationsdatei D:\feathersSDK\frameworks\airmobile-config.xml wird geladen
D:\feathersProjekte\McMakinMockUp\src\work\Main.as(36): Spalte: 28 Fehler: Definition de.biobedded.ane:BLEAir wurde nicht gefunden.

    import de.biobedded.ane.BLEAir;
                           ^

asconfig.json:

{
	"config": "airmobile",
	"compilerOptions": {
		"output": "bin/Main.swf",
		"source-path": [
			"src"
		],
		"library-path": [
			"libs",
			"anes"
		]
	},
	"application": "src/work/Main-app.xml",
	"files":
	[
		"src/work/Main.as"
	],
	"airOptions":{
		"android": {
			"extdir": [
				"./anes"
			  ],
			"output": "dist/Main.apk",
			"signingOptions":{
				"storetype": "pkcs12",
				"keystore": "cert/test.p12"
			},
			"files": [
				{
					"file": "icons/android/icons/icon_48.png",
					"path": "./icon_48.png"
				},
				{
					"file": "icons/android/icons/icon_120.png",
					"path": "./icon_120.png"
				}
			]
		},
		"ios": {
			"output": "dist/Main.ipa",
			"signingOptions":{
				"storetype": "pkcs12",
				"keystore": "cert/test.p12"
			},
			"files": [
				{
					"file": "icons/ios/icons/icon_48.png",
					"path": "."
				},
				{
					"file": "icons/ios/icons/icon_120.png",
					"path": "."
				}				
			]
		}		
	}
}
launch.json:
{
    // Verwendet IntelliSense zum Ermitteln möglicher Attribute.
    // Zeigen Sie auf vorhandene Attribute, um die zugehörigen Beschreibungen anzuzeigen.
    // Weitere Informationen finden Sie unter https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "swf",
            "request": "launch",
            "name": "Launch AIR desktop"
        },
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch Stand Alone SWF"
        },
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch SWF"
        },
        {
            "type": "swf",
            "request": "attach",
            "name": "Attach SWF"
        },
        {
            "type": "swf",
            "request": "attach",
            "name": "Install and Attach (Android Debug PreBuild)",
            "platform": "android",
            "preLaunchTask": "build-debug-android",
            "extdir": "${workspaceRoot}/anes"   //Comment here is a green waved line under extdir....
        },
        {
            "type": "swf",
            "request": "attach",
            "name": "Install and Attach (Android)",
            "platform": "android",
            "preLaunchTask": "build-android"
        },
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch and attach Sim SWF Debug",
            "profile": "mobileDevice",
            "screensize": "618x990:618x990",
            "versionPlatform": "AND",
            "preLaunchTask": "build-debug"
        }

    ]
}

Tried with extracted and unextracted ane.... No success..

Wonder why there is no documentation for that approach. Using anes on mobile projects is essential for us.
Hope that there is a way it works..
![image](https://user-images.githubusercontent.com/17081439/49226586-5a226a80-f3e7-11e8-84c3-1139621e5548.png)
Here the directory with the anes...

**Comment by joshtynjala** [comment]
> //Comment here is a green waved line under extdir....

It's because you've specified the `extdir` field with the "attach" request. In *launch.json*, the *extdir* field is meant to be used with the "launch" request. It's for debugging on desktop with the AIR simulator.

**Comment by joshtynjala** [comment]
Also, it looks like you're pointing to the same *anes* folder in both *asconfig.json* and *launch.json*

In *launch.json*, it should point to the unpackaged ANEs. [`extdir` in *launch.json*](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/launch.json-fields-for-SWF-debugging#extdir)

In *asconfig.json*, it should point to the packaged ANEs. [`extdir` in *asconfig.json*](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#extdir)

**Comment by joshtynjala** [comment]
FYI: The latest version of the AS3 & MXML extension for VSCode now has a better user experience for debugging with ANEs. It detects ANEs specified in the `airOptions` section of *asconfig.json* and it will automatically unpackage them for the AIR simulator. You no longer need to configure ANEs in *launch.json*.

Starting now, all you need to do is add your ANE folder to [`extdir`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#extdir) in `airOptions` and [`external-library-path`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#external-library-path) in `compilerOptions`.

**Comment by ShantanuK007** [comment]
My compiler is recognising the ane. That is I am getting all the code hinting and completion in the ide for the classes that are included inside the ane

But when I build and debug my app on android device I get the error that all the classes included in the ane cannot be found and the app fails to compile.

asconfig.json
`{
"config": "airmobile",
	"compilerOptions": {
		"output": "bin/HelloAIR.swf",
		"external-library-path": [
			"extentions"
		],
		"library-path": [
			"lib"
		]
	},
	"application": "src/HelloAIR-app.xml",
	"files": [
		"src/HelloAIR.as"
	],
	"airOptions": {
		"android": {
			"output": "bin/HelloAIR.apk",
			"listen": true,
			"signingOptions": {
				"storetype": "pkcs12",
				"keystore": "main.p12"
			}
		},
		"ios": {
			"output": "bin/HelloAIR.ipa",
			"signingOptions": {
				"storetype": "pkcs12",
				"keystore": "ios_certificate.p12",
				"provisioning-profile": "example.mobileprovision"
			}
		},
		"extdir": [
			"extentions"
		]
	}
}`


Error

>
/Users/cdp/Desktop/TestVSAIR/src/HelloAir.as(5): col: 46 Error: Definition com.myflashlab.air.extensions.billing:Purchase could not be found.

        import com.myflashlab.air.extensions.billing.Purchase;
                                                    ^

/Users/cdp/Desktop/TestVSAIR/src/HelloAir.as(6): col: 46 Error: Definition com.myflashlab.air.extensions.billing:Billing could not be found.

        import com.myflashlab.air.extensions.billing.Billing;
                                                    ^

/Users/cdp/Desktop/TestVSAIR/src/HelloAir.as(7): col: 46 Error: Definition com.myflashlab.air.extensions.billing:BillingType could not be found.

        import com.myflashlab.air.extensions.billing.BillingType;

**Comment by joshtynjala** [comment]
@ShantanuK007 Which SDK are you using?

**Comment by ShantanuK007** [comment]
I downloaded apache flex installer today only so it must be up to date. Its Flex 4.16.1 FP 32.0 AIR 32.0

I am using Mac OS Mojave

**Comment by ShantanuK007** [comment]
I Downloaded ane for Enhance and it comes with 2 files one ane file and a swc file when I include both the file in my project the project gets build and deploy successfully on my device. But if I exclude the swc file. I get the same error as above. I have not got any swc file from myflashlabs download for inapppurchase. 

Is inclusion of swc necessary? 

But If I just include the same myflashlabs ane in my adobe animate project without swc  then everything runs fine. In fact I have a android up and running on play store with active inapp purchase with the same myflashlabs ane. I am shifting my project to vscode because I don't want to pay more money for animate.

**Comment by joshtynjala** [comment]
As I understand it, older versions of Flash Builder (and other IDEs) did not recognize the *.ane* file extension, so sometimes native extensions are distributed with an extra *.swc* file so that they can be used in these older IDEs.

If a native extension includes a *.swc* file, you should not need to use it with Visual Studio Code. I guess that it's possible that there's a bug that I need to fix with the AIR packaging process.

**Comment by joshtynjala** [comment]
When I was original testing support for ANEs in Visual Studio Code, I created a simple test project. It uses only *.ane* files and no *.swc* files. I just gave that same project a try again today, and it is still working correctly.

However, one thing I realized is that I was using the AIR SDK & Compiler, but you are using the Apache Flex SDK. I wouldn't have expected this to make a difference because both SDKs should support native extensions. However, when I tried compiling the same project with the Flex SDK instead, I found that I could reproduce your issue.

I was able to find a solution.

In the `external-library-path` compiler option, you should add each *.ane* file separately, and that seems to work correctly with the Flex SDK.

If you have a folder named *native-extensions* with two files inside, A.ane and B.ane, you should add them like this:

```json
{
	"compilerOptions": {
		"external-library-path": [
			"native-extensions/A.ane",
			"native-extensions/B.ane"
		],
	}
}
```

This will **not** work if you are compiling with the Flex SDK:

```json
{
	"compilerOptions": {
		"external-library-path": [
			"native-extensions"
		],
	}
}
```

**Comment by ShantanuK007** [comment]
I am getting a new error now. I used a simple property OverrideAir. isSupported (http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/dependency/OverrideAir.html#isSupported)

And I get 

`Exception has occurred.
ReferenceError: Error #1065: Variable com.myflashlab.air.extensions.dependency::OverrideAir is not defined.
	at Main()[/Users/shantanukulkarni/Documents/AirTest/src/Main.as:15]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at AppEntryCommon/run()
	at global/runtime::AndroidMobileDeviceAppEntry()`

No matter what I use I get this error. If use Billing.init (http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/billing/Billing.html#init()) I get same error. 

You can download OverrideAir Ane from here (https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir) Its free. 

I am new to this sdk environment and I have been using adobe flash/animate and pure as3 no flex etc. I have imported "fl" classes in my app and I see now that flexSDK does not Include that. What sdk do you recommend?

**Comment by joshtynjala** [comment]
> I am new to this sdk environment and I have been using adobe flash/animate and pure as3 no flex etc. I have imported "fl" classes in my app and I see now that flexSDK does not Include that. What sdk do you recommend?

`fl` components are only available when you use Animate. They are not available with any other SDKs.

**Comment by joshtynjala** [comment]
> No matter what I use I get this error.

Maybe you can try `library-path` instead of `external-library-path`.

**Comment by ShantanuK007** [comment]
I think there is a problem with newer anes. Older ane "Enhance" works properly but the newer and upto date ane from myflashlabs causes problem. 

[All the images for reference](https://imgur.com/a/acOLUGd).
https://imgur.com/a/acOLUGd

I used both FlexSDK and AIRSDK and compiler. Both caused same problem.

If you want you can download all the anes (Enhance and OverrideAIr) for testing they are free

**Comment by joshtynjala** [comment]
@ShantanuK007 Do you have `extdir` set in *launch.json*? If so, please remove that field. vscode-as3mxml will automatically populate `extdir` in *launch.json* when you run/debug in the AIR simulator.

**Comment by ShantanuK007** [comment]
I don't have extdir in launch.json

https://imgur.com/a/ItI5NZd
