### ISSUE TITLE
Warnings still shown even with warnings: false

### ISSUE THREAD

**Issue by matthughes** [BowlerHatLLC/vscode-nextgenas#191]
Despite having warnings set to false:

```json
{
    "config": "flex",
    "type": "app",
	"compilerOptions": {
        "warnings": false
    }
}
```

VSCode is still presenting me with warnings in my problems view.

**Comment by joshtynjala** [comment]
For some reason, the Apache Royale compiler does not seem to exclude warnings when you use this option. Perhaps I can find a way to manually filter them out instead.
