### ISSUE TITLE
Missing assets in debug build

### ISSUE THREAD

**Issue by embpdaniel** [BowlerHatLLC/vscode-nextgenas#192]
Hi, I'm trying to get a debug build to run on my IOS simulator. My build fails with these errors:

```
ReferenceError: Error #1065: Variable OpenSans-Bold_ttf$0ac9260dbeb4b13049997d20eb4713cc-1254098573 is not defined.
ReferenceError: Error #1065: Variable OpenSans-Regular_ttf$4347b3d24aaca981d89ed80831d6fb77-1243645492 is not defined.
ReferenceError: Error #1065: Variable HelveticaNeueLTStd-BdCn_otf$a0fea3a1acaa1b3bbcb2ac17a0ad793c-1574446226 is not defined.
ReferenceError: Error #1065: Variable Spinner is not defined.
```
These are fonts from an assets located at src/assets, and `Spinner` is a MovieClip from a .swc file I export from Animate, which I save into my libs folder. For some reason these are not found, and I'm not quite sure really on how to include these files on my debug build.

The only config that I have set up so far, that references these assets is in my` asconfig.json` file:

```
{
  "config": "airmobile",
  "compilerOptions": {
      "strict": false,
      "output": "out/app.swf",
      "library-path": [
        "libs"
      ]
  },
  "application": "src/Sports App-app.xml",
  "files":
  [
      "src/Main.as"
  ],
  "airOptions": {
    "android": {
      "files": [
        {
          "file": "src/assets",
          "path": "./assets"
        }
      ],
      "extdir": [
        "./libs"
      ],
      "output": "out/Main.apk",
      "signingOptions": {
        "storetype": "pkcs12",
        "keystore": "android_certificate.p12"
      }
    },
    "ios": {
      "files": [
        {
          "file": "src/assets",
          "path": "./assets"
        }
      ],
      "extdir": [
        "./libs"
      ],
      "output": "out/Main.ipa",
      "signingOptions": {
        "storetype": "pkcs12",
        "keystore": "ios_certificate.p12",
        "providerName": "path/to/file.mobileprovision"
      }
    }
  }
}
```
As you can see, I have included the "libs" folder for my swc file, and I added the 'files' field for android and ios, setting the `src/assets` directory as the source, and `./assets` as where I'd like to place it in the package, if I'm understanding how this works.

Is there anything off here? Do I need to include these paths in another config somewhere? Thanks in advance!

**Comment by joshtynjala** [comment]
Try setting copySourcePathAssets to true in asconfig.json. That should copy src/assets to out so that the files will be available when testing in the AIR debug launcher.

**Comment by joshtynjala** [comment]
The path field here *might* need to be ./ instead of ./assets:

{ "file": "src/assets", "path": "./assets" }

I always forget how ADT expects that to work.

The best way to check that included files are in the correct place is to unzip the .ipa file. (In case you didn't know, you can rename .ipa to .zip and extract.)

**Comment by embpdaniel** [comment]
@joshtynjala No luck unfortunately. It won't copy anything over no matter what path I put or if copSourcePathAssets is set to true or not. For now I have copied the assets folder manually and that seems to work, so not a huge deal really :)
