### ISSUE TITLE
Can't find on wiki anything relate to use .fla or .xfl files/folders as source

### ISSUE THREAD

**Issue by PippoApps** [BowlerHatLLC/vscode-nextgenas#193]
Hi,
I am salivating over compiling with VSCode, but even though I develop Flash and AIR since 15 years, I have always used Flash/Animate to compile and debug apps.

I would love to move to VS code+nextgenas, but I do not seem to find a way to build from a fla source file. could you point me in the right direction?
Thanks

**Comment by joshtynjala** [comment]
You may be able to set up a coding environment in VSCode, but you will need to continue to compile and debug in Animate/Flash. There is no support for FLA/XFL files in the VSCode extension, and none is planned for the future.

**Comment by PippoApps** [comment]
Makes sense though. No choice than animate.
Thank you Josh.
