### ISSUE TITLE
Completion of fx:Style, fx:Component and fx:Script is missing first char < if completion is not triggered by <

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#196]
Preview of the issue:
![2018-04-13_02-15-05](https://user-images.githubusercontent.com/1468887/38710415-a4c52ab4-3ec0-11e8-9139-583fe4af5da7.gif)

**Comment by joshtynjala** [comment]
Unfortunately, I haven't found a good way to detect if the < is already there or not when completion list is opened in MXML.

I think most people simply start typing < when they want to add a new tag, which will open the completion list too

**Comment by joshtynjala** [comment]
I've figured out how to solve this issue. I'll get it into the next update!

**Comment by neminovno** [comment]
Great. BTW Did you mean to add this to v0.12 and not as it says to v0.11 milestone? Same for https://github.com/BowlerHatLLC/vscode-nextgenas/issues/201 and https://github.com/BowlerHatLLC/vscode-nextgenas/issues/202

**Comment by joshtynjala** [comment]
I intend to release a v0.11.1 update with some bug fixes.

**Comment by neminovno** [comment]
Oh ok, thanks for explanation.
