### ISSUE TITLE
Completion suggestions grouping after repeated pressing CTRL+Space

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#197]
In Flash Builder, after pressing CTRL+Space, completion appears (as in VSCode), and pressing it again only available methods are shown, pressing it again only properties are shown, pressing again 'code templates'/snippets are shown. Is there such possibility in VSCode?

It would be good to have option to somehow see only snippets in completion, then it is quicker to find/select one. Otherwise, as far as I know, only option to have it in VSCode is to have common prefix in name for all custom User snippets, to have them grouped.

**Comment by joshtynjala** [comment]
Unfortunately, this is not currently possible in Visual Studio Code.
