### ISSUE TITLE
[0.1.x] MXML errors don't go away after file changes

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-nextgenas#20]
I have the following code in a component:
<?xml version="1.0" encoding="utf-8"?>
<js:TextButton xmlns:js="library://ns.apache.org/flexjs/basic" xmlns:fx="http://ns.adobe.com/mxml/2009"
		   styleName="baseButton">
	<fx:Script>
		<![CDATA[
			private function init():void{
			}
		]]>
	</fx:Script>
	
</js:TextButton>

VS Code is complaining at the first tag:
message: 'This tag could not be resolved to an ActionScript class. It will be ignored.'
at: '2,1'

FB does not report any errors in this file and properly resolves the tag to org.apache.flex.html.TextButton.

**Comment by Harbs** [comment]
That was weird. Restarting VS Code caused the issue to go away.

**Comment by Harbs** [comment]
It looks like it's a general problem with MXML files. Issues in the "Problems" pane are not cleared up when fixed. I don't see any way to clear up the problems other than restarting VS Code.

This seems to be a problem with MXML files. .as files refresh as they should automatically.

**Comment by joshtynjala** [comment]
Assuming that you're running 0.1.x, it may simply be that the extension is completely ignoring MXML files in certain places. It's probably checking for the .as file extension only.

There is one issue in the Apache FlexJS compiler where its MXML parser can get into an infinite loop when MXML is malformed, but you're probably not running into that with 0.1.x.

**Comment by Harbs** [comment]
I'm using 0.1.1. When the project is first opened, it's checking the file correctly. When the file is subsequently changing, those changes are not being checked. It seems to be universal (at least in my project).

**Comment by joshtynjala** [comment]
Yeah, that's the expected behavior right now. MXML truly isn't supported in this version. If I need to do another update on the 0.1.x branch, I'll at least make it watch the file system for changes and tell the compiler about them.
