### ISSUE TITLE
How to contribute snippets?

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#200]
Are new snippets planned?
If new snippets contribution is welcomed, are there any rules for snippet naming and/or prefixes?
Regarding MXML snippets, are [these ones](https://github.com/BowlerHatLLC/vscode-nextgenas/blob/master/distribution/src/assembly/snippets/mxml.json) only currently implemented?

**Comment by joshtynjala** [comment]
The available snippets are the only ones that I currently plan to include with the extension. I would certainly be willing to consider contributions. However, you could also create your own custom extension to distribute snippets.

For [ActionScript](
https://github.com/BowlerHatLLC/vscode-nextgenas/blob/master/distribution/src/assembly/snippets/actionscript.json), I basically copied exactly what Microsoft provides for TypeScript.

The snippets that you linked are indeed the only ones that I've created for MXML. What other types of MXML snippets do you have in mind?

**Comment by neminovno** [comment]
After exporting MXML code templates from Flash Builder into XML file, I created script to convert them to VSCode snippets format (there is some minor issues left to fix). So thought was it would be great to have all those snippets bundled with extension. I'm testing them by copy into User Snippets mxml.json file, this is how it looks now:
![2018-04-16_18-06-59](https://user-images.githubusercontent.com/1468887/38821611-574527ec-41a1-11e8-930e-e74e1296947a.gif)


Probably the same could be done for ActionScript code templates.

Just noticed, [this issue](https://github.com/BowlerHatLLC/vscode-nextgenas/issues/196) can also be fixed by using snippet.
