### ISSUE TITLE
Zombie Java processes left behind by NextGenAS after closing VSCode

### ISSUE THREAD

**Issue by knetworx** [BowlerHatLLC/vscode-nextgenas#206]
OS: MacOS High Sierra 10.13.4
VSCode version: 1.22.2
NextGenAS version: 0.11.1
Related bug: #143 (Currently marked closed)

I noticed my computer chugging a bit ago, without anything that should've been taking up too much processing. I closed out IntelliJ and VSCode, and still everything was running slow. Looking in the Activity Monitor, I noticed a series of java processes using up a bunch of memory. Checking the "Open Files and Ports", it appears these are zombie processes left behind by NextGenAS whenever VSCode is closed.

![java_processes](https://user-images.githubusercontent.com/3292803/39456655-fb179c1e-4c9c-11e8-87eb-4a2215e41c42.png)
![java_processes2](https://user-images.githubusercontent.com/3292803/39456656-fb2acb86-4c9c-11e8-8cef-dfbb356e27fd.png)
![java_openfilesandports](https://user-images.githubusercontent.com/3292803/39456654-fb0338b4-4c9c-11e8-942d-f3a3e45b6a7c.png)

I was able to reproduce this by opening and quitting VSCode (via Cmd+Q) a few times.

**Comment by joshtynjala** [comment]
That's strange! It seems like Microsoft changed how VSCode handles child processes because I haven't touched the code that starts the extension in a long time (and I know for sure that everything was working correctly on macOS when #143 was fixed).
