### ISSUE TITLE
Organize imports error if run in one project in workspace with two projects

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#208]
Note: I copied one project to another folder, and in VSCode added that folder to workspace.

Output panel after file clean up:

> Could not create compilation unit for file (final fallback): c:\dev\flex\qtp\src\Main.mxml

Output panel without file clean up:

> Could not create compilation unit for file (final fallback): c:\dev\flex\qtp\src\Main.mxml
> svi 01, 2018 6:15:43 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
> SEVERE: Internal error: java.lang.reflect.InvocationTargetException
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
> 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:252)
> 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:181)
> 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:183)
> 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:92)
> 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
> 	... 11 more
> Caused by: java.lang.NullPointerException
> 	at com.nextgenactionscript.vscode.utils.ImportTextEditUtils.organizeImportsFromStartIndex(ImportTextEditUtils.java:98)
> 	at com.nextgenactionscript.vscode.utils.ImportTextEditUtils.organizeImports(ImportTextEditUtils.java:175)
> 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.organizeImportsInUri(ActionScriptTextDocumentService.java:6141)
> 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.executeOrganizeImportsInUriCommand(ActionScriptTextDocumentService.java:6164)
> 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.executeCommand(ActionScriptTextDocumentService.java:1138)
> 	at com.nextgenactionscript.vscode.ActionScriptLanguageServer$1.executeCommand(ActionScriptLanguageServer.java:309)
> 	... 16 more
> 
> [Error - 18:15:43] Request workspace/executeCommand failed.
>   Message: Internal error.
>   Code: -32603 
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
> 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:252)
> 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:181)
> 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:183)
> 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:92)
> 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
> 	... 11 more
> Caused by: java.lang.NullPointerException
> 	at com.nextgenactionscript.vscode.utils.ImportTextEditUtils.organizeImportsFromStartIndex(ImportTextEditUtils.java:98)
> 	at com.nextgenactionscript.vscode.utils.ImportTextEditUtils.organizeImports(ImportTextEditUtils.java:175)
> 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.organizeImportsInUri(ActionScriptTextDocumentService.java:6141)
> 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.executeOrganizeImportsInUriCommand(ActionScriptTextDocumentService.java:6164)
> 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.executeCommand(ActionScriptTextDocumentService.java:1138)
> 	at com.nextgenactionscript.vscode.ActionScriptLanguageServer$1.executeCommand(ActionScriptLanguageServer.java:309)
> 	... 16 more

**Comment by joshtynjala** [comment]
@neminovno So, as I understand it, you've created a multi-root workspace, and you've added two root folders to the workspace. Is the file where you're running the Organize Imports command in your first root folder or is it in the second?

**Comment by neminovno** [comment]
Not sure about terminology here. I wanted to work on two unrelated projects in same Workspace. I used right click in File Explorer then "Add Folder to Workspace":
![image](https://user-images.githubusercontent.com/1468887/39484347-d5a0eae2-4d75-11e8-81b3-cb3bb2b37097.png)

It was file in second project where Organize imports command is run.

I didn't use Actionscript source path: 
![image](https://user-images.githubusercontent.com/1468887/39484477-376a4e08-4d76-11e8-818e-f41260eb62cc.png)

**Comment by joshtynjala** [comment]
Currently, the extension supports only one root folder in a workspace. Some things, like build tasks and debugging, work in additional root folders already, but code intelligence does not yet. I need to do some serious refactoring to make the extension support multiple projects in the same workspace. It's been on my todo list for several months, but other things have taken priority.

I'm going to close this issue, in favor of the existing issue: #147
