### ISSUE TITLE
Create a .as class file in the VsCode file, "class duplicate definition: className" error

### ISSUE THREAD

**Issue by kingBook** [BowlerHatLLC/vscode-nextgenas#213]

**Comment by joshtynjala** [comment]
Can you provide more detailed instructions to reproduce the issue?

**Comment by kingBook** [comment]
https://github.com/kingBook/anquanjiaoyu/blob/master/duplicateError.gif"

**Comment by joshtynjala** [comment]
@kingBook Can you share the contents of your *asconfig.json* file with me?

**Comment by kingBook** [comment]
https://github.com/kingBook/anquanjiaoyu
This is not a issues every time.

**Comment by joshtynjala** [comment]
Thanks! It looks like my commit will fix your issue, so stay tuned for the upcoming v0.12 update.
