### ISSUE TITLE
"Attach SWF" launch configuration shows error after (~60 seconds) timeout

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#216]
If one follows wiki [Debug an Adobe AIR desktop application with Visual Studio Code](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Debug-an-Adobe-AIR-desktop-application-with-Visual-Studio-Code), after this step:
_7. Ensure that the Attach SWF configuration is selected is the Debug sidebar, and..._
debug never starts, and after long timeout (~60sec) this error pops up:
![image](https://user-images.githubusercontent.com/1468887/40273928-9fabaf2c-5bca-11e8-9316-68f0cdbca92a.png)

Is "Attach SWF" used only for mobile projects? If yes, then "Attach SWF" step should be removed from wiki for desktop projects.

**Comment by joshtynjala** [comment]
It can certainly be used for desktop projects too, but I don't think it's particularly common.

You need to manually launch the AIR Debug Launcher (ADL), of course. The "launch" request is for when you want VSCode to launch your app automatically. The "attach" request is for when you want to attach the debugger to an app that is launched in some other way.

**Comment by joshtynjala** [comment]
Oh wait. I see now that it's a typo. Sorry about that!
