### ISSUE TITLE
nextgenas.flexjssdk in settings does not point to a valid SDK. 

### ISSUE THREAD

**Issue by shiyamon** [BowlerHatLLC/vscode-nextgenas#22]
Hi,

I tried to install nextgenass but can't point FlexJS SDK. I downloaded FlexJS from Apache Flex website and modified VSCode User Settings so that "nextgenas.flexjssdk" point to a directory that I store FlexJS but VSCode alway shows error message like,

nextgenas.flexjssdk in settings does not point to a valid SDK. Requires Apache FlexJS 0.7.0 or newer.

System I use
- macOS 10.12.1
- VSCode 1.7.2

**Comment by joshtynjala** [comment]
If you downloaded it from the website, did you remember to run `ant -f installer.xml` to download all dependencies?

You don't need to do that if you use the Apache Flex Installer app or if you install from NPM. Those are probably the easiest options.

**Comment by joshtynjala** [comment]
Were you able to get it working?

**Comment by joshtynjala** [comment]
Thanks, @bithooked!
