### ISSUE TITLE
Installing app on device failed for platform "ios" with status code: 14.

### ISSUE THREAD

**Issue by m-a-v** [BowlerHatLLC/vscode-nextgenas#221]
I am trying to start an AIR application on the mobile device. Where can I find more information about the error codes? Would it be possible to make a more generic error description?

Preparing to install Adobe AIR application...
Installing Adobe AIR application...
Installing app on device failed for platform "ios" with status code: 14.

**Comment by joshtynjala** [comment]
There are a couple of reasons listed in Adobe's official documentation: [ADT installApp command](https://help.adobe.com/en_US/air/build/WS901d38e593cd1bac1e63e3d128fc240122-7ffa.html).

* If the specified device is not connected, ADT returns exit code 14: Device error (Android) or Invalid device specified (iOS).
* If the specified package is already installed, ADT returns error code 14: Device error.

It's not the second one. VSCode always uninstalls the app before trying to install again.

Which platform are you on? On Windows, make sure to open iTunes. On any platform, make sure that you've unlocked the device and given permission for your computer to connect.

**Comment by m-a-v** [comment]
Thanks a lot for the hints. Do I need to explicitly name the device in a settings file or where/how can I specify the device?

Currently, I am on OS X High Sierra. iOS device is unlocked and has permission (I already used it with Flash Builder, which obviously I want to replace with VS Code 🥇).

**Comment by m-a-v** [comment]
This is the message box which appears.

![screenshot](https://user-images.githubusercontent.com/16197536/40944254-5fa667aa-6854-11e8-8a4c-c304dc0874ca.png)

**Comment by joshtynjala** [comment]
> Do I need to explicitly name the device in a settings file or where/how can I specify the device?

No, it should automatically detect your device. Just make sure that it's connected via USB and that no other iOS devices are also connected at the same time.

> This is the message box which appears.

I think that this is a bug in VSCode, but it's normal when debugging fails.

**Comment by joshtynjala** [comment]
@m-a-v Were you able to get an app installed on iOS?

**Comment by joshtynjala** [comment]
Are you still seeing this error?

>  Installing app on device failed for platform "ios" with status code: 14.

I ask because the screenshot of the empty message box that you posted leads me to believe that installation might be completing successfully. That empty message box usually means that it's not connecting to the debugger after the app launches. Correct me if I'm wrong.

If your mobile device is on wifi, but your computer is not, you could try using the "connect" option for an "attach" request. This will attempt to connect to the debugger over USB instead of wifi.

``` json
{
	"type": "swf",
	"request": "attach",
	"name": "Attach SWF",
	"platform": "ios",
	"connect": true
}
```

**Comment by m-a-v** [comment]
After a long time I retry again to move our project to VS Code. The device was always attached with USB. The installation is certainly not successful. If I install the ipa using the adt tool I get an ApplicationVerificationFailed error, so I think this lead to the error 14 at the end.

Installation Error: ApplicationVerificationFailed.

The problem was that I made a typo in the application id.

BTW: Is there a way to store/cache the Adobe AIR code signing password?

**Comment by joshtynjala** [comment]
> BTW: Is there a way to store/cache the Adobe AIR code signing password?

Not at this time, but it's something that I want to add.

**Comment by KlausNordby** [comment]
hello, was this resolved?
