### ISSUE TITLE
Packaging captive runtime: If separate section is not created for platform, it packages as shared runtime

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#222]
Or in another words, it seems like this line from [wiki](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Adobe-AIR-for-desktop-platforms):

> When an application uses captive runtime, **we can create** separate sections for each platform to specify different options.

should be: **we should/must create** ?

Because, if you have this in asconfig.json:
```
"airOptions": {
		"output": "bin/MainBundleFolder", // this way only Shared Runtime package is available
		/* 
                this way one has package as Captive Runtime task AND as Shared Runtime
                "windows": {
			"output": "bin/MainBundleFolder"
		}, */
		"signingOptions": {
			"storetype": "pkcs12",
			"keystore": "C:\\dev\\cert\\my-selfsigned-2048-RSA-cert.p12"
		}
	}
```
there is no Captive Runtime task available:
![image](https://user-images.githubusercontent.com/1468887/41024097-943b4aba-696e-11e8-8641-e3a48665816a.png)

and released package name is _output_ + ".air" added. In this case "MainBundleFolder.air" appears in bin folder. So, one must/needs to create separate section per platform to have Captive Runtime task.

Also, related issue, if one creates separate section, in order to have package as Captive Runtime, like this:
```
"airOptions": {
		"windows": {
			"output": "bin/MainBundleFolder"
		},
		"signingOptions": {
			"storetype": "pkcs12",
			"keystore": "C:\\dev\\cert\\my-selfsigned-2048-RSA-cert.p12"
		}
	}
```
and opens Tasks -> Run task, this is visible:
![image](https://user-images.githubusercontent.com/1468887/41024495-b3fbcd4c-696f-11e8-93d4-4f234adcf651.png)

and if Shared Runtime is selected, this error appears:

> no such file C:\dev\my-project\Main.swf

Yes, if one sets asconfig for Captive Runtime, why it would click Package Shared Runtime, but maybe that task should not be visible? So no confusion can happen.

**Comment by joshtynjala** [comment]
In that statement, "can" is correct because you are supposed to be able to specify the `target` field in the root of `airOptions`, and set it to "bundle" (it's better to have separate `windows` and `mac` sections, but it's not required). However, it appears that I've accidentally removed `target` as a valid property at the root of of `airOptions` in the *asconfig.json* schema, so this doesn't work at the moment. I'll get it fixed, and that statement will be correct again.

> and if Shared Runtime is selected, this error appears:

I'll investigate and get this fixed.
