### ISSUE TITLE
How to get all classes from language server?

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#224]
For example, can an extension ask language server to provide available MXML and AS classes?
There is `commands.executeCommand('vscode.executeWorkspaceSymbolProvider', '');` to get symbols from local project, but how to get all available symbols from SDK?

I am considering adding few commands to [Flex Snippets](https://github.com/neminovno/vscode-flex-snippets) like:
- initialize project in empty folder
- create new component

**Comment by joshtynjala** [comment]
Currently, there's no way to do it. However, since I added the ability to generate text for classes in SWCs, I've been meaning to look into adding more symbols to the result from the workspace symbol provider. The SDK classes might be appropriate to add there. I think I should check what TypeScript includes in the workspace symbols to determine how AS3 & MXML should behave, so that they're similar.

**Comment by joshtynjala** [comment]
I just checked, and TypeScript includes symbols from its core library in the workspace symbols result. I'll make sure to update AS3 & MXML to include SDK symbols to match this behavior.

**Comment by neminovno** [comment]
In following playing demo, classes list are from manually copied manifest.xml from mx and spark directories from SDK, and local classes (only Main here) are from `executeWorkspaceSymbolProvider`:

![2018-06-07_15-32-10](https://user-images.githubusercontent.com/1468887/41103087-9adac378-6a68-11e8-9743-f59c168a2af8.gif)

But, proper way would be to ask language server, in order to have 100% classes from user's choosen SDK, right?
Also, it would be good to separate local project's and SDK's classes, somehow. Because it would be easier to find wanted class, if user don't recall correct class name.

**Comment by joshtynjala** [comment]
> But, proper way would be to ask language server, in order to have 100% classes from user's choosen SDK, right?

Correct. `executeWorkspaceSymbolProvider` should return all classes from the SDK too, but currently, it doesn't.

**Comment by neminovno** [comment]
Great! It is a huge list now.
In order to preload it, if `executeWorkspaceSymbolProvider` is called too early it returns 0 symbols. Is there a way to know when is the extension ready to provide result in `executeWorkspaceSymbolProvider` ? Or, how to know when the extension finished initializing language server?

**Comment by joshtynjala** [comment]
I would expect the call to start working as soon as the initializing spinner in the status bar is hidden.

**Comment by neminovno** [comment]
Correct. But how to know (programmatically) when its hidden? In my case it takes 3-6seconds, and few more to load all symbols.
This is not so important, I doubt someone will use _Create new component_ command few seconds after starting VSCode. But anyway, if there is option to know when the symbols list is available, it would be better to preload them, instead of using settimeout or preload symbols on first command call.

**Comment by joshtynjala** [comment]
> Correct. But how to know (programmatically) when its hidden? In my case it takes 3-6seconds, and few more to load all symbols.

I don't think that there's a way to check programmatically. There's an `isActive` property on the [`Extension`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Extension%3CT%3E) class, but I think that `isActive` changes from `false` to `true` before everything is actually ready.

> it would be better to preload them

Don't forget that when classes are created or deleted in the project, your preloaded list might be out of sync. It's probably better to request symbols in real-time, just like VSCode does.

**Comment by neminovno** [comment]
> but I think that isActive changes from false to true before everything is actually ready.

Correct, after adding extension dependency in package.json, and checking `isActive`, it is still early to call.

> Don't forget that when classes are created or deleted in the project, your preloaded list might be out of sync. It's probably better to request symbols in real-time, just like VSCode does.

Thanks on note. It takes some time now - not good for UI and work flow, but I just started playing with it, probably some optimal solution will come in way. Maybe keeping project's classes in separate array for quicker update, then concatenate before `showQuickPick`.
