### ISSUE TITLE
Warning on bindings when binding is on xml attributes

### ISSUE THREAD

**Issue by Sushi21** [BowlerHatLLC/vscode-nextgenas#228]
Hi,

For fun i'm trying to move an airmobile app we are doing on Flashbuilder to VScode using your plugin.

Im getting lot of warning very useful that i don't get on flashbuilder.

However there is one warning coming all over the place.

{
	"resource": "***.mxml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "undefined",
	"severity": 4,
	"message": "Data binding will not be able to detect assignments to 'displayerror'.",
	"startLineNumber": 1,
	"startColumn": 23,
	"endLineNumber": 408,
	"endColumn": 129
}

we use binding on xml and a lot are on attributes like

`<s:label id="example" visible"{node[0].@displayerror == '1'}" />`

Is there a way to avoid that warning?

**Comment by joshtynjala** [comment]
You could try adding the `-show-binding-warnings=false` to the `additionalOptions` field in *asconfig.json*.

**Comment by Sushi21** [comment]
I added it but warnings wont go away.
do you see something wrong?

"additionalOptions": "-allow-source-path-overlap=true -show-binding-warnings=false"

thanks

**Comment by joshtynjala** [comment]
Recently, I discovered that I need to manually hide warnings when the `warning` compiler option is set to `false`. Perhaps `-show-binding-warnings=false` works similarly. I was hoping that the compiler would exclude those warnings automatically, but perhaps that's not the case. With this in mind, there is currently no way to hide a particular type of warning in VSCode. You can only hide all of them, which isn't usually desirable, in my opinion.

**Comment by Nisaba** [comment]
Hi,
I've also experimented this issue.
When will the next release of as3mxml will be available ?

Thanks

**Comment by joshtynjala** [comment]
@Nisaba I think that you can add the following to your *asconfig.json*:

```
"additionalOptions": "-show-binding-warnings=false"
```

The newest release should have fixed the issue where warnings could not be hidden.
