### ISSUE TITLE
Wiki: wrong example for platformsdk

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#229]
It is [here](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/asconfig.json#platformsdk-1):

> The path to the Android SDK.
> 
> ```
> "airOptions": {
> 	"android": {
> 		"listen": true
> 	}
> }
> ```

**Comment by joshtynjala** [comment]
Thanks! Fixed.
