### ISSUE TITLE
Get selected SDK's AIR version from the extension

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#231]
Something like this `getAIRversion():string` into [here](https://github.com/BowlerHatLLC/vscode-nextgenas/blob/424040292c1aae785f245b2b718d398ca384447b/vscode-extension/src/main/ts/extension.ts#L315-L322)?

That would make easy to insert correct version into application descriptor XML file, while automatically creating project files.

By the way, why not add AIR version in status bar:
![image](https://user-images.githubusercontent.com/1468887/41821205-56e63e86-77dd-11e8-84d1-0d6578d7dd5e.png)

**Comment by joshtynjala** [comment]
> Something like this getAIRversion():string into here?

My gut feeling says that if I expose anything there, it should simply be the file system path to the currently selected SDK. From there, you could figure out the AIR version on your own.

> By the way, why not add AIR version in status bar:

I tried to keep the string as short as possible. Plus, the AIR version isn't even necessarily available in the *flex-sdk-description.xml* file where I find the SDK name and version. Some SDKs append the AIR version to the SDK name in this file, but not all of them do.

I didn't look into it before, but it appears that the AIR version can be parsed from the *airsdk.xml* file in the root of the SDK.

**Comment by neminovno** [comment]
> file system path to the currently selected SDK

Would be enough.
