### ISSUE TITLE
False error after project files delete, create

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#232]
When using an extension to delete/create new project files sometimes false errors appear.
One of them could be fixed #227

Another one is this:

> This tag could not be resolved to an ActionScript class. It will be ignored.
> This tag could not be resolved to an ActionScript class. It will be ignored.

Complete message:

> {
> 	"resource": "/c:/dev/vsc-extensions/test5/src/MyApp.mxml",
> 	"owner": "_generated_diagnostic_collection_name_#0",
> 	"code": "1450",
> 	"severity": 8,
> 	"message": "This tag could not be resolved to an ActionScript class. It will be ignored.",
> 	"startLineNumber": 2,
> 	"startColumn": 1,
> 	"endLineNumber": 2,
> 	"endColumn": 23
> }

It is false error. Debug works. Error(s) disappear on folder close then open.
In this example code is:

```
<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
   xmlns:s="library://ns.adobe.com/flex/spark"
   xmlns:mx="library://ns.adobe.com/flex/mx">

</s:Application>
```

One note is if you add `XX` after `<s:Application` error changes into:
`<s:WindowedAppXXlication ...`

but there is only `Application` tag. Not sure, but it could be that the just deleted project files main app was using `WindowedApplication`.

Animation:
![2018-06-27_21-59-09](https://user-images.githubusercontent.com/1468887/41996708-051abfb6-7a56-11e8-90da-404fbf127752.gif)

Another error (while creating project files programmatically) is when error is reported in a file that was deleted on disk. 
So it looks like the extension keeps project files indexed somewhere that don't get cleaned when deleted?

Note: In every "create project" process, the last written file is _asconfig.json_ as I thought it could be the reason as it might try read some files that are not yet written, but it didn't help me resolve this rare false errors.

**Comment by joshtynjala** [comment]
Are you using v0.12?

**Comment by joshtynjala** [comment]
Nevermind. It doesn't matter. I'm actually working on this issue right now:

>  So it looks like the extension keeps project files indexed somewhere that don't get cleaned when deleted?

**Comment by neminovno** [comment]
> Are you using v0.12?
I am using latest version, few hours ago I downloaded and compiled, and using vsix.

**Comment by joshtynjala** [comment]
Just so you know, I consider the latest code from Github to be very unstable right now. The refactoring for multi-root workspaces is changing things all over the codebase, and I'm still in the middle of the process.

**Comment by neminovno** [comment]
Thanks for info. Anyway, my plan is to wait for v0.13. For fixed issues, and also because of multi-root workspaces as it enables me to add same support for 'create project' command (choose folder within workspace folders to create project into instead of use first folder).

**Comment by joshtynjala** [comment]
This particular issue should be fixed now, so I'm closing. Deleted files were not properly cleared from memory, but now they should be.
