### ISSUE TITLE
AIR Mobile Debug Issue

### ISSUE THREAD

**Issue by rhett-thompson** [BowlerHatLLC/vscode-nextgenas#237]
When I try to debug my project I receive the "Error launching SWF debug session..."; the file displayed in the error dialog is the application.xml file.

I've set the default program to open SWF files to the debug flash player.

Setting the runtimeExecutable path to the player gets rid of the error, however the player doesn't load my SWF.

Am I missing something?

Thanks.

**Comment by joshtynjala** [comment]
You may have the wrong AIR version in your AIR application descriptor XML. Generally, it should match the exact version of the SDK that you are using.

runtimeExecutable should point to Flash Player only when you want to debug in Flash Player. For an AIR app, you shouldn't need to set it, but if you happened to want to set it, for some reason, it should point to the adl executable instead.

**Comment by rhett-thompson** [comment]
Ahh if I manually set the **program** in the launch.json it works as expected.

For some reason it's failing to autopopulate with the path to my SWF file.

**Comment by joshtynjala** [comment]
For an AIR app, the "program" in *launch.json* should be your AIR application descriptor XML file. It should automatically populate if your *asconfig.json* has the "application" field and the "output" compiler option both set.

If you set "program" to the SWF file, it will run in Flash Player instead, and any AIR APIs that you try to use will not work.

If you could share the contents of both *launch.json* and *asconfig.json*, I could probably make some more suggestions.

**Comment by rhett-thompson** [comment]
Oh I see, you're right.

**launch.json**
`{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch AIR Mobile",
            "profile": "mobileDevice",
            "screensize": "800x1400:800x1400",
            "versionPlatform": "AND",
            "preLaunchTask": "build-debug",
            "program": "bin/astrozone.xml"
        }
    ]
}`

**asconfig.json**
`{
    "config": "airmobile",
    "compilerOptions": {
        "output": "bin/astrozone.swf",
        "library-path": [
            "lib"
        ]
    },
    "application": "astrozone.xml",
    "files":
    [
        "src/Main.as"
    ]
}`

**Comment by hydroper** [comment]
@rhett-thompson Formatting it quickly...

**launch.json**

```json
{
  "version":"0.2.0",
  "configurations":[
    {
      "type":"swf",
      "request":"launch",
      "name":"Launch AIR Mobile",
      "profile":"mobileDevice",
      "screensize":"800x1400:800x1400",
      "versionPlatform":"AND",
      "preLaunchTask":"build-debug",
      "program":"bin/astrozone.xml"
    }
  ]
}
```

**asconfig.json**

```json
{
  "config":"airmobile",
  "compilerOptions":{
    "output":"bin/astrozone.swf",
    "library-path":[
      "lib"
    ]
  },
  "application":"astrozone.xml",
  "files":[
    "src/Main.as"
  ]
}
```

**Comment by joshtynjala** [comment]
Looks good to me! Based on what you have there, you should be able to remove "program" from *launch.json* now, and it should be automatically detected. However, you can certainly leave it in too. It won't hurt anything.

**Comment by joshtynjala** [comment]
@hydroper Thanks! I just edited the original comment to add the formatting there.

**Comment by rhett-thompson** [comment]
After removing **program** it's still launching the debug flash player with no SWF loaded.

If I set **runtimeExecutable** to adl.exe i get "Error launching SWF debug session. Process exited with code: 7"

The debug console is now spitting this following error:

"Process terminated without establishing connection to debugger.
invalid application descriptor: initialWindow/content must have a non-empty value."

**Comment by hydroper** [comment]
@rhett-thompson Try specifying your SWF as follows:

```xml
<?xml version="1.0" encoding="utf-8" ?> 
<application xmlns="http://ns.adobe.com/air/application/29.0">
	
	<id>com.id</id> 
	<versionNumber>1.0</versionNumber> 
	<filename>FileName</filename> 
	
	<name>AppName</name> 
	<description></description> 
	<copyright></copyright> 
	
	<initialWindow> 
		<title>Untitled</title> 
		<content>.build/target/swiff.swf</content> <!-- path to your SWF (that's mine) -->
		<!--systemChrome>standard</systemChrome> 
		<transparent>false</transparent> 
		<visible>true</visible> 
		<minimizable>true</minimizable> 
		<maximizable>true</maximizable> 
		<resizable>true</resizable--> 
	</initialWindow> 
	
	<!-- 
	More options:
	http://livedocs.adobe.com/flex/3/html/File_formats_1.html#1043413
	-->
</application>
```

**Comment by rhett-thompson** [comment]
@hydroper That did the trick.  So it looks like i'm not getting **content** to auto populate for some reason.

Also, if I remove **runtimeExecutable** (which is set to adl.exe) - it runs the empty debug flash player.

**Comment by hydroper** [comment]
@rhett-thompson I don't believe ADT/ADL auto populate the content for you, even because it can be a HTML and not only a SWF, too.

**Comment by joshtynjala** [comment]
VSCode should automatically populate `<content>` with the correct file when it copies your XML file to *bin* during the build process. Is it possible that `<content>` is entirely missing in your original file?

**Comment by rhett-thompson** [comment]
`<content>` has been present all along.

It's also not auto detecting the **runtimeExecutable**

**Comment by joshtynjala** [comment]
Yeah, the fact that it's trying to use Flash Player instead of AIR is confusing me because your *asconfig.json* has multiple signals that it's an AIR app.

Can you zip up your project and email it to me? Send it to my GitHub username at Gmail. I think I need to see more of your files to figure this one out.

**Comment by rhett-thompson** [comment]
@joshtynjala I've sent it.

Thanks for the help man.

**Comment by joshtynjala** [comment]
@rhett-thompson I just realized what the issue is. In order to automatically detect that it should launch the AIR runtime (instead of Flash Player), the debugger expects your AIR descriptor XML file to follow a certain naming convention. It must either end with *-app.xml* or *application.xml*. Your file is named *astrozone.xml*, so it doesn't think that it's meant to be an AIR app. This is the code that Adobe wrote for detecting the correct runtime, so it's not something that the VSCode extension has control over, unfortunately.

If you rename the file to *astrozone-app.xml*, it should work without the runtimeExecutable field being set.

**Comment by rhett-thompson** [comment]
That did the trick.  I still have to explicitly set the content element in the descriptor; not a big deal by any means.

Thanks Josh.

P.S. Great work on this extension!  When there's code formatting, I don't see how this won't be the best "IDE" for AS3 AIR development.

**Comment by joshtynjala** [comment]
> I still have to explicitly set the content element in the descriptor

Confirmed. It seems that I didn't handle the case where `<content></content>` is empty. I'll get that fixed.

However, in the meantime, you can use something like this instead: `<content>[This value will be overwritten by Visual Studio Code]</content>`.

**Comment by joshtynjala** [comment]
I figured out how to change the debugger to allow *astrozone.xml*, so that won't be an issue in future versions!
