### ISSUE TITLE
Adobe AIR code signing password

### ISSUE THREAD

**Issue by ddorris** [BowlerHatLLC/vscode-nextgenas#243]
I have set up a VS Code Adobe AIR (desktop) project with this excellent extension, and have been following along with the awesome help in the Wiki.

I read "Package an Adobe AIR application in Visual Studio Code" and want to do the task:
**Adobe AIR package release Windows application (captive runtime)**

Everything seems to be configured correctly in my asconfig.json. In the appropriate place in my signingOptions, I reference the valid p12 signing certificate that we use all the time to build AIR native installers in Adobe Animate. (I didn't think that a captive runtime app even needed code signing since it doesn't make installers??)

---

It looks like it is going to work...
The task executes in the integrated terminal, writes my swf, and then prompts
**Adobe AIR code signing password:**

but doesn't actually let me type the password!

Am I missing something obvious?

---

I saw in another issue that you didn't want the p12 password to be stored in a plaintext file, which I understand. Even if I have to type it manually every time, I don't see a place to put the password.

If I can't get that working, I'll go down a rabbit hole of writing batch/shell scripts to run the ADT -package command with the p12 password, which sounds painful. Hopefully this package task is supported and there is just something simple I am missing. Thanks for your attention!

**Comment by joshtynjala** [comment]
> but doesn't actually let me type the password!
> Am I missing something obvious?

Just click inside the Terminal view where it asks you for the password (to be sure that it has focus) and start typing! I think that you may be confused because you **will not** see any new characters appear in the terminal while you type your password. That's how it works for many command line applications that accept a password.

**Comment by ddorris** [comment]
I love you Josh! That worked!
Feeling 100% silly for typing so much!

**Comment by joshtynjala** [comment]
> I didn't think that a captive runtime app even needed code signing since it doesn't make installers??

Windows and macOS expect all executables to be signed. Both apps and installers.

**Comment by joshtynjala** [comment]
> I love you Josh! That worked!
> Feeling 100% silly for typing so much!

Happy to help! 😄

**Comment by joshtynjala** [comment]
@ddorris I added a little tip [to this page in the wiki](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Package-an-Adobe-AIR-application-in-Visual-Studio-Code) about the password being hidden so that no one else has the same issue in the future!
