### ISSUE TITLE
Allow disabling compiler warnings in asconfig.json

### ISSUE THREAD

**Issue by hydroper** [BowlerHatLLC/vscode-nextgenas#244]
The issue title might be clear. Actually my `asconfig.json` passes

  * `-compiler.warn-assignment-within-conditional=false`
  * `-compiler.warn-duplicate-variable-def=false`

to the compiler, but the VSCode extension continues with over 100+ warnings. My solution for conditional assignment was to do `((assignment), result)` :/.

**Comment by joshtynjala** [comment]
This should start working correctly in the upcoming v0.13 update. Last week or so, I finally found the class that the compiler uses to automatically filter out errors/warnings based on the compiler options, like the ones that you mentioned.
