### ISSUE TITLE
Changes of an SWC file on the library-path aren't detected automatically 

### ISSUE THREAD

**Issue by olafkruger** [BowlerHatLLC/vscode-nextgenas#250]
Currently, changes of an swc file or a loaded module aren't detected.

To work around this issue, we can use commands like "Reload Window" or "Restart AS/MXML server" in order to detect changes.
 
It would be great to have an automatism which takes care of those changes!

**Comment by angelhdz** [comment]
I can confirm. 

Have to Reload Window when:
1- Every time I add a new library path or class path to add SWC libraries.
2- Every time I create a new AIR project with a document class (Main.as). I get error that Main.as is not in the source path (and all my projects' document class is in '/src'. Reload Window and the error goes away.

**Comment by joshtynjala** [comment]
@angelhdz Is there any chance that you could record a video/screencast of creating a new project so that I can see how you get that "Main.as is not in the source path" error? I've never encountered that one. Please open a new issue, if you're able to do that. Thanks!

**Comment by angelhdz** [comment]
@joshtynjala done and done. Thank you very much!
