### ISSUE TITLE
Unverified breakpoints

### ISSUE THREAD

**Issue by olafkruger** [BowlerHatLLC/vscode-nextgenas#251]
After the debugger is started all of the breakpoints (or sometimes all except the last in the list)  are turning from red to grey. Such a grey breakpoint is named as "unverified breakpoint".

Setting breakpoints at runtime always work (remains red). Reapplying breakpoints at runtime also works (all breakpoints turns to red) [1].

It turns out to me, that if there's no way to get a breakpoint red during runtime, it definitely won't work!
But vice versa an unverified breakpoint works as long as it could be reapplied.
But basically, there's no need to reapply breakpoints in order to get it to work.

[1] Reapplying breakpoints the simple way:
![image](https://user-images.githubusercontent.com/38468124/43573744-c2b3b2f0-9642-11e8-904c-b6dd708fc099.png)

**Comment by joshtynjala** [comment]
Last week, I tested a couple of my Feathers projects, but I did could not reproduce the unverified breakpoints. However, today, I saw some unverified breakpoints while I was debugging Moonshine.

Perhaps this is more likely to happen in Flex projects. I'll investigate further when I have some time.

**Comment by olafkruger** [comment]
Thanks for looking into this.
Just in order to make sure that the issue has nothing to do with linked libs or modules I tested a simple Flex/AIR one-file-application... and can still reproduce it [1].

This is from the VSCode Docs, maybe it is helpful:
>...
> When a debugging session starts, breakpoints that cannot be registered with the debugger change to a gray hollow circle. The same might happen if the source is edited while a debug session without 
> live-edit support is running.
> The **Reapply All Breakpoints** command sets all breakpoints again to their original location. This is helpful if your debug environment is "lazy" and "misplaces" breakpoints in source code that has not yet been executed.
...
(https://code.visualstudio.com/docs/editor/debugging#_breakpoints)

[1]
![image](https://user-images.githubusercontent.com/38468124/43758671-285b463a-9a1d-11e8-8d13-b4279cf38e98.png)
