### ISSUE TITLE
Add AS3 to the list of supported languages at langserver.org

### ISSUE THREAD

**Issue by olafkrueger** [BowlerHatLLC/vscode-nextgenas#252]
If I understand it correctly, this vscode-extension uses the "language server protocol" and AS3 should be part of the list at https://langserver.org [1].

If that's right, I could create a pull request at their repo [2].

Are all features already supported?
- Code completion
- Hover
- Jump to def
- Workspace symbols
- Find references
- Diagnostics

[1] Supported languages
![grafik](https://user-images.githubusercontent.com/14052170/43638382-e2d77676-9718-11e8-9a03-41c2ee8c6545.png)

[2] http://github.com/langserver/langserver.github.io

**Comment by joshtynjala** [comment]
> If that's right, I could create a pull request at their repo [2].

Yes, please feel free to add it to the list.

> Are all features already supported?
>
>    Code completion
>    Hover
>    Jump to def
>    Workspace symbols
>    Find references
>    Diagnostics

Yes, all of these features are supported.

**Comment by olafkrueger** [comment]
[Pull request](https://github.com/langserver/langserver.github.io/pull/110) is created.

**Comment by joshtynjala** [comment]
Thank you!

**Comment by olafkruger** [comment]
It's already online:

[langserver.org](http://langserver.org):
![image](https://user-images.githubusercontent.com/38468124/43714104-351a6302-997c-11e8-9835-2773fce42a00.png)
