### ISSUE TITLE
Auto Create AIR Project

### ISSUE THREAD

**Issue by angelhdz** [BowlerHatLLC/vscode-nextgenas#259]
Hello guys.

 I already achieved to add multiple folders into a single workspace and named it AIR Workspace. When I hit CNTRL + ENTER, then I can choose which project to debug/release. But only projects which I add the asconfig.json, .vscode>launch.json and .vscode >tasks.json to, appear in the drop down to be build for debug/release, so to fix that, I'd have to go folder by folder adding those files and setting them up.

So my question is, is there any way to just create an AIR Project and all those required files automatically get created, like in FlashDevelop? 

**FlashDevelop:**

1- Create Project
2- Select Project Type (Air Desktop Projector, Air Mobile APP, etc.)
3- All the neccesary files are created automatically for that project and the project it's ready to be build for debug/release.

Thank you!

**Comment by joshtynjala** [comment]
As I understand Microsoft's philosophy with Visual Studio Code, it tends to encourage you to manually create configuration files that you need... as you need them. They seem to treat VSCode slightly more as a text editor than an IDE, which involves more manual configuration. As I work on the AS3 & MXML extension, I try to look to how Microsoft implements similar features for their core languages supported by VSCode, including TypeScript and JavaScript. They don't have commands to automatically create *tsconfig.json*, *tasks.json*, and *launch.json* all in one step, so I don't do that either.

This is a perfect place for someone like @neminovno to come along and provide another extension for people who want a more IDE-like experience. One nice thing is that VSCode supports extension packs, so you can bundle the AS3 & MXML extension with others to create a single package that provides all the bells and whistles.

**Comment by angelhdz** [comment]
Wow this community is very active!

Thanks guys for responding so fast and for the solutions provided.

If nothing left to add, you can close this issue.

**Comment by neminovno** [comment]
@angelhdz AIR desktop app can be created using Flex/AS and only AS so that is why are those project names. Anyway, once I create new repo please create any issues you have. Last 30 days I was offline most of the time. First I need to catch up with all the work that @joshtynjala has done. 

For fast project creation, idea is to have menu item on right click in explorer menu like this:

![image](https://user-images.githubusercontent.com/1468887/44721579-ac8f7a80-aaca-11e8-8b63-5299284d170e.png)

**Comment by angelhdz** [comment]
I Wanna thank you @neminovno . Still using your extension to create AS projects. 

Cheers!
