### ISSUE TITLE
Problem with tasks.json ?

### ISSUE THREAD

**Issue by JimmyGot** [BowlerHatLLC/vscode-nextgenas#26]
tasks.json: version 0.2.0: "Value is not an accepted value. Valid values: ["0.1.0"]

**Comment by joshtynjala** [comment]
Where did you get the version 0.2.0 from?

The tasks.json generated by the "Tasks: Configure Task Runner (ActionScript - asconfig.json)" command contains version 0.1.0.

The wiki page about tasks.json also contains version 0.1.0: https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Create-tasks.json-to-compile-an-ActionScript-project

Is there another example where you might have found that version instead?

**Comment by JimmyGot** [comment]
My mistake. I thought it should be 0.2.0 because of the NextGenAS version number.

**Comment by joshtynjala** [comment]
Nope! That's version is part of the tasks.json file format.
