### ISSUE TITLE
Opening debug window when compiling, not the Output window

### ISSUE THREAD

**Issue by angelhdz** [BowlerHatLLC/vscode-nextgenas#260]
Hello guys! 

I've been struggling to get the debug tab to open automatically when compiling (CNTRL + ENTER) because all my trace() calls are going there. Instead, the Output tab is opened.

I managed to get it to work in AIR Mobile by setting "console": "none", but when I'm debugging an AIR Desktop application I got an error: "console" property is not allowed.

I think this is the last thing I need to finally start building my applications in VS Code with the nextgenactionscript extension and make the jump from FlashDevelop. 

Thank you!

**Comment by angelhdz** [comment]
That's it! :)

I tried "internalConsoleOptions" but only set it to "neverOpen" thinking it was the Output window. 
"openOnSessionStart" is the one.

Thank you again @joshtynjala !

**Comment by joshtynjala** [comment]
I'm happy to help!
