### ISSUE TITLE
In MXML bindings not shown current info in code intelligence

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#268]
Hi,

I was writing in MXML something like this:

`<js:FontIcon text="{MaterialIconType.MENU}" material="true"/>`

And found that hitting CTRL+SPACE after "{MaterialIconType." does not show the list of possible icons constants. I tried the same for Jewel Alert.YES (other class in other package)

for example, doing this inside a <fx:Script> pulls correctly this list, so this seems to me a problem with bindings only.

Thanks

**Comment by joshtynjala** [comment]
Duplicate #53.

I have this feature implemented, but I cannot enable it until the next release of Royale because the correct version of the compiler has some bugs.
