### ISSUE TITLE
No snippet support for ActionScript embedded in MXML

### ISSUE THREAD

**Issue by GotJimmy** [BowlerHatLLC/vscode-nextgenas#27]
Maybe that's just not been implemented yet but I cannot insert snippets in *.mxml files (neither in the MXML nor the Script section). Works fine in *.as files.

**Comment by joshtynjala** [comment]
The extension doesn't provide any snippets at all. If you're getting any in *.as files, it must be from another extension.

**Comment by JimmyGot** [comment]
I wrote a few snippets myself. See "Preferences: Open User Snippets" and then "NextGen ActionScript". Just saw that there's also a section for MXML. Haven't tried that yet, but what about the Script section in MXML files? Will keep you posted.

**Comment by joshtynjala** [comment]
I haven't found a good way for VSCode to know that the Script element in MXML contains ActionScript. I thought I found some undocumented hooks that Microsoft uses for CSS and JavaScript inside HTML, but when I tried it out with MXML and ActionScript, I wasn't successful. I'm hoping to try again when I find some time.

**Comment by JimmyGot** [comment]
I added some snippets to the Snippets | MXML section:  works fine all over the *.mxml files (including the Script section), but not in *.as.
OTOH, the Snippets | NextGenAS work in *.as but not in *.mxml.

**Comment by JimmyGot** [comment]
OK, simple workaround for the snippets is to have the AS3 snippets in both the NextGenAS and MXML snippets files, while MXML snippets only in the MXML snippet file.

**Comment by joshtynjala** [comment]
The fix for #31 does not appear to help with snippets for ActionScript in <fx:Script> elements. I suspect that VSCode does not currently know how to expose snippets to embedded languages.

**Comment by JimmyGot** [comment]
I know that this fix will give me AS3 snippets in the MXML section, and MXML snippets in the Script section, but that's still better than not having any snippets at all.

**Comment by joshtynjala** [comment]
Closing because ActionScript snippets in MXML `<fx:Script>` elements appears to be working correctly now!
