### ISSUE TITLE
launch air desktop not work

### ISSUE THREAD

**Issue by matrix3d** [BowlerHatLLC/vscode-nextgenas#272]
ctrl + enter
open a windows, and close the windows

**Comment by Hakunametata** [comment]
> This usually indicates an issue with the XML namespace in your AIR application descriptor, or with the `swf-version` used to compile your SWF.
> 
> For example, the SWF version for AIR 30 is 41. If the XML namespace is 30.0, but the SWF version is 42, the app will crash on startup.
how to find out that which version of my swf player is?
