### ISSUE TITLE
entity nbsp in MXML not recognized throwing error

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#274]
Hi Josh, 

I added to royale compiler **&nbsp;** entity to take into account in MXML.

Today updated to latest snapshot and this line of code in MXML:

`<j:Label width="120" multiline="true" html="Some&nbsp;text">`

and extension is reporting the following error:

`Unknown entity '{entity}' found. It will be ignored.`

**Comment by joshtynjala** [comment]
I remember you recently built the extension from source. If you update to my latest changes from yesterday, it will be `as3mxml.sdk.editor` instead.

**Comment by carlosrovira** [comment]
Right, I built SNAPSHOT before posting this issue with latest changes from yesterday and this problem started to show. Maybe I must perform some clean of a cache or something? thanks

**Comment by carlosrovira** [comment]
I'm seeing the new var  `as3mxml.sdk.editor`

**Comment by joshtynjala** [comment]
Using the be compiler should work automatically once you change the setting. If not, then restarting VSCode is enough to fix it. If you still get the error after, then I suspect that you might have more work to do in the compiler.

**Comment by carlosrovira** [comment]
Hi Josh,

in MXMLDialect.java line 101 is the inclusion of the new entity (nbsp) along with the other 5 we have declared. I don't see other references to NAMED_ENTITY_MAP. This error started to show we the latest changes in the extension (when I made the change, and build the compiler, all was working ok with latest snapshot I built from vscode), maybe some latest change could bring this error? or is less probable this scenario
thanks

**Comment by joshtynjala** [comment]
I guess it's also that you've set the wrong path to the SDK. It will fall back to the bundled compiler if it can't find a valid SDK at that path.

Last time I checked, Maven SDKs will work fine.

**Comment by joshtynjala** [comment]
FYI, I'm going on vacation for my wedding anniversary, so I won't be able to help more until next week. Let me know if you figure it out in the meantime.

**Comment by joshtynjala** [comment]
I took a few moments to try this out. I confirm that the error appears when the bundled compiler is used for code intelligence, but it disappears when `as3mxml.sdk.editor` is set to a nightly SDK build.

I see that there is a bug in the Royale compiler, though:

> Unknown entity '{entity}' found. It will be ignored.

The `{entity}` token in this error message is not being replaced with the actual entity. If someone were to try using `&unknown;`, it should say this instead:

> Unknown entity '&unknown;' found. It will be ignored.

**Comment by carlosrovira** [comment]
Thanks Josh to look into this. 
I'll try to find how to fix the "entity" in the compiler.

**Comment by carlosrovira** [comment]
Hi Josh, 
I fixed this, there was a missing $ in the entity token
