### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by jcrawford** [BowlerHatLLC/vscode-nextgenas#276]
I have set everything up as your instructions state to.  However when I attempt to build I am getting the following error:

```
The terminal process terminated with exit code: 2

Terminal will be reused by tasks, press any key to close it.
```

Under the Problems tab I see this

```
A fatal error occurred. Error checking has been disabled, except for simple syntax problems.
```

asconfig.json
```
{
	"config": "flex",
	"compilerOptions": {
		"output": "bin/manufacturer.swf"
	},
	"files":
	[
		"./manufacturer.mxml"
	]
}
```

settings
```
"nextgenas.java": "/usr/local/bin/java",
"nextgenas.sdk.framework": "/Applications/Adobe Flash Builder 4.7/sdks/3.6.0"
```

Any assistance would be appreciated as I cannot seem to get Flash Builder to run without locking up on my system so it is completely unusable.  I would love for the ability to build using vs-code

Building the project works fine in Flash Builder, however editing files in Flash Builder leads to the application hanging so currently I am editing in VSCode and building in Flash Builder, would be nice to get this to work in VSCode so I could just blow away Flash Builder.

**Comment by neminovno** [comment]
Is it error after running adt ? if yes, error 2 description is:

_2 | Usage error | Check the command-line arguments for errors_

Check Terminal lines when running build.

**Comment by joshtynjala** [comment]
Could you try moving the source code, like *manufacturer.mxml*, into a sub-folder like *src*? Maybe it doesn't like your code in the root folder like that.

**Comment by jcrawford** [comment]
Unfortunately the project is rather large and poorly coded by a previous developer it would take quite a bit of effort to do what you requested.  Is it possible to provide the path somewhere so that it knows to check the root project and not /src?

**Comment by joshtynjala** [comment]
You could try adding "." to the `source-path` compiler option. I don't know if it will work for sure, but it's worth a try.

You should also double check that *asconfig.json* is in the root and not somewhere like *.vscode/*. Sometimes, people accidentally put it there.

**Comment by joshtynjala** [comment]
The *.mxml file with `<s:Application>` or `<mx:Application>` at its root is your main class. That's the file that you want to put into the `files` section of *asconfig.json*.

**Comment by jcrawford** [comment]
Perfect that is what I was thinking and that is how I have it setup.  I cannot seem to figure out how to see the actual build command in Flash Builder since there is no terminal component and trying to install one has proven to be difficult since the adobe repo cannot be read.  I am guessing because it is not supported software anymore.

Any other ideas how I can either see more errors or how I can get this to compile through using vscode?

**Comment by jcrawford** [comment]
Ahhh so I went through all the warning output and saw one specific Error line: `Error: unable to resolve 'images/import_export_outlook.gif' for transcoding` I fixed the path to this and building is now working properly :)

Thanks for all of your assistance on this issue.

**Comment by joshtynjala** [comment]
If you ever want to see exactly whwich compiler options Flash Builder is using, you can add the `dump-config` compiler option. It will create a config file that can even be passed to the command line compiler with `load-config`.

`-dump-config=my-dumped-config.xml`

**Comment by jcrawford** [comment]
out of curiosity is there anyway to make your plugin open the html page for the build in the browser automatically?

**Comment by joshtynjala** [comment]
See the **
Build automatically before debugging** section in [Debug a SWF embedded in HTML with Visual Studio Code](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Debug-a-SWF-embedded-in-HTML-with-Visual-Studio-Code). It's kind of the opposite idea. You tell VSCode to debug (which launches the HTML file in the browser), but `preLuanchTask` tells it will build first.

**Comment by jcrawford** [comment]
The only issue i am seeing with that is I get the following error

```
User defined identifiers are deprecated. For custom task used the name as a reference and for tasks provided by extensions use their defined task identifier.
```

**Comment by joshtynjala** [comment]
I'm not seeing that error in VSCode 1.27.2. Strange!

**Comment by jcrawford** [comment]
ah I am using insiders so that might be why.  it may be something that is coming soon.

**Comment by joshtynjala** [comment]
Yeah, it's probably a change in Insider's. It sounds like they're going to let me define an identifier in the extension that you can reference in *launch.json* without also adding it to *tasks.json* manually. That should be a good improvement!

**Comment by jcrawford** [comment]
I assume there is no way to launch a debug without hitting the green arrow?  I would like to hit something like Command+Shift+B (or D) and just have it build and open.  Currently I have to click the green arrow and it will build and open but it requires an extra click after hitting Command+Shift+D

**Comment by jcrawford** [comment]
I will have to look into how to use F5 as fn-F5 does not appear to work and if I click F5 it dims my backlit keyboard on mac.

If I run your quick debugger builds then it compiles once and then runs the compile again and debugs so it does open but it requires 2 compiles.

**Comment by joshtynjala** [comment]
You need to remove the preLaunchTask when using the quick compile & debug.

**Comment by jcrawford** [comment]
I should have mentioned that I tried that, all that happens is that it builds the project but does not launch in the browser.

**Comment by jcrawford** [comment]
What I have found is that if I close Code and then reopen it and run the Quick Compile it does in-fact compile and open a browser tab for me.  However when I close that tab and run quick compile a second time it does not open in the browser.
