### ISSUE TITLE
Wiki: Wrong example in "runtimeExecutable" property

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-nextgenas#280]
Hello Josh,

Just a minor documentation issue in https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/launch.json-fields-for-SWF-debugging#runtimeexecutable.

The "runtimeExecutable" property section shows the "program" example.

Best,
Aurélien

**Comment by joshtynjala** [comment]
Thanks!
