### ISSUE TITLE
trying to code-intellisense for a custom library

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#282]
Hi Josh,

I linked a library project to a Royale App project, and of course classes in that library are not recognized in VSCode. I'm trying to wire the configuration to get code intelligence for this custom library, but don't know how to do it. I as well read all the wiki, and see some points that could be valid but I don0t get it to work. Hope you can give some clues on how to do this.

Thanks!

Carlos

**Comment by joshtynjala** [comment]
You can add the built SWC file to the app project's `library-path`.

**Comment by joshtynjala** [comment]
If you don't want to build the library project every time that you make a change, you can add its source folder to the app's `source-path` instead.

**Comment by carlosrovira** [comment]
Thanks Josh,
that worked:

```
"source-path": [
            "/Users/... ...../royale/royalelibs/royaledto/src/main/royale/"
        ]
```
I was missing the last main/royale.
