### ISSUE TITLE
Generate getter/setter broken in repo

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#283]
Hi Josh
just let you know that just built VSCode from sources and found that generation of getter/setter is not working. Going back to 0.14.1 fixes the issue.
thanks

**Comment by joshtynjala** [comment]
Thanks. I'm in the middle of refactoring code actions, and I have not completed everything yet, so things may be a little unstable this week.

**Comment by carlosrovira** [comment]
ok, cool! :)
