### ISSUE TITLE
Problem compiling on Windows 7

### ISSUE THREAD

**Issue by amcoho** [BowlerHatLLC/vscode-nextgenas#285]
I receive the following error when I try to compile a project I have inherited. Same project compiles on Mac using your extension without problems: 

```
> Executing task: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe -jar c:\Users\xxxx\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.14.1\bin\asconfigc.jar --sdk c:\flex_sdk_3.6a --debug=true --project c:\Users\xxxx\projects\project.Flexv1.vscode\asconfig.json <

Loading configuration file C:\flex_sdk_3.6a\frameworks\flex-config.xml
C:\Users\xxxx\projects\project.Flexv1.vscode\manufacturer\scorecard.mxml(206):  Error: Type was not found or was
not a compile-time constant: HitData.

                        private function fmtDataTip( item:HitData ):String {

The terminal process terminated with exit code: 1
```

Below is my asconfig.json:
```
{
	"config": "flex",
	"compilerOptions": {
		"output": "bin/manufacturer.swf",
		"source-path": [
			"."
		]
	},
	"files":
	[
		"./manufacturer.mxml"
	]
}
```
Note that the source files are located in the root of the project and so is manufacturer.xml. I wonder if on Windows source-path cannot be specified in this way.

**Comment by amcoho** [comment]
Here is the code in scorecard.mxml. Line 206 is where private function fmtDataTip is declared. Note how import statement is right above it in the same block.

```
	<mx:Script>
		<![CDATA[
      ...
    
      import mx.charts.HitData;

      ...
      
			private function fmtDataTip( item:HitData ):String {
				var s:String;
				var bSI:BarSeriesItem = item.chartItem as BarSeriesItem;           
				
				s = "<b>" +Series(item.element).displayName + "</b><br />" +" => "  +bSI.xValue ;
				return s;
			}
```

**Comment by joshtynjala** [comment]
I'm guessing that it's not an issue with the extension, but some difference between the SDKs that you are using to compile the project. Are you using the exact same version of the Flex SDK on both platforms? I see that you're compiling with Adobe Flex 3.6A on Windows. Is that the same version of the SDK that you're using on Mac?

It's worth mentioning that the Adobe Flex data visualization components (including charts) used to be a premium feature that required an extra compiler option to unlock. Depending on which version of the Flex SDK you are using, this may or may not be necessary.

**Comment by amcoho** [comment]
Thanks for the hint. Indeed the visualization components where not part of 3.6 SDK. I had to download Adobe Flex 3.6 Data Visualization Components for Flex Builder separately from https://www.adobe.com/devnet/flex/flex-sdk-download.html and then grab the following two files from it and move them to their corresponding locations in 3.6 SDK:

/frameworks/libs/datavisualization.swc
/frameworks/locale/en_US/datavisualization_rb.swc

For some unknown reason the files were present in the 3.6 SDK folder on Mac that's why it compiled there.

Thanks again.

**Comment by joshtynjala** [comment]
Happy to help!
