### ISSUE TITLE
Building only builds swf not html files

### ISSUE THREAD

**Issue by jcrawford** [BowlerHatLLC/vscode-nextgenas#286]
I have had this working for a while now and I am guessing that is because when I converted to VSCode from FlashBuilder that the `bin/` folder already had everything previously built.  However, when I removed all files from the `bin/` folder and tried building with VSCode I received only the swf file.  It did not build the html file from the mxml file.  It also is only building the manufacturer.swf and not any of the others.  It appears that flash builder copies the main directory over into bin while also building out files that it needs to.  I need to try to get VSCode to replicate this so that the `bin/` folder is the same as that from Flash Builder.

```
ls -la bin
total 4112
drwxr-xr-x@  3 jcrawford  staff       96 Oct  9 09:28 .
drwxr-xr-x@ 33 jcrawford  staff     1056 Oct  9 09:27 ..
-rw-r--r--@  1 jcrawford  staff  1305217 Oct  9 09:28 manufacturer.swf
```

```
ls -la bin-old
total 16240
drwxr-xr-x@  26 jcrawford  staff      832 Oct  1 15:20 .
drwxr-xr-x@  33 jcrawford  staff     1056 Oct  9 09:27 ..
-rw-r--r--    1 jcrawford  staff     6148 Oct  1 15:19 .DS_Store
-rwxr-xr-x@   1 jcrawford  staff      831 Sep 13 13:59 .fxpProperties
drwxr-xr-x@  15 jcrawford  staff      480 Sep 19 10:52 .git
-rw-r--r--@   1 jcrawford  staff       23 Sep 17 09:48 .gitignore
drwxr-xr-x@   4 jcrawford  staff      128 Sep 17 10:28 .vscode
-rwxr-xr-x@   1 jcrawford  staff     8349 Sep 17 10:28 AC_OETags.js
-rw-r--r--@   1 jcrawford  staff      787 Sep 14 07:45 README.md
-rw-r--r--@   1 jcrawford  staff      154 Sep 17 10:14 asconfig.json
drwxr-xr-x@  20 jcrawford  staff      640 Sep 17 10:28 bin-release
-rw-r--r--@   1 jcrawford  staff     4308 Sep 17 10:28 consumer.html
-rw-r--r--@   1 jcrawford  staff     4335 Sep 17 10:28 distributor.html
-rw-r--r--@   1 jcrawford  staff  1807192 Sep 17 10:28 distributor.swf
-rw-r--r--@   1 jcrawford  staff     4326 Sep 17 10:28 government.html
-rw-r--r--@   1 jcrawford  staff  1043062 Sep 17 10:28 government.swf
drwxr-xr-x@   5 jcrawford  staff      160 Sep 14 07:46 history
drwxr-xr-x@ 161 jcrawford  staff     5152 Sep 17 10:28 images
drwxr-xr-x@   3 jcrawford  staff       96 Sep 17 10:24 include
-rw-r--r--@   1 jcrawford  staff     4344 Sep 17 10:28 manufacturer.html
-rw-r--r--@   1 jcrawford  staff  1305216 Oct  9 09:26 manufacturer.swf
-rwxr-xr-x@   1 jcrawford  staff      657 Sep 17 10:28 playerProductInstall.swf
-rw-r--r--@   1 jcrawford  staff     4308 Sep 17 10:28 retailer.html
-rw-r--r--@   1 jcrawford  staff  1165159 Sep 17 10:28 retailer.swf
drwxr-xr-x@  45 jcrawford  staff     1440 Sep 17 10:28 uploads
```

As you can see there are MANY more files in the old `bin/` directory, how can I get VSCode to compile all of these as FlashBuilder did?

This is what our project directory looks like

```
ls -la
total 216
drwxr-xr-x@  33 jcrawford  staff   1056 Oct  9 09:27 .
drwxrwxrwx@  20 jcrawford  staff    640 Oct  8 10:41 ..
-rw-r--r--@   1 jcrawford  staff  10244 Oct  1 15:19 .DS_Store
-rwxr-xr-x@   1 jcrawford  staff   1805 Sep 13 14:05 .actionScriptProperties
-rwxr-xr-x@   1 jcrawford  staff    241 Sep 13 14:05 .flexProperties
-rwxr-xr-x@   1 jcrawford  staff    831 Sep 13 13:59 .fxpProperties
drwxr-xr-x@  15 jcrawford  staff    480 Oct  9 09:31 .git
-rw-r--r--@   1 jcrawford  staff     29 Oct  1 15:35 .gitignore
drwxr-xr-x@   8 jcrawford  staff    256 Sep 19 10:52 .idea
-rwxr-xr-x@   1 jcrawford  staff    451 Sep 13 14:05 .project
drwxr-xr-x@   4 jcrawford  staff    128 Sep 13 14:05 .settings
drwxr-xr-x@   5 jcrawford  staff    160 Sep 17 11:39 .vscode
-rw-r--r--@   1 jcrawford  staff   4282 Oct  8 09:38 README.md
-rw-r--r--@   1 jcrawford  staff    154 Sep 18 09:14 asconfig.json
drwxr-xr-x@   3 jcrawford  staff     96 Oct  9 09:28 bin
drwxr-xr-x@  26 jcrawford  staff    832 Oct  1 15:20 bin-old
drwxr-xr-x@  20 jcrawford  staff    640 Sep 17 11:32 bin-release
drwxr-xr-x@  66 jcrawford  staff   2112 Sep 18 09:14 components
drwxr-xr-x@   9 jcrawford  staff    288 Sep 13 14:00 consumer
-rwxr-xr-x@   1 jcrawford  staff   8954 Sep 13 13:59 consumer.mxml
drwxr-xr-x@  11 jcrawford  staff    352 Sep 13 14:01 distributor
-rwxr-xr-x@   1 jcrawford  staff  11016 Sep 13 13:59 distributor.mxml
drwxr-xr-x@   8 jcrawford  staff    256 Sep 13 14:00 government
-rwxr-xr-x@   1 jcrawford  staff   6690 Sep 13 13:59 government.mxml
drwxr-xr-x@   6 jcrawford  staff    192 Sep 13 14:01 html-template
drwxr-xr-x@ 161 jcrawford  staff   5152 Sep 13 14:01 images
drwxr-xr-x@   9 jcrawford  staff    288 Oct  5 16:15 include
drwxr-xr-x@  24 jcrawford  staff    768 Sep 13 14:01 manufacturer
-rw-r--r--@   1 jcrawford  staff  17872 Oct  5 16:15 manufacturer.mxml
drwxr-xr-x@   8 jcrawford  staff    256 Sep 13 14:01 retailer
-rwxr-xr-x@   1 jcrawford  staff   8941 Sep 13 13:59 retailer.mxml
drwxr-xr-x@   3 jcrawford  staff     96 Sep 13 14:00 skins
drwxr-xr-x@  45 jcrawford  staff   1440 Sep 13 14:00 uploads
```

**Comment by joshtynjala** [comment]
HTML files are not generated from MXML. MXML is more like an ActionScript class, and it gets compiler into the SWF. If i had to guess, the HTML files come from your *html-template* folder. The VSCode extension currently doesn't process *html-template*, though. That's a feature that would be to be added.

The [`copySourcePathAssets`](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/asconfig.json#copysourcepathassets) field in *asconfig.json* can be used to copy any files that are in the source path that don't have *.as* or *.mxml* file extensions to your output folder. However, it looks like you don't have a dedicated source folder (often named *src*), so this might not work for your project unless you reorganize a little bit.

**Comment by jcrawford** [comment]
I have checked the html-template folder and all other folders there is no such manufacturer.html nor retailer.html anywhere in the project so they are being built from somewhere, maybe that is something flashbuilder does automatically?

```
mdfind -name manufacturer.html
/Users/Shared/Dropbox/Work/RecallInfoLink/FlexV1/bin/manufacturer.html
```

I will look into the copySourcePathAssets to see if I can get that to work, thanks for that tip.

**Comment by joshtynjala** [comment]
> any idea if/when this feature could be incorporated into this plugin, it is a hard requirement for us to have these files generated.

I can take a look, but no promises.

> Also any idea how I would get it to build multiple mxml at one time? I tried to add more to the files array in asconfig.json however it complained about multiple sources.

The VSCode extension was designed with one SWF per project in mind. You may need to separate it into multiple projects.

However, the most recent update includes a feature that may allow you to keep a single project. The extension now allows you to create multiple *asconfig.json* files. The idea was to allow you to have different settings for different types of builds. For instance, you might want different compiler options for debug and release builds. However, this could potentially be used for building multiple SWFs too.

You can add an extra string in the middle of the filename, so you might create *asconfig.retailer.json* and *asconfig.government.json*, for instance. The extension will provide separate build tasks for each *asconfig.json* file, so this will allow you to build multiple SWFs. Additionally, as I understand it, Visual Studio Code allows you to optionally specify dependencies when you define a task in *tasks.json*. You should be able to use that to build all SWFs with one build command.

**Comment by joshtynjala** [comment]
> any idea if/when this feature could be incorporated into this plugin, it is a hard requirement for us to have these files generated.

The next update to the extension will include a new `htmlTemplate` field in *asconfig.json*. You will be able to pass in the path to your *html-template* folder and it will copy the files to your *bin* folder and populate all of the tokens, like Flash Builder does.

**Comment by jcrawford** [comment]
This is awesome to hear, thank you very much!

**Comment by jcrawford** [comment]
@joshtynjala One thing I noticed with the new build with the htmlTemplate addition is that it is not adhering to the background colors set.  When built with Flash Builder it does use the correct background color, when built with vscode it uses a white background color.  

If you go here the one on the left side was built with Flash Builder and the one on the right built with vscode.  If you scroll down you will see the color code differences.  Is this a bug or do I need to do something in vscode to get it to use the proper configured colors?

https://www.diffchecker.com/BkUhKlpa

**Comment by joshtynjala** [comment]
You need to define the `default-background-color` compiler option. It was previously missing in `compilerOptions` in older versions, but I added it in the new version. The color will not be detected if you defined it in `additionalOptions`.

**Comment by jcrawford** [comment]
Ok Thank You! I assume Flash Builder was picking up on this configuration from somewhere else, however adding it to my compilerOptions in asconfig has done the trick.  Is there anything else like this that I would need to define in asconfig that Flash Builder may be picking up on that vscode is not?

**Comment by joshtynjala** [comment]
* `default-background-color` populates `${bgcolor}`
* `default-size` populates `${width}` and `${height}`
* `target-player` populates `${version_major}`, `${version_minor}`, and `${version_revision}`
* `output` populates `${swf}`
* The name of your main class populates `${application}`

**Comment by jcrawford** [comment]
excellent thank you for that information.  I will be sure to add the ones we require.

**Comment by jcrawford** [comment]
Do you have an example file, I would like to see how the target-player is setup, do I just do something like this?

```
target-player: {
  version_major: 9,
  version_minor: 0
  version_revision: 124
}
```

**Comment by joshtynjala** [comment]
https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/asconfig.json#target-player

**Comment by jcrawford** [comment]
thanks

**Comment by jcrawford** [comment]
so would that be `"target-player": "9.0.124"` in my case?

**Comment by joshtynjala** [comment]
That's actually the default version used when you omit `target-player`, but yes, it would be fine to define it explicitly.

**Comment by jcrawford** [comment]
ok if it is the default version then I will probably leave it out, however when I tried to do 9.0.124 it complained that it didn't match the required regular expression so I am not sure it's possible to do it like that.
<img width="696" alt="screen shot 2018-10-31 at 10 24 27 am" src="https://user-images.githubusercontent.com/875341/47794605-2b857700-dcf7-11e8-8896-ae1222fd5ce9.png">

**Comment by joshtynjala** [comment]
Oh! I've confirmed that's a bug. I guess you'll need to use "9.0" until that gets fixed.

**Comment by jcrawford** [comment]
For the time being I plan to leave it out as the versions are the same between Flash Builder and VSCode.  If that changes in the future and things break that is when I will put this into the asconfig.json.

Thanks for all your work on this project!

**Comment by jcrawford** [comment]
@joshtynjala do you have a sample of how I would have to modify tasks.json to make it build all projects at one time rather than having to build them individually?

**Comment by jcrawford** [comment]
Also when I renamed asconfig.json to asconfig.manufacturer.json I now get this error when trying to build.

<img width="472" alt="screen shot 2019-01-15 at 4 21 34 pm" src="https://user-images.githubusercontent.com/875341/51210816-b5e67b80-18e1-11e9-8421-3d72bf1c6825.png">

**Comment by joshtynjala** [comment]
> do you have a sample of how I would have to modify tasks.json to make it build all projects at one time rather than having to build them individually?

You can create a new task that runs multiple task by using the dependsOn field:

https://code.visualstudio.com/docs/editor/tasks#_compound-tasks

> Also when I renamed asconfig.json to asconfig.manufacturer.json I now get this error when trying to build.

You still need at least one file that is named asconfig.json. That's the "main" one that VSCode uses to provide code intelligence.

**Comment by jcrawford** [comment]
Will I need to modify my tasks.json?  The link you provided looks more like my launch.json.

tasks.json
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "identifier": "build-debug",
            "type": "actionscript",
            "debug": false,
            "problemMatcher": [
                "$nextgenas_nomatch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]

```

launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch Manufacturer",
            "program": "bin/manufacturer.html",
            "preLaunchTask": "build-debug",
            "runtimeExecutable": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        },
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch Retailer",
            "program": "bin/retailer.html",
            "preLaunchTask": "build-debug",
            "runtimeExecutable": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        }
    ]
}
```

**Comment by joshtynjala** [comment]
Yes, you'll need to do it in tasks.json. I'm not sure what resembles launch.json in the link, but it's definitely all about tasks.json on that page.

**Comment by jcrawford** [comment]
@joshtynjala so I am trying to just get different build menu options for the Retailer, Manufacturer and I have modified my launch.json as seen above.  However when I launch Retailer it is still building manufacturer.  Do I need to modify my tasks.json for this if I am not going to use the dependsOn abilities?  If I do could you show an example as my current tasks.json (as seen above) does not have a command that is executed or anything that resembles manufacturer.  I also noticed it was not picking up on the asconfig.retailer.json and using the main asconfig.json file.

**Comment by joshtynjala** [comment]
"preLaunchTask": "asconfigc: asconfig.manufacturer.json"

**Comment by joshtynjala** [comment]
Depending on which SWF you want to debug, you need to choose the appropriate `preLaunchTask`. Right now, you're telling it to build using the task you defined in *tasks.json*, which uses the default *asconfig.json*.

I believe that this updated *launch.json* should work for your needs:

``` jsonc
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch Manufacturer",
            "program": "bin/manufacturer.html",
            "preLaunchTask": "ActionScript: compile debug - asconfig.manufacturer.json",
            "runtimeExecutable": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        },
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch Retailer",
            "program": "bin/retailer.html",
            "preLaunchTask": "ActionScript: compile debug - asconfig.retailer.json",
            "runtimeExecutable": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        }
    ]
}
```

If you're wondering where I got those task names, go to the **Terminal** menu and choose **Run Task**. It will give you the names of the built-in tasks that the VSCode extension provides. You can use those names in the `preLaunchTask` field of *launch.json*.

**Comment by jcrawford** [comment]
With this modified launch.json does that mean that the tasks.json is no longer required since the launch.json is not referencing a task from that file?

**Comment by joshtynjala** [comment]
Yeah, you can probably remove *tasks.json* after these changes to *launch.json*.

**Comment by jcrawford** [comment]
thank you for the assistance all seems to be working fine now!  However with these being in the launch.json and not in tasks.json there would not be a way to build all at once with the dependsOn bit correct?  is there no way to put the asconfig bit in the task itself rather than in the launch?

**Comment by jcrawford** [comment]
So an oddity on my end, I have this in my tasks.json

```
{
            "label": "Build All",
            "identifier": "build-all",
            "dependsOn": ["Build Manufacturer", "Build Retailer", "Build Consumer", "Build Distributor", "Build Government"]
        }
```

It seems to build all except for Manufacturer.  I can build manufacturer alone by using the debug just not through dependsOn.  This is the one that is using asconfig.json, would that lead to the problem?

**Comment by joshtynjala** [comment]
No, that shouldn't matter.

Maybe you forgot the label for the manufacturer task. Or maybe it's a conflict because you have both label and identifier defined. There's probably just a field missing (or with the incorrect value) somewhere in *tasks.json*.

**Comment by jcrawford** [comment]
i have both label and identifier defined for all of them

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build Manufacturer",
            "identifier": "build-manufacturer",
            "type": "actionscript",
            "asconfig": "asconfig.json",
            "debug": false,
            "problemMatcher": [
                "$nextgenas_nomatch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Build Retailer",
            "identifier": "build-retailer",
            "type": "actionscript",
            "asconfig": "asconfig.retailer.json",
            "debug": false,
            "problemMatcher": [
                "$nextgenas_nomatch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Build Consumer",
            "identifier": "build-consumer",
            "type": "actionscript",
            "asconfig": "asconfig.consumer.json",
            "debug": false,
            "problemMatcher": [
                "$nextgenas_nomatch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Build Distributor",
            "identifier": "build-distributor",
            "type": "actionscript",
            "asconfig": "asconfig.distributor.json",
            "debug": false,
            "problemMatcher": [
                "$nextgenas_nomatch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Build Government",
            "identifier": "build-government",
            "type": "actionscript",
            "asconfig": "asconfig.government.json",
            "debug": false,
            "problemMatcher": [
                "$nextgenas_nomatch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Build All",
            "identifier": "build-all",
            "dependsOn": ["Build Manufacturer", "Build Retailer", "Build Consumer", "Build Distributor", "Build Government"]
        }

    ]
}
```

**Comment by joshtynjala** [comment]
> "asconfig": "asconfig.json"

Remove this line from the "Build Manufacturer" task, and it should work.

You should only use the `asconfig` field when you're referencing anything **except** *asconfig.json*. For some reason, VSCode is super strict about *tasks.json*, so the fields need to be defined in an exact way, and I could not allow you to reference *asconfig.json* specifically without breaking backwards compatibility. It's super annoying because I knew that someone would eventually run into this issue.

**Comment by jcrawford** [comment]
Thanks that did the trick 👍
