### ISSUE TITLE
Add catalogs(manifest files) in custom libraries to get code-intellisense

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#288]
Hi Josh,

When adding a custom library with a custom manifest.xml this is not considered by VSCode, just the ones in the SDK. I suppose this applies to all SDKs (Royale, Flex...).

Could you add the capability to the plugin to add existing catalogs in custom SWCs to the extension in order to get code-intelligence for custom libraries?

thanks in advance

**Comment by joshtynjala** [comment]
I cannot reproduce this issue. I added a SWC file built with a manifest.xml to a Flex project, and the components correctly showed up in the completion list when I tried to use them in MXML. Additionally, the XML namespace for the SWC was correctly detected.

There must be something wrong with your SWC file.

**Comment by carlosrovira** [comment]
Hi Josh,
can be something related only to Royale? I can send you offline a test library project that shows the problem if you want. I'm getting the components in the completion list but not with an URI (i.e: xmlns:j="library://ns.apache.org/royale/jewel"), but a package (i.e: xmlns:jewel="org.apache.royale.jewel.*")
thanks
