### ISSUE TITLE
Breakpoints in MXML files

### ISSUE THREAD

**Issue by GotJimmy** [BowlerHatLLC/vscode-nextgenas#29]
Cannot set a breakpoint anywhere in an MXML file (not even in the Script section).

**Comment by joshtynjala** [comment]
Yeah, the compiler doesn't generate source maps for MXML yet.

https://issues.apache.org/jira/browse/FLEX-35186

**Comment by JimmyGot** [comment]
The FlexJS compiler? What about mxmlc for Flex 4.6 (because that's what I'm using on this project)?

**Comment by joshtynjala** [comment]
Yes, source maps are not generated for MXML in FlexJS compiler. Only ActionScript right now.

SWF debugging is completely unsupported in the extension right now. That's my next big TODO item.

**Comment by joshtynjala** [comment]
Closing because breakpoints are now supported for MXML for both SWF projects and Apache FlexJS 0.8 projects.
