### ISSUE TITLE
How to point to local compiler for testing

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#290]
Hi Josh,

recently at Apache Royale we added more compiler enhacements to support Flex MX RemoteObject (I'm talking about mx:methods, mx:arguments, symbol).

Right now as3&mxml extension complains from "sysmbol" tag and from some bindings to operation.

I think the extension points to official compiler, I would like to point to local one for testing purposes, could you give guidance if this is possible and where I should look to try in a local build?

Thanks in advance for your help

**Comment by joshtynjala** [comment]
https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Extension-settings#as3mxmlsdkeditor

**Comment by carlosrovira** [comment]
Thanks josh :)
