### ISSUE TITLE
Issue with MXRoyale project

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#291]
Hi Josh,

using latest local build (0.15.0-SNAPSHOT) and pointing with "as3mxml.sdk.editor" to local SDK with latest compiler, I'm seeing as3&mxml gives an error when using a MXRoyale project, I think caused by this:

http://apache-royale-development.20373.n8.nabble.com/Proxy-method-calls-with-RemoteObject-td6717i20.html#a6834

Test case is here:
https://github.com/apache/royale-asjs/tree/develop/examples/mxroyale/RemoteObjectAMFTest

I get:
{
	"resource": "/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/mxroyale/RemoteObjectAMFTest/",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "1310",
	"severity": 8,
	"message": "Unexpected character. '﻿' is not allowed here",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

**Comment by joshtynjala** [comment]
You seem to have an invalid character in *App.mxml*. I see that the encoding appears to be **UTF-8 with BOM** rather than just **UTF-8**. It's probably having an issue with that invisible BOM character at the beginning of the file.

**Comment by joshtynjala** [comment]
The compiler also seems to dislike the `theme` compiler option in *asconfig.json*.

**Comment by carlosrovira** [comment]
Thanks Josh, doing the two fixes and setting up "as3mxml.sdk.editor" with the local build SDK makes all work perfectly. Thanks! :)
