### ISSUE TITLE
Issues with new mx:RemoteObject in AS3&MXML extension

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#292]
Hi Josh,

adding mx:RemoteObject to a normal Royale application gives me two problems:

1.- "symbol" is not detected by AS3&MXML extension.

Add this:

```
<fx:Declarations>
        <mx:RemoteObject id="service" 
                         endpoint="http://localhost:8080/messagebroker/websocket-amf"
                         destination="exampleService">
            <mx:method name="echo">
                <mx:arguments>
                    <symbol>{name_txt.text}</symbol>
                </mx:arguments>
            </mx:method>
        </mx:RemoteObject>        
    </fx:Declarations>
```

And you'll get this for "symbol":

This tag could not be resolved to an ActionScript class. It will be ignored.

2.- Binding reports "Data binding will not be able to detect assignments to 'echo'."

Adding this
`<j:Label text="{(service.echo as Operation).lastResult}"/>`

and "import mx.rpc.remoting.Operation;" to Script block.

But the binding is valid and works ok.

Thanks

**Comment by joshtynjala** [comment]
I can't seem to find a `method` property on RemoteObject, so I'm not sure what this code is even supposed to map to in ActionScript:

```
<mx:method name="echo">
</mx:method>
```

This seems like a Royale compiler issue. Does the project build from the command line?

**Comment by carlosrovira** [comment]
Hi Josh,

yes this compiles thanks to latest Alex addition to support mx:RemoteObject in the compiler.
mx:Method is like rpc Operation, so the compiler should transform this syntax to Operation class.

with the other ticker you just closed and using latest SDK with  "as3mxml.sdk.editor"
 all seems to work right.
