### ISSUE TITLE
Ignoring conditional compilations constants

### ISSUE THREAD

**Issue by yvantaurines** [BowlerHatLLC/vscode-nextgenas#293]
Hi, 

I defined some constants in asconfig.json
"define": [
			{
				"name": "CONFIG::AIR",
				"value": false
			},
			{
				"name": "CONFIG::DEBUG",
				"value": true
			}
		]

I have something like that in my code:
CONFIG::AIR {
    import flash.system.Capabilities;
}

if (CONFIG::AIR) {
    _globalBG.width = Capabilities.screenResolutionX;
    _globalBG.height = Capabilities.screenResolutionY;
}
else {
    _globalBG.width = stage.stageWidth;
    _globalBG.height = stage.stageHeight;
}

I have an error because Capabilities is not imported. But since CONFIG::AIR is set to false, it should just ignore it. Or did I miss something?
Thanks!

**Comment by joshtynjala** [comment]
That code is being handled correctly because you are using CONFIG::AIR like a variable. If you want it to be completely skipped at compilation, you need to do this instead:

```
CONFIG::AIR {
_globalBG.width = Capabilities.screenResolutionX;
_globalBG.height = Capabilities.screenResolutionY;
}
```

Basically, you need to format it the same way that you did for the import.
