### ISSUE TITLE
Can't debug the application

### ISSUE THREAD

**Issue by onselakin** [BowlerHatLLC/vscode-nextgenas#295]
Followed the project setup step by step and created a very minimal project. When I start debugging I get the error:

`Process terminated without establishing connection to debugger. application descriptor not found`

Here is my launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch SWF",
            "profile": "mobileDevice",
            "screensize": "iPhoneRetina",
            "screenDPI": 326,
            "versionPlatform": "IOS"
        },
        {
            "type": "swf",
            "request": "attach",
            "name": "Attach SWF"
        }
    ]
}

```
I can see that VS Code can see the sdk from the lower right corner of the VSCode window.

**EDIT**: Building works fine using "ActionScript: compile debug build" task.

**Comment by joshtynjala** [comment]
> application descriptor not found

It seems to be having trouble finding your Adobe AIR *-app.xml* file. Did you specify it in *asconfig.json* so that it gets populated and copied to your output folder?

**Comment by onselakin** [comment]
I can see that Main.swf and Main-app.xml is copied to the output folder after building. Also the value of the content element is replaced with "Main.swf" in the app descriptor file in the output folder.

**Comment by joshtynjala** [comment]
Can you share the contents of *asconfig.json*?

**Comment by joshtynjala** [comment]
Also, double check that the AIR namespace at the root of *Main-app.xml* is appropriate for the version of the AIR SDK that you're using.

**Comment by onselakin** [comment]
asconfig.json:

```json
{
	"config": "airmobile",
	"compilerOptions": {
		"output": "bin/Main.swf"
	},
	"application": "src/Main-app.xml",
	"files": [
		"src/Main.as"
	]
}
```
Main-app.xml:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<application xmlns="http://ns.adobe.com/air/application/31.0">
	<id>com.example.Main</id>
	<versionNumber>0.0.0</versionNumber>
	<filename>Main</filename>
	<name>Main</name>
	<initialWindow>
		<content>[Path to content will be replaced by Visual Studio Code]</content>
		<visible>true</visible>
	</initialWindow>
</application>
```

VS Code shows the AIR SDK version as 31.0.0.96. I used bot 31.0 and 31.0.0.96 in the app descriptor file.

**Comment by onselakin** [comment]
I can put the project under a repo if it helps.

**Comment by onselakin** [comment]
Sorry, accidentally clicked the close button.

**Comment by joshtynjala** [comment]
If you modify *launch.json* to add a `program` field that points to *bin/Main-app.xml*, does it work?

``` json
{
    "type": "swf",
    "request": "launch",
    "name": "Launch SWF",
    "profile": "mobileDevice",
    "screensize": "iPhoneRetina",
    "screenDPI": 326,
    "versionPlatform": "IOS",
    "program": "bin/Main-app.xml"
}
```

**Comment by onselakin** [comment]
No it doesn't 😕

I can temporarily upload the project to a repo if you'd like to try it yourself but this is not much different from the template you set up in the wiki.

**Comment by joshtynjala** [comment]
You can zip it up and attach it here, if you'd like.

**Comment by onselakin** [comment]
Here it is.

[action-script.zip](https://github.com/BowlerHatLLC/vscode-nextgenas/files/2511563/action-script.zip)

**Comment by onselakin** [comment]
Hey @joshtynjala, any progress on this?

**Comment by joshtynjala** [comment]
I haven't had a chance to try your project yet. I will do it later today.

**Comment by neminovno** [comment]
@onselakin You are missing _.vscode/tasks.json_ file:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "identifier": "build-debug",
            "type": "actionscript",
            "debug": true,
            //"air": "ios",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

and `"preLaunchTask": "build-debug"` line in your _.vscode/launch.json_:
```
{
	// Use IntelliSense to learn about possible SWF debug attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "swf",
			"request": "launch",
			"name": "Launch SWF",
			"profile": "mobileDevice",
			"screensize": "iPhoneRetina",
			"screenDPI": 326,
			"versionPlatform": "IOS",
			"program": "bin/Main-app.xml",

			"preLaunchTask": "build-debug"
		},
		{
			"type": "swf",
			"request": "attach",
			"name": "Attach SWF"
		}
	]
}
```
Note: VSCode says Warning but it works:

> User defined identifiers are deprecated. For custom task used the name as a reference and for tasks provided by extensions use their defined task identifier.

**Comment by joshtynjala** [comment]
I just tried your project. I compiled a debug build and then I launched the debugger. The AIR simulator opened, and the debugger connected successfully.

Perhaps there is something wrong with your AIR SDK? Maybe you should re-download it.

**Comment by neminovno** [comment]
@joshtynjala Same time answering here :) @onselakin probably didn't build before debug.

**Comment by onselakin** [comment]
@joshtynjala I re-downloaded but same error here, really strange.

@neminovno No, I build before pressing Debug :-)

I'm sharing the screenshot of VSCode so you can better see what's going on there.

![image](https://user-images.githubusercontent.com/10635384/47519993-9ec25f80-d897-11e8-9b56-faa2c08b001a.png)

I compile the project without any errors, you can see the bin folder and its contents are created. When I press F5, after the project is built a second time, I get the error you see on the screenshot.

At this stage, I don't see AIR simulator running but I can run Flash Player projector content debugger manually and open the compiled swf. Also I can attach to the Flash player debugger without any problems.

I guess the only difference from Josh's setup is Air simulator doesn't run automatically and this makes me uncomfortable as the development workflow is interrupted.

**Comment by onselakin** [comment]
Ok, a minor development here. 

I never look at the problems window while coding with VSCode because I find the terminal almost always more stable in error reporting but when I looked to the problems list this time I saw this error:

```
unable to open '/Users/onselakin/Development/AirSdk/frameworks/locale/en_TR'.
/Users/onselakin/Development/AirSdk/frameworks/airmobile-config.xml (line: 64)
```

@joshtynjala Does the extension send locale information to the compiler because although I changed the airmobile-config.xml manually it still tried to find a folder named en_TR under the frameworks/locale folder.

**Comment by joshtynjala** [comment]
> although I changed the airmobile-config.xml manually it still tried to find a folder named en_TR under the frameworks/locale folder

Did you restart VSCode after doing this?

**Comment by onselakin** [comment]
> Did you restart VSCode after doing this?

Yes, restarting fixed the locale problem, but the main problem is still there.

> @onselakin Can you post the contents of _bin/Main-app.xml_? It should be similar to _src/Main-app.xml_, but I'd like to make sure that the string replacement worked correctly.

src/Main-app.xml:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<application xmlns="http://ns.adobe.com/air/application/31.0">
	<id>com.example.Main</id>
	<versionNumber>1.0.0</versionNumber>
	<filename>Main</filename>
	<name>Main</name>
	<initialWindow>
		<content>[Path to content will be replaced by Visual Studio Code]</content>
		<visible>true</visible>
	</initialWindow>
</application>
```

bin/Main-app.xml

```xml
<?xml version="1.0" encoding="utf-8" ?>
<application xmlns="http://ns.adobe.com/air/application/31.0">
	<id>com.example.Main</id>
	<versionNumber>1.0.0</versionNumber>
	<filename>Main</filename>
	<name>Main</name>
	<initialWindow>
		<content>Main.swf</content>
		<visible>true</visible>
	</initialWindow>
</application>
```

**Comment by joshtynjala** [comment]
Does the full path to *bin/Main-app.xml* contain any non-Latin UTF characters? Maybe the AIR simulator is can't handle that.

**Comment by onselakin** [comment]
No, there aren't any non-Latin characters. It's under _/Users/onselakin/Development/action-script_ folder.

**Comment by joshtynjala** [comment]
Inside *launch.json*, give the absolute path a try:

```
"program": "Users/onselakin/Development/action-script/bin/Main-app.xml"
```

**Comment by onselakin** [comment]
Finally! I thought I tried this but it seems I haven't!

Thank you @joshtynjala!
