### ISSUE TITLE
additionalOptions "Property additionalOptions is not allowed."

### ISSUE THREAD

**Issue by devlfm** [BowlerHatLLC/vscode-nextgenas#296]
Hi @joshtynjala nice job!

I'm trying to add all my projects to vscode, some of them need compiler args..

I need additionOptions, but I get this error:

> Invalid asconfig.json:
> $.compilerOptions.additionalOptions: is not defined in the schema and the schema does not allow additional properties
> $.type: does not match the regex pattern ^lib$
> 
> The terminal process terminated with exit code: 1

How can I set this:
"-locale=pt_PT,es_ES,en_US,fr_FR,pt_BR -allow-source-path-overlap=true -source-path=locale/{locale}  -keep-as3-metadata=Inject,Autowire,EventHandler,Mediate,Dispatcher,PostConstruct,PreDestroy,ViewAdded,ViewRemoved,ViewNavigator"

It will be better to use a dumped config?

**Comment by joshtynjala** [comment]
`additionalOptions` is not a child of `compilerOptions`. Instead, you should at `additionalOptions` at the same level as `compilerOptions`.

**Comment by devlfm** [comment]
Thank you @joshtynjala totally forgot.. worked nice 👍
