### ISSUE TITLE
flex modules

### ISSUE THREAD

**Issue by devlfm** [BowlerHatLLC/vscode-nextgenas#297]
Hi @joshtynjala ,

How do I handle modules?
![image](https://user-images.githubusercontent.com/11923375/47582201-a5aaaa00-d94b-11e8-87b2-c0da4c61034d.png)

is there any entry on asconfig.json?

**Comment by joshtynjala** [comment]
First off, let me say that I've never used Flex modules. As I understand it, though, they are separate SWFs, so they'll need to be compiled on their own.

You should be able to take advantage of the ability to add multiple *asconfig.json* files to a single project. Create a *asconfig.modulename.json* file for each module. Then, you'll be able to run a separate compile task for each one.

As I understand it, you can make VSCode tasks depend on other tasks, so it should be possible to build them all in one step, if needed.

**Comment by devlfm** [comment]
Hi @joshtynjala , not sure about that.. maybe guys form flexjs could help here (alex or harbs)? I know that you can generate modules separated or "optimized" for one app.
It would be great if we could have a asconfig.modules.json

**Comment by devlfm** [comment]
maybe this can help: https://forums.adobe.com/thread/1342158?tstart=0

**Comment by devlfm** [comment]
Sorry for the spam, but just for helping, [from here](https://www.len.ro/work/flex-applications-size-optimization/):

```
Module optimization
The last step I did was to emulate the flex builder “optimize module for application” functionality. This consists in 2 steps. First when the application swf is compiled with the link-report option to generate a xml file with the classes used:

<mxmlc file="${src.dir}/myApp.mxml" output="${build.dir}/myApp.swf"
 keep-generated-actionscript="false" incremental="true" debug="${debug}" optimize="${optimize}"
 allow-source-path-overlap="true" locale="${locale}"
 link-report="${build.dir}/report.xml">
 <load-config filename="${FLEX_HOME}/frameworks/flex-config.xml" />
 <source-path path-element="${FLEX_HOME}/frameworks" />
 <source-path path-element="${locale.dir}/{locale}" />

 <compiler.library-path dir="${FLEX_HOME}/frameworks" append="true">
 <include name="libs" />
 <include name="../bundles/{locale}" />
 </compiler.library-path>
 <compiler.library-path dir="libs" append="true">
 <include name="*.swc" />
 </compiler.library-path>
 <runtime-shared-library-path path-element="${build.dir}/myApp-lib.swc">
 <url rsl-url="/myApp/myApp-library.swf" />
 </runtime-shared-library-path>
 </mxmlc>
Then the modules are compiled using the load-externs option:

<mxmlc file="${src.dir}/myModule.mxml" output="${build.dir}/myModule.swf"
 keep-generated-actionscript="false" incremental="true" debug="${debug}" optimize="${optimize}"  
 allow-source-path-overlap="true" locale="${locale}"
 load-externs="${build.dir}/report.xml">
 <source-path path-element="${src.dir}" />
 <source-path path-element="${locale.dir}/{locale}" />
 <load-config filename="${FLEX_HOME}/frameworks/flex-config.xml" />
 <compiler.library-path dir="${FLEX_HOME}/frameworks" append="true">
 <include name="libs" />
 <include name="../bundles/{locale}" />
 </compiler.library-path>
 <compiler.library-path dir="libs" append="true">
 <include name="*.swc" />
 </compiler.library-path>
 <runtime-shared-library-path path-element="${build.dir}/myApp-lib.swc">
 <url rsl-url="/myApp/myApp-library.swf" />
 </runtime-shared-library-path>
 </mxmlc>
This way the modules will be even smaller.

Final results after all these steps are that the application is now almost 10 times smaller.
```


Actually I'm using this approach with ant for a custom (semi)CI, and final sizes match from FlashBuilder, so it seams thats the right way.

**Comment by joshtynjala** [comment]
Yeah, you should be able to do something similar to your Ant script using multiple *asconfig.json* files, like I described. If any compiler options don't exist in `compilerOptions`, you can add them to `additionalOptions` instead (but let me know if any are missing so that I can expose them properly). Everything should be good to go without any changes to the extension.

**Comment by devlfm** [comment]
thank you @joshtynjala I'll try that, and if works you can add to documentation :)
