### ISSUE TITLE
Can not define compiler constants with string values

### ISSUE THREAD

**Issue by gosgame** [BowlerHatLLC/vscode-nextgenas#298]
When I am trying to define a compiler constant with a string value, the compiler throws an error like;

`Error: The initializer for a configuration value must be a compile time constant.`

You can replicate the issue by adding this block to any asconfig.json file;

```
"define": [
	{
		"name": "BUILD::version_all",
		"value": "v0.0.0"
	}
]
```

In addition, if I set the value to "0", it is parsed as a number. Trying to reference it as a String in code also throws the following error;

`Implicit coercion of a value of type Number to an unrelated type String.`

If I load constants from a separate config file, no problem occurs. Example file content;

```
<?xml version="1.0" encoding="utf-8"?>
<flex-config>
    <define append="true">
      <name>BUILD::version_all</name>
      <value>"v0.0.0"</value>
    </define>
</flex-config>
```

Is it a bug or am I missing something?

**Comment by joshtynjala** [comment]
Notice how you need to include quotes in the XML config file:

```
<value>"v0.0.0"</value>
```

It's basically the same thing in *asconfig.json*:

```
{
	"name": "BUILD::version_all",
	"value": "\"v0.0.0\""
}
```

It's kind of weird, but the reason for this is that the compiler evaluates quoted values as expressions, so "1 + 2" gets evaluated to 3. This means that two sets of quotes are required for strings. This is required when you pass compiler constants with **mxmlc** on the command line too!

Note: if the above syntax doesn't work, try using single quotes instead (I can never remember which one to use... or if both work):

```
"value": "'v0.0.0'"
```

**Comment by gosgame** [comment]
Thanks, Josh. Using single quotes solved it;

**Comment by gosgame** [comment]
Thanks, Josh. Using single quotes solved it;

`"value": "'v0.0.0'"`

Note: Your first suggestion throws the following error;
`Error: Unexpected character. '\' is not allowed here`

**Comment by joshtynjala** [comment]
Thanks! Since Adobe took down their Flex documentation that explained conditional compilation, I'll add this detail directly to the *asconfig.json* documentation.
