### ISSUE TITLE
No auto-reload on changed files

### ISSUE THREAD

**Issue by JimmyGot** [BowlerHatLLC/vscode-nextgenas#30]
Files don't get reloaded when a file was changed in another editor and have a newer time stamp.

**Comment by joshtynjala** [comment]
ActionScript and MXML files? That's strange. I specifically made sure that works.

**Comment by JimmyGot** [comment]
It's working now in both MXML and AS. Maybe that happened when I got the "... exited with error null". Don't know anymore. Please disregard.
