### ISSUE TITLE
Memory usage is too large

### ISSUE THREAD

**Issue by Stay-by-my-side** [BowlerHatLLC/vscode-nextgenas#300]
Is there any way to solve the problem of excessive memory usage?😵😵

<img width="304" alt="qq20181102-183907 2x" src="https://user-images.githubusercontent.com/37897071/47910697-9fc64300-dece-11e8-99c6-7b81acd05d16.png">
<img width="1677" alt="qq20181102-184028 2x" src="https://user-images.githubusercontent.com/37897071/47910770-d308d200-dece-11e8-8792-1c2e59e7e607.png">

**Comment by joshtynjala** [comment]
Is the memory usage relatively stable over time? If there's an obvious memory leak, I can try to look into that. However, I doubt that there's anything I can do about high memory usage in general. Most of the memory should be completely managed by the ActionScript compiler and would be out of my hands.

**Comment by Stay-by-my-side** [comment]
Memory is stable, so that should be a problem with the ActionScript compiler. thank
