### ISSUE TITLE
Jewel Component definition snippet

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#301]
Hi Josh,

just see the commit to add Jewel snippet. I tried it and just let you know that it will be more useful if the  generated prefix will be "j" instead of "js", since js use to be for "Basic", so it use to be already used in the file (normally we have "fx", "js" and "j", when using Jewel in namespace definitions)

**Comment by piotrzarzycki21** [comment]
Hi Carlos,

As for the snippet. Do you need anything for Jewel in that matter? I could add it into my [extension](https://github.com/piotrzarzycki21/royalesnippetsforvscode) as well.

**Comment by carlosrovira** [comment]
Hi Piotr,
thanks!, I can't think nothing for now, but I'll think about it and report to you.

**Comment by carlosrovira** [comment]
one question. Is your extension available in VSCode, or you must to install it from GitHub?
Maybe it could be great to join that to Josh extension so all is packaged in just one plugin and be more easy and convenient for users. Just suggesting :)

**Comment by piotrzarzycki21** [comment]
It's available as plugin, the same as Josh's extension. You have instruction in readme and link as I remember. Probably you can find it through search in the plugin area.

**Comment by joshtynjala** [comment]
> Maybe it could be great to join that to Josh extension so all is packaged in just one plugin and be more easy and convenient for users.

It's perfect as a separate extension that can be disabled when desired. For example, in Flex projects, users don't want to see Royale snippets. Users wouldn't have that level of control over the snippets if they were included in the as3mxml extension.

Someone could create a Royale "extension pack" that installs both together, which gives the users convenience and choice.

**Comment by joshtynjala** [comment]
> it will be more useful if the generated prefix will be "j" instead of "js"

I meant to do that. Thanks for catching my copy/paste mistake!

**Comment by carlosrovira** [comment]
Ok thanks, I searched in VSCode for "Royale" and it appears :)
thanks!
