### ISSUE TITLE
Is identifier in tasks.json used anymore?

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#303]
In Wiki: is step 4. needed in [Build-an-ActionScript-project-in-Visual-Studio-Code](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Build-an-ActionScript-project-in-Visual-Studio-Code#set-the-default-build-task) due to it is no more used? As it is no more mentioned in Debug pages to be used for `preLaunchTask`.

**Comment by joshtynjala** [comment]
Thanks for pointing that out! I've now removed it.
