### ISSUE TITLE
Problem with comments in MXML

### ISSUE THREAD

**Issue by JimmyGot** [BowlerHatLLC/vscode-nextgenas#31]
Toggling a line comment in the Script section of an MXML file produces  &lt;!--  --&gt;  instead of  //

**Comment by joshtynjala** [comment]
This is similar to what I mentioned in your the snippets issue #27. I'm not sure how to tell VSCode that MXML contains ActionScript and should behave differently in an &lt;fx:Script&gt; element.

**Comment by JimmyGot** [comment]
I see. Seems like telling VSCode about the Script section is a tough and also an important issue.

**Comment by joshtynjala** [comment]
Okay, I was able to figure out how to make VSCode see the <fx:Script> element as ActionScript. The keyboard shortcuts for comments will work correctly in the next version.
