### ISSUE TITLE
Completion list contains duplicates when variables have [Bindable] metadata

### ISSUE THREAD

**Issue by JimmyGot** [BowlerHatLLC/vscode-nextgenas#32]
Auto-completions get listed twice in MXML Script section.

**Comment by joshtynjala** [comment]
I cannot reproduce this behavior. Can you provide an example MXML class where you're seeing duplicate items in the list? Thanks!

**Comment by JimmyGot** [comment]
Hmm, it's all part of a huge Flex 4.6 app. I'll see if I can extract something.
May it have something to do with the fact that I'm settings the "nextgenas.frameworksdk" in a project-specific settings.json and "nextgenas.flexjssdk" in the default settings.json ?

**Comment by joshtynjala** [comment]
No, when nextgenas.frameworksdk is set, the framework from nextgenas.flexjssdk should be completely ignored. The compiler has a special "flexlib" path that determines where to find the framework SWCs and things.

**Comment by JimmyGot** [comment]
Still looking for a suitable MXML file, but here's a screenshot first:

![vscodedoublelisting](https://cloud.githubusercontent.com/assets/6039735/20817024/a0d55190-b825-11e6-9691-e87dd66c98ea.png)

**Comment by joshtynjala** [comment]
Is the text on the right side the same if you highlight the duplicate one? I have code to skip overrides, but maybe it's similar. If we can find two different locations for the same property, that might give us a clue.

**Comment by JimmyGot** [comment]
Yes, the locations are identical for each pair (acContent, de_DE$..., en_US$...).

**Comment by JimmyGot** [comment]
There's something interesting that I found:

a) this var gets listed twice:   	[Bindable] public var xml : XML;
b) this var gets listed only once:     public var xml : XML;
     
Tried switching multiple times and same result each time.

**Comment by joshtynjala** [comment]
That's a good clue! I'll take a look. Bindable variables get converted to properties, and I could see how that process might contribute to this issue.
