### ISSUE TITLE
ActionScript auto-closing pairs don't work in MXML <fx:Script> elements

### ISSUE THREAD

**Issue by JimmyGot** [BowlerHatLLC/vscode-nextgenas#34]
~~~1.  would be nice not to list such auto-completions as "_022b8a8bb94dcc4df9c30f9be950d42865d2131b86f63db0b7ed44680524ce44_flash_display_Sprite"~~~
Moved to new issue #41

2.  insert closing "}", ")", "]" automatically

**Comment by joshtynjala** [comment]
1. I'm not really sure where those come from, and I'd rather not write some code that tries to detect weird names like this and have it omit completion items from real projects that shouldn't be removed.

2. The extension already does this!

**Comment by joshtynjala** [comment]
(Also, both of these should be considered separate issues. They're completely unrelated to each other)

**Comment by JimmyGot** [comment]
2.  sometimes it's closing, sometimes not. It's not doing it before the closing of an MXML tag. 
i.e.: ... id="/> if there's no space between " and /
Also in MXML <Script> when calling a function:  showPage(
Closing seems to work fine in *.as files.

**Comment by JimmyGot** [comment]
Sorry, my post got cut off:
Also in MXML's `<Script>` : showPage(
But closing `(` it's working in *.as files.

**Comment by joshtynjala** [comment]
> It's not doing it before the closing of an MXML tag.

The extension only tells VSCode which characters should behave like that. There's nothing I can do to change that particular case.

**Comment by joshtynjala** [comment]
> Also in MXML's `<Script>` : showPage(
> But closing `(` it's working in *.as files.

Yeah, I reproduce that, even with my recent change that fixed the comments. It looks like ( and things will auto-close in JavaScript embedded in HTML, so there must be a way to make that work. I'll investigate.
