### ISSUE TITLE
FlexJS Snippets

### ISSUE THREAD

**Issue by GotJimmy** [BowlerHatLLC/vscode-nextgenas#36]
I've been thinking about the complaints on the FlexJS mailing list about the missing documentation. Now what if somebody familiar with the components in FlexJS writes basically a list of all the components with their respective most used properties and styles and I convert them to user snippets to be used in NextGenAS?
IMO, that would go a long way to make up for the missing docs and allow newbies to get started much faster. I cannot write this list myself since I found myself struggling with FlexJS to just set colors on a label and other basic stuff (and that after years of working with AS3/Flex)  :(

What do you think? Might someone be willing to write this list?

Something like (in Flex):

<s:VGroup id="vg" x="10" y="20" gap="10" 
     paddingLeft="0" paddingRight="0" paddingTop="0" paddingBottom="0"
     horizontalAlign="left" verticalAlign="top" ....... />

<s:Label id="lbl" color="0xff0000" textAlign="center"  ........ />

**Comment by joshtynjala** [comment]
That would certainly make sense. I'm hoping to see someone more experienced with FlexJS add examples of the most common features for each component to the wiki. It seems like no one is interested, though. I've never used the FlexJS components, so I'd need to learn them too.

**Comment by JimmyGot** [comment]
Ok I'll ask on the FlexJS list. Feel free to jump in for support ;)
