### ISSUE TITLE
asconfig.json example incorrect

### ISSUE THREAD

**Issue by hnuecke** [BowlerHatLLC/vscode-nextgenas#37]
the given example for asconfig.json is incorrect:
The last compiler option (in this case "library-path") must not be followed by a comma.

Example given:
`{

    "config": "js",

    "compilerOptions": {

        "debug": true,

        "library-path": [

            "libs"

        ]**,**    // this comma is not correct

    },

    "files":
`

**Comment by joshtynjala** [comment]
Where can I find this example so that I can fix it?

**Comment by joshtynjala** [comment]
Found it! Thank you!

**Comment by hnuecke** [comment]
Wow, you're fast ;-)
Thanks


Am 02.12.2016 um 04:54 schrieb Josh Tynjala:
