### ISSUE TITLE
Support Apache FlexJS SDK built with Maven

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/vscode-nextgenas#42]
A Maven-built SDK cannot be passed to the nextgenas.flexjssdk setting. It probably has a different directory structure than other ActionScript SDKs.

**Comment by carlosrovira** [comment]
Hope you could solve this since it will be a great step forward. Thanks to thinking on it! :)

**Comment by carlosrovira** [comment]
So great! That's really huge! Thanks for doing this! :)
