### ISSUE TITLE
MXML problem: "This tag could not be resolved to an ActionScript class. It will be ignored."

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#46]
Build works, but have this in Problems panel:
message: 'This tag could not be resolved to an ActionScript class. It will be ignored.' at: '2,1'

Using v0.2.0, settings is visible in preview:
![image](https://cloud.githubusercontent.com/assets/1468887/21290474/05abb166-c4bc-11e6-9304-0e37e0e495aa.png)

**Comment by joshtynjala** [comment]
In your VSCode workspace settings, you need to point nextgenas.frameworksdk to the same SDK that you're using in tasks.json. That's only if you're compiling with an SDK other than FlexJS.

https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Extension-settings#nextgenasframeworksdk

**Comment by neminovno** [comment]
So FlexJS is like default SDK, ok I got it. Thanks!

**Comment by neminovno** [comment]
Except missing config, this problem happens when you got two xmlns in same tag after deleting charaters.. Like this: 
![codenexgenas_mxml_bug_bac1_legacenc](https://cloud.githubusercontent.com/assets/1468887/21335446/4a501308-c65f-11e6-9ae3-ceab47e983c7.gif)

After VSCode restart, there is no problem.

**Comment by joshtynjala** [comment]
I cannot reproduce this issue. Can you provide steps to follow to make it happen? Thanks!

**Comment by neminovno** [comment]
I updated to 0.2.1, and can't reproduce it. But now this code says "no problems":
```
<?xml version="1.0" encoding="utf-8"?>
<s:Application  xmlns:fx="http://ns.adobe.com/mxml/2009"xmlns:s="library://ns.adobe.com/flex/spark"
                xmlns:mx="library://ns.adobe.com/flex/mx">
</s:Application>
```
Note: there is no space between '...2009"xmlns...'
![image](https://cloud.githubusercontent.com/assets/1468887/21361114/e1e68a52-c6e2-11e6-8b4c-e0b29d405bdf.png)

**Comment by joshtynjala** [comment]
That is a compiler issue.
