### ISSUE TITLE
Setting lib location breaks SDK references

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-nextgenas#49]
I have an asconfig file which contains the following:

    "compilerOptions": {
        "debug": false,
        "js-output-type": "flexjs",
        "source-map": true,
        "library-path": [
            "lib"
        ],
        "external-library-path": [
        "typedefs"
        ]
    },
The lib folder and the typedefs folder is being correctly used, but some Framework files are not being used. I have XML classes and none of the js files related to that are being copied to the js-debug folder.

I'm pretty sure the problem is that it's using "-library-path=lib" instead of "-library-path+=lib".

If I build using ant with the "+=" option, it works.

**Comment by joshtynjala** [comment]
You can see here that when library-path is parsed in the JSON, appendPaths() is called:

https://github.com/BowlerHatLLC/asconfigc/blob/v0.3.0/source/com/nextgenactionscript/asconfigc/CompilerOptionsParser.as#L97

In appendPaths(), it uses += here:

https://github.com/BowlerHatLLC/asconfigc/blob/v0.3.0/source/com/nextgenactionscript/asconfigc/CompilerOptionsParser.as#L277

Perhaps asconfigc is using a different SDK than your Ant build?

**Comment by joshtynjala** [comment]
Since I didn't get a response, I'm closing for now feel free to reopen when you have more information.

**Comment by Harbs** [comment]
Sorry I did not get back sooner.

I am using the same SDK for both ant and VSCode. The VSCode build is still not copying the XML files.

I can send you my project off-line if that'll help you find the issue.

**Comment by Harbs** [comment]
To be super-clear: The difference between the build is that the following files (at the base level) are not being copied into js-debug:
Namespace.js
QName.js
XML.js
XMLList.js

**Comment by joshtynjala** [comment]
This appears to be a bug in FlexJS. I created a simple MXML file with the following code:

```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:js="library://ns.apache.org/flexjs/basic">
    <js:initialView>
        <js:View initComplete="test()">
            <js:Label text="Hello World" x="100" y="100"/>
        </js:View>
    </js:initialView>
    <js:valuesImpl>
        <js:SimpleCSSValuesImpl />
    </js:valuesImpl>
    <fx:Script><![CDATA[
        private function test():void
        {
            var xml:XML = new XML();
        }
    ]]></fx:Script>
</js:Application>
```

Then, I ran the following command in my terminal, completely outside of VSCode:

```
<path to flexjs>/js/bin/mxmlc src/HelloFlexJS.mxml
```

Just as you describe, those JS files are not present.

I tested with both 0.7.0 and a nightly build from Jan 6, 2017.
