### ISSUE TITLE
MXML propose html5.button only

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#52]
Hi,

just updated to 0.3.1 and I'm seeing class suggestions in MXML. So good! :)

As you know I'm working with a project that has HTML and MDL swcs. I find when I write "butt"
NextGen suggest only the one Button import (the one from html5), but I want to import the MDL one not the HTML5.

For example if I start writing "badg" ... is suggest MDL Badge (since there's no other Badge component in FlexJS

So maybe the solution should be that NGAS would suggest all Button classes found in SWC libs attached right?

Thanks!

**Comment by joshtynjala** [comment]
The extension will definitely suggest multiple classes with the same name, if available. At the very least, you should have seen both html.Button and html5.Button. I recall seeing both yesterday when I made the GIF of automatic inputs. That was in ActionScript, but it searches the same compilation units for MXML types. I'll double check when I'm at my desk later today.

**Comment by carlosrovira** [comment]
Hi Josh,
you're right, in MXML and AS3 code blocks is working ok, so I think is ok.
Maybe the problem could be working on property tag, but I think that would be residual and not important.

While testing I try a a class of constants (MaterialIconType) in binding and that pull lots of stuff, while in AS3 code blocks pulls all the constants, in the binding not. Maybe bindings still are not covered right?

btw, I think NextGenAS is working great. Very happy with this new toy :D

Thanks!

**Comment by joshtynjala** [comment]
Correct, there is no completion for {} bindings in MXML. Event attributes in MXML also don't have completion yet. I just opened two issues, #53 and #54, to keep track of these.
