### ISSUE TITLE
Implementing "Code templates": in the extension or use VS Code Snippets?

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#55]
How should MXML and ActionScript "Code templates" (like in FB 4.7) be implemented?
Is it good enough to just use [VS Code Snippets](https://code.visualstudio.com/Docs/customization/userdefinedsnippets) or it must be somehow related with the extension?

**Comment by joshtynjala** [comment]
In my opinion, snippets seem like the right choice for that sort of thing.

**Comment by ok-at-github** [comment]
There're some vscode extensions available  e.g. 
https://marketplace.visualstudio.com/items?itemName=brpaz.file-templates

HTH,
Olaf
