### ISSUE TITLE
Wiki/Docs: "nextgenas.flexjssdk" replaced by "nextgenas.sdk.editor" 

### ISSUE THREAD

**Issue by ok-at-github** [BowlerHatLLC/vscode-nextgenas#57]
Hi Josh,
seems to me that the docs are not up-to-date.
Keep up the great work!

Thanks,
Olaf

![grafik](https://cloud.githubusercontent.com/assets/14052170/22499872/809aa0d0-e861-11e6-9371-cb08b35522f9.png)

**Comment by joshtynjala** [comment]
Thanks!
