### ISSUE TITLE
How to point to bin/MyApp.swf from src/MyApp-app.xml content field?

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#67]
I was having problems with [content field](http://help.adobe.com/en_US/air/build/WSfffb011ac560372f2fea1812938a6e463-8000.html#WSfffb011ac560372f2fea1812938a6e463-7ff4):
`inital content not found`
because could not find a way to set content field in app descriptor XML file to point to .swf file which I set per wiki in bin folder.

Had unsuccessful results with:
```
<content>MyApp.swf</content>
<content>../bin/MyApp.swf</content>
<content>bin/MyApp.swf</content>
<content>bin\MyApp.swf</content>
<content>bin\\MyApp.swf</content>
...
```

After moving MyApp-app.xml and MyApp.swf to root folder, everything works ok.

Also problem could be that:
"The value specified for the content element is the URL for the main content file of the application. This may be either a SWF file or an HTML file. The URL is specified relative to the root of the application installation folder. (**When running an AIR application with ADL, the URL is relative to the folder containing the application descriptor file. You can use the root-dir parameter of ADL to specify a different root directory.**)"

**Comment by joshtynjala** [comment]
If you set the "application" field in asconfig.json, the AIR application descriptor will also be copied to the bin directory, and the content field will be populated with your SWF name.

https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/asconfig.json#application-optional

Make sure you update asconfigc, if you installed it a while ago. The application field in asconfig.json is new, so you must use the latest version.

**Comment by neminovno** [comment]
In that case what should content field in AIR application descriptor file look like?
I see that AIR application descriptor is now copied to bin folder, but still after F5 to start debug I got:
```
Process terminated without establishing connection to debugger.
initial content not found

```

**Comment by neminovno** [comment]
I got it, need to change in launch.json
` "program": "${workspaceRoot}/src/Main-app.xml",`
to
` "program": "${workspaceRoot}/bin/Main-app.xml",`

**Comment by joshtynjala** [comment]
Yep, I should have mentioned that part too!
