### ISSUE TITLE
Goto doesn't work until particular file is modified

### ISSUE THREAD

**Issue by ok-at-github** [BowlerHatLLC/vscode-nextgenas#68]
I've opened some of the FlexJS examples with vscode (Windows7) and found that goto doesn't work immediately.
It immediately works after the particular file is modified e.g. by just adding a blank.
There's no need to save the file.

**Comment by joshtynjala** [comment]
I can reproduce this issue with the MDLExample.

However, it seems to work correctly in some of my pure ActionScript projects, so I think this is related to MXML specifically.

**Comment by joshtynjala** [comment]
Can you give this a try again in the new 0.4.1 update? I didn't actually change anything in response to this bug report, but goto definition is now working for me in MDLExample (where it was failing previously). I suspect that one of my other changes may have helped here. Thanks!

**Comment by ok-at-github** [comment]
Hi Josh,
I've overlooked your comments, sorry!
I've checked out 0.4.2. and as you mentioned it seems to me that the issue is solved, thank you!

Olaf
