### ISSUE TITLE
Goto doesn't work with FlexJS 0.8 nightly framework classes

### ISSUE THREAD

**Issue by ok-at-github** [BowlerHatLLC/vscode-nextgenas#69]
Unfortunately, it's not possible to jump to FlexJS framework classes by using goto.

Thanks,
Olaf

**Comment by joshtynjala** [comment]
I have confirmed that this is not working for a FlexJS nightly build, but it works with version 0.7.0.

**Comment by ok-at-github** [comment]
Good to know, thanks!
