### ISSUE TITLE
Feature request: Auto completion of the package name 

### ISSUE THREAD

**Issue by ok-at-github** [BowlerHatLLC/vscode-nextgenas#70]
Hi,
FlashBuilder is able to auto complete the package name if you just place the cursor in the first line after the 'package' keyword and call IntelliSense by pressing "CTRL" with "SPACE".
The package name will be immediately inserted or corrected.

Would be great to have this feature in vscode ;-)

Thanks,
Olaf

**Comment by joshtynjala** [comment]
Yeah, I like that feature too!
