### ISSUE TITLE
Specifying an app descriptor in launch.json opens the file in xcode

### ISSUE THREAD

**Issue by jackwlee01** [BowlerHatLLC/vscode-nextgenas#71]
Instead of opening ADL, the app descriptor is opened in xcode when I start debugging. 

Here is my launch.json file
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch AIR mobile",
            "program": "${workspaceRoot}/bin/app-ios.xml",
            "profile": "mobileDevice",
            "screensize": "iPhoneRetina",
            "screenDPI": 326,
            "versionPlatform": "IOS",
            "preLaunchTask": "asconfigc"
        }
    ]
}
```

Here is my asconfig.json file:
```
{
	"config": "airmobile",
	"application":"bin/app-ios.xml",
	"compilerOptions": {
		"debug": false,
		"output":"bin/main.swf",
		"strict":false,
		"library-path": [
			"lib/",
			"lib/swf",
			"lib/ane"
		],
		"dump-config": "dumped-config.xml",
		"load-config":[
			"compiler-config.xml"
		]
	},
	"files":[
		"src/Main.as"
	]
}
```

And this is my tasks.json file:
```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "asconfigc",
	"isShellCommand": true,
	"args": [
		"--flexHome=/Users/jacklee/SDKs/Adobe-Air-24"
	],
	"showOutput": "always"
}
```

**Comment by joshtynjala** [comment]
The debugger expects a certain naming scheme for the AIR application descriptor. The name must end with `-app.xml` or be equal to `application.xml`. You can see this in the open source debugger from Apache Flex, but it's probably also true in Adobe SDKs:

https://github.com/apache/flex-falcon/blob/0b3c78b95152939ade64afbaf8c455f1dd2eb38d/debugger/src/main/java/flash/tools/debugger/concrete/PlayerSessionManager.java#L192

**Comment by jackwlee01** [comment]
Thanks, I was unaware of this!

**Comment by zeh** [comment]
Wow. Ran into the same problem. Weird that I've always used it with the air compiler/sdk before without a problem but it was a requirement here. FDT (what I used before, but not anymore) probably did some magic to get it to work.

**Comment by joshtynjala** [comment]
It's possible that FDT manually launches ADL and then attaches the debugger to the running process. I think the way that I've integrated the debugger into VSCode is closer to the way that Flash Builder handles a debug session, which involves the debugger launching the runtime process automatically.
