### ISSUE TITLE
Cannot specify extdir in launch.json for mobile projects.

### ISSUE THREAD

**Issue by jackwlee01** [BowlerHatLLC/vscode-nextgenas#72]
My project is using ANEs. Is it possible to specify extdir in launch.json?

**Comment by joshtynjala** [comment]
Native extensions are not supported yet!

Duplicate #60

**Comment by joshtynjala** [comment]
FYI: The latest version of the AS3 & MXML extension for VSCode now has a better user experience for debugging with ANEs. It detects ANEs specified in the `airOptions` section of *asconfig.json* and it will automatically unpackage them for the AIR simulator. You no longer need to configure ANEs in *launch.json*.

Starting now, all you need to do is add your ANE folder to [`extdir`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#extdir) in `airOptions` and [`external-library-path`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#external-library-path) in `compilerOptions`.
