### ISSUE TITLE
compilerOptions.library-path doesn't like spaces

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-nextgenas#73]
Adding a library path with a space in causes compiler errors. This is what I've found:

1. Adding a single entry containing spaces to the library-path array causes the compiler to stop at the first space it finds e.g. if the library path is `"C:\Projects\Foo Bar"`, the compiler will throw `Error: unable to open 'C:\Projects\Foo'`
2. If I have multiple library paths in the array and at least one contains a space, the compiler throws `Error: default arguments may not be interspersed with other options`

In this particular case I am developing an AIR application in Windows

UPDATE: Using \u0020 has the same effect
UPDATE 2: Referencing a folder that contains SWC files with spaces in their names doesn't cause an issue

**Comment by joshtynjala** [comment]
Do you see these errors only when you build the project, or do they also appear during development?

**Comment by esidegallery** [comment]
It's build only. I'm still getting code completion and no development errors, so I guess this is a compiler issue. However, I haven't found any issues in other environments with spaces in library-paths, so perhaps this is related to how the plugin passes these arguments to the compiler, e.g. encoding the spaces?

**Comment by joshtynjala** [comment]
Yeah, it's probably how `asconfigc` is building the command line options when it calls mxmlc.

**Comment by joshtynjala** [comment]
Fixed in BowlerHatLLC/asconfigc@b56637e91817c8ace447e9070b0c818065605aa2

Sorry for the trouble. I will release an update to asconfigc in the near future.

**Comment by esidegallery** [comment]
Thank you Josh!

**Comment by joshtynjala** [comment]
I just released [asconfigc](https://www.npmjs.com/package/asconfigc) 0.4.1. Update with NPM and this issue will be fixed.
