### ISSUE TITLE
Does not watch for added/removed/changed files in source-path

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/vscode-nextgenas#77]
Can't use the FileSystemWatcher API from VSCode. According to the docs:

> Note that only files within the current workspace folders can be watched.

Source: https://code.visualstudio.com/docs/extensionAPI/vscode-api#workspace.createFileSystemWatcher

Probably going to need to use Java's WatchService instead:

https://docs.oracle.com/javase/tutorial/essential/io/notification.html
https://docs.oracle.com/javase/7/docs/api/java/nio/file/WatchService.html

**Comment by piotrzarzycki21** [comment]
Hi @joshtynjala ,

I did notice yesterday that adding new file/class in Moonshine is not recognizable - Is this what you mean by this issue ?
Another question is - Does your changes in this issue will require also some changes in Moonshine's code for that area. - Of course if you know at this early stage. I'm asking cause if it is I will raise an issue there additionally.

Thanks,
Piotr

**Comment by joshtynjala** [comment]
If the file is in the project directory, all changes will be detected. Files added/removed in an external directory added with the -source-path compiler option are not currently detected. This issue also affects Moonshine.

**Comment by piotrzarzycki21** [comment]
Yesterday when I was using Moonshine for Flex project adding file into the project directory wasn't work for me. Class wasn't visible in code completion. However I have seen today that there were one time where after adding new class to the project it was discovered. Right after that error #121 occurred and I was trying add another class and The second one wasn't discovered. I hope update will helps with some of that weird behavior.

Thanks Josh.
