### ISSUE TITLE
Can not resolve config constant

### ISSUE THREAD

**Issue by JarrodCope** [BowlerHatLLC/vscode-nextgenas#8]
Hi Josh,
Nice work on the plugin, this is an exciting project!

Just tried the plugin for the first time with an existing AIR project.
I'm getting a compile error trying to use config constants in my code eg
`DEFINE::ANDROID {
	//android code
}
DEFINE::IOS {
	//ios code
}`

I've tried to define the constants in the asconfig.json as 
`"additionalOptions": "-define+=DEFINE::IOS,true -define+=DEFINE::ANDROID,false`

**Comment by joshtynjala** [comment]
The VSCode extension doesn't currently know about additionalOptions. I recently added it to [asconfigc](https://github.com/BowlerHatLLC/asconfigc), and haven't gotten it into the extension yet. I'll get that hooked up in next version, and expose "define" as a proper compilerOption too. I can't believe that one slipped through! If you can ignore the errors in the editor for the time being, building the project should work. Sorry for the trouble!

**Comment by joshtynjala** [comment]
I just released version 0.1.1 of the extension. It now supports the define compilerOption.
