### ISSUE TITLE
If you enter only "<" within mxml code, no problem reported

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#80]
This code should have problem like: "tag not closed" or similar. Extra is only one "<" char:
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:js="library://ns.apache.org/flexjs/basic">
	<js:initialView>
	<
		<js:View> 
			<js:Label text="Hello World" x="100" y="100"/>
		</js:View>
	</js:initialView>
	<js:valuesImpl>
		<js:SimpleCSSValuesImpl />
	</js:valuesImpl>
</js:Application>
```

**Comment by joshtynjala** [comment]
I meant for [this comment](https://github.com/BowlerHatLLC/vscode-nextgenas/issues/79#issuecomment-298935282) to appear in this issue.

> If you can successfully build the same project, and the compiler output doesn't include an error either, then it's a compiler bug. If there is an error, then the extension has a bug and I need to figure out where the error is exposed.

**Comment by neminovno** [comment]
Hm, then it's a compiler bug.

**Comment by joshtynjala** [comment]
Compiler bugs may be reported in the Apache Flex JIRA:

https://issues.apache.org/jira/browse/FLEX/

**Comment by neminovno** [comment]
Thanks. Now, issue is reported in the Apache Flex JIRA as [FLEX-35302](https://issues.apache.org/jira/browse/FLEX-35302).
