### ISSUE TITLE
Help with Intellisense/autocomplete?

### ISSUE THREAD

**Issue by tlhinman** [BowlerHatLLC/vscode-nextgenas#87]
Hello--

I recently started using VSCode in conjunction with Adobe Animate CC to work on Flash projects in AS3. I installed the NextGen ActionScript extension primarily to get Intellisense and autocomplete for both Flash libraries and references within my project. I've messed around a lot with the required asconfig.json and I can't get any results. I get either hundreds of errors and warnings or simply "Failed to load project configuration options."

I don't think I'm particularly interested in actual compilation through the extension, as I simply use Shift-Cmd-Enter in Animate to compile and test the SWF.

Here's a representation of my directory structure.

- dirA
  - dirB
    - dirC
      - UtilFolder
        - Util1.as
        - Util2.as
        - etc.
      - ProjFolder
        - Project1
          - SourceFile1.as
          - etc.
        - Project2
          - SourceFile2.as
          - etc.
        - etc.

At the top of each source file, the package path is:

`dirB.dirC.ProjFolder.[Project name]`

Optimally, I'd include the Util files in autocompletion as well. I've tried putting asconfig.json in dirA (trying to match the package path) and in [Project name]. I've tried various combinations of using source-path and include-sources and such. All to no avail.

Can anyone help? Am I way off base because I'm using this along with Animate? Thank you for your time.

**Comment by joshtynjala** [comment]
I'm at ApacheCon this week, so I may not find the time to respond for a few days. Thanks for your patience!

**Comment by tlhinman** [comment]
No problem; thanks!

**Comment by joshtynjala** [comment]
Is your FLA file in dirA or the parent directory of dirA? You probably want asconfig.json to be in the same directory as your FLA file.

Does your FLA file have a document class? The path to your document class is what you would put in the "files" field of asconfig.json. Maybe something like this will be enough:

``` json
{
	"files": [
		"dirA/MyDocumentClass.as"
	]
}
```

If you don't have a document class, then it might get tricky to use VSCode. Animate works a bit differently than the other ActionScript SDKs, and it does some things behind the scenes for you (like automatically providing its own entry point if there is no document class). Without a document class, it may be possible set the source-path, like this:

``` json
{
	"compilerOptions": {
		"source-path": [
			"dirA"
		]
	}
}
```

I'm not sure how well that will work, but it might be worth a try if you don't have a document class.

> I get either hundreds of errors and warnings

It would help if you could share some of the first errors and warnings that you see. They might offer a clue.

**Comment by tlhinman** [comment]
I see. Here's my folder structure including the Animate files (which are XFLs rather than FLAs):
- baseFolder
  - src
    - dirA
      - [continued as posted above]
  - fla
    - dirA2 [same name as dirA]
      - allProjects
        - Project1
          - Project1.xfl
          - [other stuff like DOMDocument.xml, bin and LIBRARY folders, etc.]
        - [more projects]

So, in Animate's ActionScript Settings window, I have `../../../src/dirA` under Source Path, and the document class is `dirB.dirC.ProjFolder.Project1.Main`.

I put `asconfig.json` in `Project1` (i.e. the same folder as `Main.as`) with a very simple definition: "config" is "flex" and "files" is "[Main.as]". That gave me the pile of errors, many of which seem to be like the following (where `Foo.as` is another source file in the folder):

`No externally-visible definition with the name 'Foo' was found.`
`An externally-visible definition with the name 'dirB.dirC.ProjFolder.Project1.Foo' was unexpectedly found.`

Many other errors refer to class names as well. Also, for some involved MP3s, I get `Internal error in outgoing dependency subsystem` errors, which refer to an `ArrayIndexOutOfBoundsException` in Java.

So it looks like the big problem is that it's not using the right path somehow. Not sure if it's a simple adjustment I'm missing, or if I'm going to have to open all of `baseFolder` in VSCode, or something in between.

Thanks again for helping me through this!

**Comment by joshtynjala** [comment]
Typically with other ActionScript SDKs, the main/document class is placed in the top-level package, so having `dirB.dirC.ProjFolder.Project1.Main` be the document class may make things a little tricky. Even if Animate allows it, the VSCode extension uses a compiler from another SDK for its code intelligence features, so you may run into issues. Off the top of my head, I don't recall if putting Main as the top-level package is actually required by these SDKs or if it's simply what everybody does.

I suggest opening `src` in VSCode and adding the `asconfig.json` file there. Try it with the following content:

``` json
{
	"compilerOptions":
	{
		"source-path": [
			"dirA"
		]
	}
	"files": [
		"dirA/dirB/dirC/ProjFolder/Project1/Main.as"
	]
}
```

I'm hoping that with the source-path defined, the compiler will be smart enough to see that `Main` is in the `dirB.dirC.ProjFolder.Project1` package and that dirA is the root for all of the other classes too.

(I realize that you have multiple projects, but I'd rather see if we can get this to work at all with one project before we go into how to make it work with more than one)

**Comment by tlhinman** [comment]
That seems to have been effective! I don't have those class-related errors anymore and it looks like I have autocomplete. A few existing shortcomings remain.

It'd be really nice to rectify these issues caused by my entire src directory being open:

- I get the errors and warnings for all my other projects. It's a big list.
- In many cases, files in different projects share a name, so the autocomplete suggestions can get pretty noisy.

I'll mention these two as well; they're kind of annoying but can be ignored or avoided with a little redesigning:

- The "Internal error in outgoing dependency subsystem" messages remain.
- The system can't find definitions for classes that are defined only by AS Linkage in Animate (i.e. the name by itself in Class and some other known class for the Base Class).

Thanks!

**Comment by joshtynjala** [comment]
> I get the errors and warnings for all my other projects. It's a big list.

The compiler gives errors for all files in the source-path, even for files that aren't included in the final output. It may be possible for me to omit unreferenced files from the list of errors (if you open an unreferenced file for editing, the errors would be included, of course).

> In many cases, files in different projects share a name, so the autocomplete suggestions can get pretty noisy.

I don't think there's a good way to change this in VSCode. Even if a file isn't referenced in the current project, if it's on the source-path, it needs to show up in the completion list. People would consider that a bug, otherwise.

If you want to avoid this, you'll need to restructure your projects so that project-specific files go in their own separate directories instead of one main source path that is shared by all projects. As a bonus, if you restructured like this, you would no longer see the errors from files in other projects. Plus, if you hope to create multiple projects in VSCode, you'll need asconfig.json files in separate directories anyway.

> The "Internal error in outgoing dependency subsystem" messages remain.

That sounds like a bug in the VSCode extension, but unless I could reproduce it myself, it could be hard to figure out why that's happening.

> The system can't find definitions for classes that are defined only by AS Linkage in Animate (i.e. the name by itself in Class and some other known class for the Base Class).

VSCode would need some kind of way to talk to Animate. Or maybe a way to parse FLA/XFL files. Unfortunately, either one is unlikely to happen any time soon!

**Comment by tlhinman** [comment]
All understandable. Just wasn't sure if there was an easy way to exclude certain paths through the config or whatnot. The feature you mention would be most welcome. (Not too keen on reorganizing the long-established directory structure given imminent Flash deprecation.)

I'll just disregard the "Internal error..." messages, and if the AS Linkage errors really bother me, I can always create very basic AS definitions that simply extend the base class and then change the linkage accordingly.

I think that addresses everything. Thanks very much again!
