### ISSUE TITLE
Code Action: Generate missing method

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/vscode-nextgenas#95]
Similar to [Flash Builder's Generate from usage feature](http://help.adobe.com/en_US/flashbuilder/using/WSe4e4b720da9dedb5344c6f711358acdda1d-7fff.html#WSe4e4b720da9dedb56fd3caca12e6bb494bb-7fec). If a method is referenced, but it doesn't exist yet, the editor should offer to generate a stub.

Should be possible to implement this one similarly to the code action for missing imports. If a method doesn't exist, create a code action to generate it.

**Comment by joshtynjala** [comment]
Creating a Diagnostic with DiagnosticSeverity.Hint may be the way to trigger a code action without having it show up in the problems list.

**Comment by neminovno** [comment]
This is not working in MXML.

Reproduce code:
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
	xmlns:js="library://ns.apache.org/royale/express">

	<fx:Script>
		<![CDATA[

			private function nameFunc():void
			{
				callme();
			}
			
		]]>
	</fx:Script>
	<js:initialView>
		<js:View>
			<js:Label text="Hello World" x="100" y="100"/>
		</js:View>
	</js:initialView>
</js:Application>
```
Place editor cursor within "callme" and click light bubble (or CTRL+.) and click "Generate Method" - nothing happens.
![image](https://user-images.githubusercontent.com/1468887/36864913-5da7fdee-1d8e-11e8-9266-02d7938aabc2.png)

Same is for "Generate Field variable". 

Only "Generate Local variable" works as expected (although one more TAB spacing, before newly generated local variable line, would be great).
![image](https://user-images.githubusercontent.com/1468887/36865521-0d6faece-1d90-11e8-9378-624b0fe2def5.png)

**Comment by joshtynjala** [comment]
@neminovno Thanks! I copied your comment into a new issue so that I can keep track of it: #183
