### ISSUE TITLE
Building a SWF object

### ISSUE THREAD

**Issue by uconnjosh** [BowlerHatLLC/vscode-nextgenas#97]
Hi there,

Apologies if this isn't the proper method of reaching out, but I'm having some issues.

I'm trying to follow the Wiki instructions to compile a simple Hello World into the SWF format. 
Every time I build the application, it does build successfully, but into a a javascript file (Main.js) and html file (index.html)... I can't seem to build a SWF object!

Just wondering if I'm missing something, or if there is some sort of bug that's causing the AS to ignore the `output` flag.

Here is everything I have:
(src/Main.as)
```
package
{
	import flash.display.Sprite;
	import flash.text.TextField;

	public class Main extends Sprite
	{
		public function Main()
		{
			var tf:TextField = new TextField();
			tf.text = "Hello World";
			addChild(tf);
		}
	}
}
```
(asconfig.json)

```
{
	"config": "flex",
	"compilerOptions": {
		"output": "bin/Main.swf",
		"debug": true		
	},
	"files":
	[
		"src/Main.as"
	]
}
```
(tasks.json)
```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "asconfigc",
	"isShellCommand": true,
	"args": [
		"--debug=true",
		"--flexHome=/Users/joshpaul/.nvm/versions/node/v6.5.0/lib/node_modules/flexjs"
	],
	"showOutput": "always"
}
```

Thanks!!!!

**Comment by joshtynjala** [comment]
Looks like asconfigc has a bug. It should properly detect that you're trying to build a SWF file as output. I can get that fixed.

In the meantime, please try setting the --flexHome argument in your tasks.json file to a different SDK. FlexJS is only needed to power the code intelligence. Other SDKs may be used to compile your project. You should also set the nextgenas.sdk.framework setting to the same SDK as the one you use in tasks.json.

**Comment by uconnjosh** [comment]
@joshtynjala thanks so much for responding... I'll try using a different SDK!

**Comment by joshtynjala** [comment]
Now that FlexJS 0.8.0 is available, if you want to use that SDK, you can set the targets compiler option to ensure that a SWF file is created:

``` json
{
	"config": "flex",
	"compilerOptions": {
		"targets": [
			"SWF"
		]
		"output": "bin/Main.swf",
		"debug": true		
	},
	"files":
	[
		"src/Main.as"
	]
}
```

Non-FlexJS SDKs will create SWFs automatically, so this is only needed when compiling a SWF with FlexJS.
